// AUTO GENERATED BY JNIGEN 1.0.0. DO NOT EDIT!

// ignore_for_file: annotate_overrides
// ignore_for_file: argument_type_not_assignable
// ignore_for_file: camel_case_extensions
// ignore_for_file: camel_case_types
// ignore_for_file: constant_identifier_names
// ignore_for_file: comment_references
// ignore_for_file: doc_directive_unknown
// ignore_for_file: file_names
// ignore_for_file: inference_failure_on_untyped_parameter
// ignore_for_file: invalid_internal_annotation
// ignore_for_file: invalid_use_of_internal_member
// ignore_for_file: library_prefixes
// ignore_for_file: lines_longer_than_80_chars
// ignore_for_file: no_leading_underscores_for_library_prefixes
// ignore_for_file: no_leading_underscores_for_local_identifiers
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: only_throw_errors
// ignore_for_file: overridden_fields
// ignore_for_file: prefer_double_quotes
// ignore_for_file: unintended_html_in_doc_comment
// ignore_for_file: unnecessary_cast
// ignore_for_file: unnecessary_non_null_assertion
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: unused_element
// ignore_for_file: unused_field
// ignore_for_file: unused_import
// ignore_for_file: unused_local_variable
// ignore_for_file: unused_shown_name
// ignore_for_file: use_super_parameters

import 'dart:core' as core$_;
import 'dart:core' show Object, String;

import 'package:jni/_internal.dart' as jni$_;
import 'package:jni/jni.dart' as jni$_;

import '../../../../../java/util/Locale.dart' as locale$_;

import 'LocalePicker.dart' as localepicker$_;

/// from: `dev.zeekr.invictus_android.internal.app.JniLocalePicker$JniLocaleSelectionListener`
extension type JniLocalePicker$JniLocaleSelectionListener._(
  jni$_.JObject _$this
)
    implements jni$_.JObject {
  static final _class = jni$_.JClass.forName(
    r'dev/zeekr/invictus_android/internal/app/JniLocalePicker$JniLocaleSelectionListener',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<JniLocalePicker$JniLocaleSelectionListener> type =
      $JniLocalePicker$JniLocaleSelectionListener$Type$();

  /// Maps a specific port to the implemented interface.
  static final core$_.Map<
    core$_.int,
    $JniLocalePicker$JniLocaleSelectionListener
  >
  _$impls = {};
  static jni$_.JObjectPtr _$invoke(
    core$_.int port,
    jni$_.JObjectPtr descriptor,
    jni$_.JObjectPtr args,
  ) {
    return _$invokeMethod(
      port,
      jni$_.MethodInvocation.fromAddresses(0, descriptor.address, args.address),
    );
  }

  static final jni$_.Pointer<
    jni$_.NativeFunction<
      jni$_.JObjectPtr Function(jni$_.Int64, jni$_.JObjectPtr, jni$_.JObjectPtr)
    >
  >
  _$invokePointer = jni$_.Pointer.fromFunction(_$invoke);

  static jni$_.Pointer<jni$_.Void> _$invokeMethod(
    core$_.int $p,
    jni$_.MethodInvocation $i,
  ) {
    try {
      final $d = $i.methodDescriptor.toDartString(releaseOriginal: true);
      final $a = $i.args;
      if ($d == r'onLocaleSelected(Ljava/util/Locale;)V') {
        _$impls[$p]!.onLocaleSelected(($a![0] as locale$_.Locale));
        return jni$_.nullptr;
      }
    } catch (e) {
      return jni$_.ProtectedJniExtensions.newDartException(e);
    }
    return jni$_.nullptr;
  }

  static void implementIn(
    jni$_.JImplementer implementer,
    $JniLocalePicker$JniLocaleSelectionListener $impl,
  ) {
    late final jni$_.RawReceivePort $p;
    $p = jni$_.RawReceivePort(($m) {
      if ($m == null) {
        _$impls.remove($p.sendPort.nativePort);
        $p.close();
        return;
      }
      final $i = jni$_.MethodInvocation.fromMessage($m);
      final $r = _$invokeMethod($p.sendPort.nativePort, $i);
      $i.args?.release();
      jni$_.ProtectedJniExtensions.returnResult($i.result, $r);
    });
    implementer.add(
      r'dev.zeekr.invictus_android.internal.app.JniLocalePicker$JniLocaleSelectionListener',
      $p,
      _$invokePointer,
      [
        if ($impl.onLocaleSelected$async)
          r'onLocaleSelected(Ljava/util/Locale;)V',
      ],
    );
    final $a = $p.sendPort.nativePort;
    _$impls[$a] = $impl;
  }

  factory JniLocalePicker$JniLocaleSelectionListener.implement(
    $JniLocalePicker$JniLocaleSelectionListener $impl,
  ) {
    final $i = jni$_.JImplementer();
    implementIn($i, $impl);
    return $i.implement<JniLocalePicker$JniLocaleSelectionListener>();
  }
}

extension JniLocalePicker$JniLocaleSelectionListener$$Methods
    on JniLocalePicker$JniLocaleSelectionListener {
  static final _id_onLocaleSelected = JniLocalePicker$JniLocaleSelectionListener
      ._class
      .instanceMethodId(r'onLocaleSelected', r'(Ljava/util/Locale;)V');

  static final _onLocaleSelected =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public fun onLocaleSelected(locale: java.util.Locale): kotlin.Unit`
  void onLocaleSelected(locale$_.Locale locale) {
    final _$$selfRef = reference;
    final _$locale = locale.reference;
    _onLocaleSelected(
      _$$selfRef.pointer,
      _id_onLocaleSelected.pointer,
      _$locale.pointer,
    ).check();
  }
}

abstract base mixin class $JniLocalePicker$JniLocaleSelectionListener {
  factory $JniLocalePicker$JniLocaleSelectionListener({
    required void Function(locale$_.Locale locale) onLocaleSelected,
    core$_.bool onLocaleSelected$async,
  }) = _$JniLocalePicker$JniLocaleSelectionListener;

  void onLocaleSelected(locale$_.Locale locale);
  core$_.bool get onLocaleSelected$async => false;
}

final class _$JniLocalePicker$JniLocaleSelectionListener
    with $JniLocalePicker$JniLocaleSelectionListener {
  _$JniLocalePicker$JniLocaleSelectionListener({
    required void Function(locale$_.Locale locale) onLocaleSelected,
    this.onLocaleSelected$async = false,
  }) : _onLocaleSelected = onLocaleSelected;

  final void Function(locale$_.Locale locale) _onLocaleSelected;
  final core$_.bool onLocaleSelected$async;

  void onLocaleSelected(locale$_.Locale locale) {
    return _onLocaleSelected(locale);
  }
}

final class $JniLocalePicker$JniLocaleSelectionListener$Type$
    extends jni$_.JType<JniLocalePicker$JniLocaleSelectionListener> {
  @jni$_.internal
  const $JniLocalePicker$JniLocaleSelectionListener$Type$();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Ldev/zeekr/invictus_android/internal/app/JniLocalePicker$JniLocaleSelectionListener;';
}

/// from: `dev.zeekr.invictus_android.internal.app.JniLocalePicker$JniLocaleSelectionListenerImpl`
extension type JniLocalePicker$JniLocaleSelectionListenerImpl._(
  jni$_.JObject _$this
)
    implements localepicker$_.LocalePicker$LocaleSelectionListener {
  static final _class = jni$_.JClass.forName(
    r'dev/zeekr/invictus_android/internal/app/JniLocalePicker$JniLocaleSelectionListenerImpl',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<JniLocalePicker$JniLocaleSelectionListenerImpl>
  type = $JniLocalePicker$JniLocaleSelectionListenerImpl$Type$();
  static final _id_new$ = _class.constructorId(
    r'(Ldev/zeekr/invictus_android/internal/app/JniLocalePicker$JniLocaleSelectionListener;)V',
  );

  static final _new$ =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void <init>(dev.zeekr.invictus_android.internal.app.JniLocalePicker$JniLocaleSelectionListener jniLocaleSelectionListener)`
  /// The returned object must be released after use, by calling the [release] method.
  factory JniLocalePicker$JniLocaleSelectionListenerImpl(
    JniLocalePicker$JniLocaleSelectionListener jniLocaleSelectionListener,
  ) {
    final _$$classRef = _class.reference;
    final _$jniLocaleSelectionListener = jniLocaleSelectionListener.reference;
    return _new$(
      _$$classRef.pointer,
      _id_new$.pointer,
      _$jniLocaleSelectionListener.pointer,
    ).object<JniLocalePicker$JniLocaleSelectionListenerImpl>();
  }
}

extension JniLocalePicker$JniLocaleSelectionListenerImpl$$Methods
    on JniLocalePicker$JniLocaleSelectionListenerImpl {
  static final _id_onLocaleSelected =
      JniLocalePicker$JniLocaleSelectionListenerImpl._class.instanceMethodId(
        r'onLocaleSelected',
        r'(Ljava/util/Locale;)V',
      );

  static final _onLocaleSelected =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public fun onLocaleSelected(locale: java.util.Locale): kotlin.Unit`
  void onLocaleSelected(locale$_.Locale locale) {
    final _$$selfRef = reference;
    final _$locale = locale.reference;
    _onLocaleSelected(
      _$$selfRef.pointer,
      _id_onLocaleSelected.pointer,
      _$locale.pointer,
    ).check();
  }
}

final class $JniLocalePicker$JniLocaleSelectionListenerImpl$Type$
    extends jni$_.JType<JniLocalePicker$JniLocaleSelectionListenerImpl> {
  @jni$_.internal
  const $JniLocalePicker$JniLocaleSelectionListenerImpl$Type$();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Ldev/zeekr/invictus_android/internal/app/JniLocalePicker$JniLocaleSelectionListenerImpl;';
}

/// from: `dev.zeekr.invictus_android.internal.app.JniLocalePicker`
extension type JniLocalePicker._(jni$_.JObject _$this)
    implements jni$_.JObject {
  static final _class = jni$_.JClass.forName(
    r'dev/zeekr/invictus_android/internal/app/JniLocalePicker',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<JniLocalePicker> type = $JniLocalePicker$Type$();
  static final _id_new$ = _class.constructorId(r'()V');

  static final _new$ =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public void <init>()`
  /// The returned object must be released after use, by calling the [release] method.
  factory JniLocalePicker() {
    final _$$classRef = _class.reference;
    return _new$(
      _$$classRef.pointer,
      _id_new$.pointer,
    ).object<JniLocalePicker>();
  }
}

final class $JniLocalePicker$Type$ extends jni$_.JType<JniLocalePicker> {
  @jni$_.internal
  const $JniLocalePicker$Type$();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Ldev/zeekr/invictus_android/internal/app/JniLocalePicker;';
}
