// AUTO GENERATED BY JNIGEN 0.15.0. DO NOT EDIT!

// ignore_for_file: annotate_overrides
// ignore_for_file: argument_type_not_assignable
// ignore_for_file: camel_case_extensions
// ignore_for_file: camel_case_types
// ignore_for_file: constant_identifier_names
// ignore_for_file: comment_references
// ignore_for_file: doc_directive_unknown
// ignore_for_file: file_names
// ignore_for_file: inference_failure_on_untyped_parameter
// ignore_for_file: invalid_internal_annotation
// ignore_for_file: invalid_use_of_internal_member
// ignore_for_file: library_prefixes
// ignore_for_file: lines_longer_than_80_chars
// ignore_for_file: no_leading_underscores_for_library_prefixes
// ignore_for_file: no_leading_underscores_for_local_identifiers
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: only_throw_errors
// ignore_for_file: overridden_fields
// ignore_for_file: prefer_double_quotes
// ignore_for_file: unintended_html_in_doc_comment
// ignore_for_file: unnecessary_cast
// ignore_for_file: unnecessary_non_null_assertion
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: unused_element
// ignore_for_file: unused_field
// ignore_for_file: unused_import
// ignore_for_file: unused_local_variable
// ignore_for_file: unused_shown_name
// ignore_for_file: use_super_parameters

import 'dart:core' as core$_;
import 'dart:core' show Object, String, bool, double, int;

import 'package:jni/_internal.dart' as jni$_;
import 'package:jni/jni.dart' as jni$_;

import '../../../../../android/content/Context.dart' as context$_;

import '../../../../../android/os/LocaleList.dart' as localelist$_;

import '../../../../../java/util/Locale.dart' as locale$_;

/// from: `dev.zeekr.invictus_android.internal.app.LocalePicker$Companion`
class LocalePicker$Companion extends jni$_.JObject {
  @jni$_.internal
  @core$_.override
  final jni$_.JType<LocalePicker$Companion> $type;

  @jni$_.internal
  LocalePicker$Companion.fromReference(jni$_.JReference reference)
    : $type = type,
      super.fromReference(reference);

  static final _class = jni$_.JClass.forName(
    r'dev/zeekr/invictus_android/internal/app/LocalePicker$Companion',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<LocalePicker$Companion?> nullableType =
      $LocalePicker$Companion$NullableType$();

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<LocalePicker$Companion> type =
      $LocalePicker$Companion$Type$();
  static final _id_getClazz = _class.instanceMethodId(
    r'getClazz',
    r'()Ljava/lang/Class;',
  );

  static final _getClazz =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public final java.lang.Class<?> getClazz()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JObject getClazz() {
    return _getClazz(
      reference.pointer,
      _id_getClazz as jni$_.JMethodIDPtr,
    ).object<jni$_.JObject>(const jni$_.$JObject$Type$());
  }

  static final _id_getSystemAssetLocales = _class.instanceMethodId(
    r'getSystemAssetLocales',
    r'()[Ljava/lang/String;',
  );

  static final _getSystemAssetLocales =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public fun getSystemAssetLocales(): kotlin.Array<kotlin.String>`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JArray<jni$_.JString> getSystemAssetLocales() {
    return _getSystemAssetLocales(
      reference.pointer,
      _id_getSystemAssetLocales as jni$_.JMethodIDPtr,
    ).object<jni$_.JArray<jni$_.JString>>(
      const jni$_.$JArray$Type$<jni$_.JString>(jni$_.$JString$Type$()),
    );
  }

  static final _id_getSupportedLocales = _class.instanceMethodId(
    r'getSupportedLocales',
    r'(Landroid/content/Context;)[Ljava/lang/String;',
  );

  static final _getSupportedLocales =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public fun getSupportedLocales(context: android.content.Context): kotlin.Array<kotlin.String>`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JArray<jni$_.JString> getSupportedLocales(context$_.Context context) {
    final _$context = context.reference;
    return _getSupportedLocales(
      reference.pointer,
      _id_getSupportedLocales as jni$_.JMethodIDPtr,
      _$context.pointer,
    ).object<jni$_.JArray<jni$_.JString>>(
      const jni$_.$JArray$Type$<jni$_.JString>(jni$_.$JString$Type$()),
    );
  }

  static final _id_getAllAssetLocales = _class.instanceMethodId(
    r'getAllAssetLocales',
    r'(Landroid/content/Context;Z)Ljava/util/List;',
  );

  static final _getAllAssetLocales =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>, jni$_.Int32)>,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              int,
            )
          >();

  /// from: `public fun getAllAssetLocales(context: android.content.Context, isInDeveloperMode: kotlin.Boolean): kotlin.collections.List<dev.zeekr.invictus_android.internal.app.LocalePicker.LocaleInfo>`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JList<LocalePicker$LocaleInfo> getAllAssetLocales(
    context$_.Context context,
    bool z,
  ) {
    final _$context = context.reference;
    return _getAllAssetLocales(
      reference.pointer,
      _id_getAllAssetLocales as jni$_.JMethodIDPtr,
      _$context.pointer,
      z ? 1 : 0,
    ).object<jni$_.JList<LocalePicker$LocaleInfo>>(
      const jni$_.$JList$Type$<LocalePicker$LocaleInfo>(
        $LocalePicker$LocaleInfo$Type$(),
      ),
    );
  }

  static final _id_setLocaleSelectionListener = _class.instanceMethodId(
    r'setLocaleSelectionListener',
    r'(Ldev/zeekr/invictus_android/internal/app/LocalePicker$LocaleSelectionListener;)V',
  );

  static final _setLocaleSelectionListener =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public fun setLocaleSelectionListener(listener: dev.zeekr.invictus_android.internal.app.LocalePicker.LocaleSelectionListener): kotlin.Unit`
  void setLocaleSelectionListener(
    LocalePicker$LocaleSelectionListener localeSelectionListener,
  ) {
    final _$localeSelectionListener = localeSelectionListener.reference;
    _setLocaleSelectionListener(
      reference.pointer,
      _id_setLocaleSelectionListener as jni$_.JMethodIDPtr,
      _$localeSelectionListener.pointer,
    ).check();
  }

  static final _id_updateLocale = _class.instanceMethodId(
    r'updateLocale',
    r'(Ljava/util/Locale;)V',
  );

  static final _updateLocale =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public fun updateLocale(locale: java.util.Locale): kotlin.Unit`
  void updateLocale(locale$_.Locale locale) {
    final _$locale = locale.reference;
    _updateLocale(
      reference.pointer,
      _id_updateLocale as jni$_.JMethodIDPtr,
      _$locale.pointer,
    ).check();
  }

  static final _id_updateLocales = _class.instanceMethodId(
    r'updateLocales',
    r'(Landroid/os/LocaleList;)V',
  );

  static final _updateLocales =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public fun updateLocales(locals: android.os.LocaleList): kotlin.Unit`
  void updateLocales(localelist$_.LocaleList localeList) {
    final _$localeList = localeList.reference;
    _updateLocales(
      reference.pointer,
      _id_updateLocales as jni$_.JMethodIDPtr,
      _$localeList.pointer,
    ).check();
  }

  static final _id_getLocales = _class.instanceMethodId(
    r'getLocales',
    r'()Landroid/os/LocaleList;',
  );

  static final _getLocales =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public fun getLocales(): android.os.LocaleList`
  /// The returned object must be released after use, by calling the [release] method.
  localelist$_.LocaleList getLocales() {
    return _getLocales(
      reference.pointer,
      _id_getLocales as jni$_.JMethodIDPtr,
    ).object<localelist$_.LocaleList>(const localelist$_.$LocaleList$Type$());
  }

  static final _id_new$ = _class.constructorId(
    r'(Lkotlin/jvm/internal/DefaultConstructorMarker;)V',
  );

  static final _new$ =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `synthetic public void <init>(kotlin.jvm.internal.DefaultConstructorMarker defaultConstructorMarker)`
  /// The returned object must be released after use, by calling the [release] method.
  factory LocalePicker$Companion(jni$_.JObject? defaultConstructorMarker) {
    final _$defaultConstructorMarker =
        defaultConstructorMarker?.reference ?? jni$_.jNullReference;
    return LocalePicker$Companion.fromReference(
      _new$(
        _class.reference.pointer,
        _id_new$ as jni$_.JMethodIDPtr,
        _$defaultConstructorMarker.pointer,
      ).reference,
    );
  }
}

final class $LocalePicker$Companion$NullableType$
    extends jni$_.JType<LocalePicker$Companion?> {
  @jni$_.internal
  const $LocalePicker$Companion$NullableType$();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Ldev/zeekr/invictus_android/internal/app/LocalePicker$Companion;';

  @jni$_.internal
  @core$_.override
  LocalePicker$Companion? fromReference(jni$_.JReference reference) =>
      reference.isNull ? null : LocalePicker$Companion.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$Type$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<LocalePicker$Companion?> get nullableType => this;

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($LocalePicker$Companion$NullableType$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($LocalePicker$Companion$NullableType$) &&
        other is $LocalePicker$Companion$NullableType$;
  }
}

final class $LocalePicker$Companion$Type$
    extends jni$_.JType<LocalePicker$Companion> {
  @jni$_.internal
  const $LocalePicker$Companion$Type$();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Ldev/zeekr/invictus_android/internal/app/LocalePicker$Companion;';

  @jni$_.internal
  @core$_.override
  LocalePicker$Companion fromReference(jni$_.JReference reference) =>
      LocalePicker$Companion.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$Type$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<LocalePicker$Companion?> get nullableType =>
      const $LocalePicker$Companion$NullableType$();

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($LocalePicker$Companion$Type$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($LocalePicker$Companion$Type$) &&
        other is $LocalePicker$Companion$Type$;
  }
}

/// from: `dev.zeekr.invictus_android.internal.app.LocalePicker$LocaleInfo$Companion`
class LocalePicker$LocaleInfo$Companion extends jni$_.JObject {
  @jni$_.internal
  @core$_.override
  final jni$_.JType<LocalePicker$LocaleInfo$Companion> $type;

  @jni$_.internal
  LocalePicker$LocaleInfo$Companion.fromReference(jni$_.JReference reference)
    : $type = type,
      super.fromReference(reference);

  static final _class = jni$_.JClass.forName(
    r'dev/zeekr/invictus_android/internal/app/LocalePicker$LocaleInfo$Companion',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<LocalePicker$LocaleInfo$Companion?> nullableType =
      $LocalePicker$LocaleInfo$Companion$NullableType$();

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<LocalePicker$LocaleInfo$Companion> type =
      $LocalePicker$LocaleInfo$Companion$Type$();
  static final _id_getClazz = _class.instanceMethodId(
    r'getClazz',
    r'()Ljava/lang/Class;',
  );

  static final _getClazz =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public final java.lang.Class<?> getClazz()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JObject getClazz() {
    return _getClazz(
      reference.pointer,
      _id_getClazz as jni$_.JMethodIDPtr,
    ).object<jni$_.JObject>(const jni$_.$JObject$Type$());
  }

  static final _id_new$ = _class.constructorId(
    r'(Lkotlin/jvm/internal/DefaultConstructorMarker;)V',
  );

  static final _new$ =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `synthetic public void <init>(kotlin.jvm.internal.DefaultConstructorMarker defaultConstructorMarker)`
  /// The returned object must be released after use, by calling the [release] method.
  factory LocalePicker$LocaleInfo$Companion(
    jni$_.JObject? defaultConstructorMarker,
  ) {
    final _$defaultConstructorMarker =
        defaultConstructorMarker?.reference ?? jni$_.jNullReference;
    return LocalePicker$LocaleInfo$Companion.fromReference(
      _new$(
        _class.reference.pointer,
        _id_new$ as jni$_.JMethodIDPtr,
        _$defaultConstructorMarker.pointer,
      ).reference,
    );
  }
}

final class $LocalePicker$LocaleInfo$Companion$NullableType$
    extends jni$_.JType<LocalePicker$LocaleInfo$Companion?> {
  @jni$_.internal
  const $LocalePicker$LocaleInfo$Companion$NullableType$();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Ldev/zeekr/invictus_android/internal/app/LocalePicker$LocaleInfo$Companion;';

  @jni$_.internal
  @core$_.override
  LocalePicker$LocaleInfo$Companion? fromReference(
    jni$_.JReference reference,
  ) => reference.isNull
      ? null
      : LocalePicker$LocaleInfo$Companion.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$Type$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<LocalePicker$LocaleInfo$Companion?> get nullableType => this;

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode =>
      ($LocalePicker$LocaleInfo$Companion$NullableType$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType ==
            ($LocalePicker$LocaleInfo$Companion$NullableType$) &&
        other is $LocalePicker$LocaleInfo$Companion$NullableType$;
  }
}

final class $LocalePicker$LocaleInfo$Companion$Type$
    extends jni$_.JType<LocalePicker$LocaleInfo$Companion> {
  @jni$_.internal
  const $LocalePicker$LocaleInfo$Companion$Type$();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Ldev/zeekr/invictus_android/internal/app/LocalePicker$LocaleInfo$Companion;';

  @jni$_.internal
  @core$_.override
  LocalePicker$LocaleInfo$Companion fromReference(jni$_.JReference reference) =>
      LocalePicker$LocaleInfo$Companion.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$Type$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<LocalePicker$LocaleInfo$Companion?> get nullableType =>
      const $LocalePicker$LocaleInfo$Companion$NullableType$();

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($LocalePicker$LocaleInfo$Companion$Type$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($LocalePicker$LocaleInfo$Companion$Type$) &&
        other is $LocalePicker$LocaleInfo$Companion$Type$;
  }
}

/// from: `dev.zeekr.invictus_android.internal.app.LocalePicker$LocaleInfo`
class LocalePicker$LocaleInfo extends jni$_.JObject {
  @jni$_.internal
  @core$_.override
  final jni$_.JType<LocalePicker$LocaleInfo> $type;

  @jni$_.internal
  LocalePicker$LocaleInfo.fromReference(jni$_.JReference reference)
    : $type = type,
      super.fromReference(reference);

  static final _class = jni$_.JClass.forName(
    r'dev/zeekr/invictus_android/internal/app/LocalePicker$LocaleInfo',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<LocalePicker$LocaleInfo?> nullableType =
      $LocalePicker$LocaleInfo$NullableType$();

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<LocalePicker$LocaleInfo> type =
      $LocalePicker$LocaleInfo$Type$();
  static final _id_Companion = _class.staticFieldId(
    r'Companion',
    r'Ldev/zeekr/invictus_android/internal/app/LocalePicker$LocaleInfo$Companion;',
  );

  /// from: `static public final dev.zeekr.invictus_android.internal.app.LocalePicker$LocaleInfo$Companion Companion`
  /// The returned object must be released after use, by calling the [release] method.
  static LocalePicker$LocaleInfo$Companion get Companion => _id_Companion.get(
    _class,
    const $LocalePicker$LocaleInfo$Companion$Type$(),
  );

  static final _id_getObj = _class.instanceMethodId(
    r'getObj',
    r'()Ljava/lang/Object;',
  );

  static final _getObj =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public final java.lang.Object getObj()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JObject getObj() {
    return _getObj(
      reference.pointer,
      _id_getObj as jni$_.JMethodIDPtr,
    ).object<jni$_.JObject>(const jni$_.$JObject$Type$());
  }

  static final _id_new$ = _class.constructorId(r'(Ljava/lang/Object;)V');

  static final _new$ =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void <init>(java.lang.Object object)`
  /// The returned object must be released after use, by calling the [release] method.
  factory LocalePicker$LocaleInfo(jni$_.JObject object) {
    final _$object = object.reference;
    return LocalePicker$LocaleInfo.fromReference(
      _new$(
        _class.reference.pointer,
        _id_new$ as jni$_.JMethodIDPtr,
        _$object.pointer,
      ).reference,
    );
  }

  static final _id_new$1 = _class.constructorId(
    r'(Ljava/lang/String;Ljava/util/Locale;)V',
  );

  static final _new$1 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (jni$_.Pointer<jni$_.Void>, jni$_.Pointer<jni$_.Void>)
                >,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void <init>(java.lang.String string, java.util.Locale locale)`
  /// The returned object must be released after use, by calling the [release] method.
  factory LocalePicker$LocaleInfo.new$1(
    jni$_.JString string,
    locale$_.Locale locale,
  ) {
    final _$string = string.reference;
    final _$locale = locale.reference;
    return LocalePicker$LocaleInfo.fromReference(
      _new$1(
        _class.reference.pointer,
        _id_new$1 as jni$_.JMethodIDPtr,
        _$string.pointer,
        _$locale.pointer,
      ).reference,
    );
  }

  static final _id_getLabel = _class.instanceMethodId(
    r'getLabel',
    r'()Ljava/lang/String;',
  );

  static final _getLabel =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public final java.lang.String getLabel()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JString getLabel() {
    return _getLabel(
      reference.pointer,
      _id_getLabel as jni$_.JMethodIDPtr,
    ).object<jni$_.JString>(const jni$_.$JString$Type$());
  }

  static final _id_getLocale = _class.instanceMethodId(
    r'getLocale',
    r'()Ljava/util/Locale;',
  );

  static final _getLocale =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public final java.util.Locale getLocale()`
  /// The returned object must be released after use, by calling the [release] method.
  locale$_.Locale getLocale() {
    return _getLocale(
      reference.pointer,
      _id_getLocale as jni$_.JMethodIDPtr,
    ).object<locale$_.Locale>(const locale$_.$Locale$Type$());
  }

  static final _id_toString$1 = _class.instanceMethodId(
    r'toString',
    r'()Ljava/lang/String;',
  );

  static final _toString$1 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public fun toString(): kotlin.String`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JString toString$1() {
    return _toString$1(
      reference.pointer,
      _id_toString$1 as jni$_.JMethodIDPtr,
    ).object<jni$_.JString>(const jni$_.$JString$Type$());
  }

  static final _id_compareTo = _class.instanceMethodId(
    r'compareTo',
    r'(Ldev/zeekr/invictus_android/internal/app/LocalePicker$LocaleInfo;)I',
  );

  static final _compareTo =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallIntMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public operator fun compareTo(other: dev.zeekr.invictus_android.internal.app.LocalePicker.LocaleInfo): kotlin.Int`
  int compareTo(LocalePicker$LocaleInfo localeInfo) {
    final _$localeInfo = localeInfo.reference;
    return _compareTo(
      reference.pointer,
      _id_compareTo as jni$_.JMethodIDPtr,
      _$localeInfo.pointer,
    ).integer;
  }

  bool operator <(LocalePicker$LocaleInfo localeInfo) {
    return compareTo(localeInfo) < 0;
  }

  bool operator <=(LocalePicker$LocaleInfo localeInfo) {
    return compareTo(localeInfo) <= 0;
  }

  bool operator >(LocalePicker$LocaleInfo localeInfo) {
    return compareTo(localeInfo) > 0;
  }

  bool operator >=(LocalePicker$LocaleInfo localeInfo) {
    return compareTo(localeInfo) >= 0;
  }
}

final class $LocalePicker$LocaleInfo$NullableType$
    extends jni$_.JType<LocalePicker$LocaleInfo?> {
  @jni$_.internal
  const $LocalePicker$LocaleInfo$NullableType$();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Ldev/zeekr/invictus_android/internal/app/LocalePicker$LocaleInfo;';

  @jni$_.internal
  @core$_.override
  LocalePicker$LocaleInfo? fromReference(jni$_.JReference reference) =>
      reference.isNull
      ? null
      : LocalePicker$LocaleInfo.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$NullableType$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<LocalePicker$LocaleInfo?> get nullableType => this;

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($LocalePicker$LocaleInfo$NullableType$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($LocalePicker$LocaleInfo$NullableType$) &&
        other is $LocalePicker$LocaleInfo$NullableType$;
  }
}

final class $LocalePicker$LocaleInfo$Type$
    extends jni$_.JType<LocalePicker$LocaleInfo> {
  @jni$_.internal
  const $LocalePicker$LocaleInfo$Type$();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Ldev/zeekr/invictus_android/internal/app/LocalePicker$LocaleInfo;';

  @jni$_.internal
  @core$_.override
  LocalePicker$LocaleInfo fromReference(jni$_.JReference reference) =>
      LocalePicker$LocaleInfo.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$NullableType$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<LocalePicker$LocaleInfo?> get nullableType =>
      const $LocalePicker$LocaleInfo$NullableType$();

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($LocalePicker$LocaleInfo$Type$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($LocalePicker$LocaleInfo$Type$) &&
        other is $LocalePicker$LocaleInfo$Type$;
  }
}

/// from: `dev.zeekr.invictus_android.internal.app.LocalePicker$LocaleSelectionListener$Companion`
class LocalePicker$LocaleSelectionListener$Companion extends jni$_.JObject {
  @jni$_.internal
  @core$_.override
  final jni$_.JType<LocalePicker$LocaleSelectionListener$Companion> $type;

  @jni$_.internal
  LocalePicker$LocaleSelectionListener$Companion.fromReference(
    jni$_.JReference reference,
  ) : $type = type,
      super.fromReference(reference);

  static final _class = jni$_.JClass.forName(
    r'dev/zeekr/invictus_android/internal/app/LocalePicker$LocaleSelectionListener$Companion',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<LocalePicker$LocaleSelectionListener$Companion?>
  nullableType =
      $LocalePicker$LocaleSelectionListener$Companion$NullableType$();

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<LocalePicker$LocaleSelectionListener$Companion>
  type = $LocalePicker$LocaleSelectionListener$Companion$Type$();
  static final _id_getClazz = _class.instanceMethodId(
    r'getClazz',
    r'()Ljava/lang/Class;',
  );

  static final _getClazz =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public final java.lang.Class<?> getClazz()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JObject getClazz() {
    return _getClazz(
      reference.pointer,
      _id_getClazz as jni$_.JMethodIDPtr,
    ).object<jni$_.JObject>(const jni$_.$JObject$Type$());
  }

  static final _id_new$ = _class.constructorId(
    r'(Lkotlin/jvm/internal/DefaultConstructorMarker;)V',
  );

  static final _new$ =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `synthetic public void <init>(kotlin.jvm.internal.DefaultConstructorMarker defaultConstructorMarker)`
  /// The returned object must be released after use, by calling the [release] method.
  factory LocalePicker$LocaleSelectionListener$Companion(
    jni$_.JObject? defaultConstructorMarker,
  ) {
    final _$defaultConstructorMarker =
        defaultConstructorMarker?.reference ?? jni$_.jNullReference;
    return LocalePicker$LocaleSelectionListener$Companion.fromReference(
      _new$(
        _class.reference.pointer,
        _id_new$ as jni$_.JMethodIDPtr,
        _$defaultConstructorMarker.pointer,
      ).reference,
    );
  }
}

final class $LocalePicker$LocaleSelectionListener$Companion$NullableType$
    extends jni$_.JType<LocalePicker$LocaleSelectionListener$Companion?> {
  @jni$_.internal
  const $LocalePicker$LocaleSelectionListener$Companion$NullableType$();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Ldev/zeekr/invictus_android/internal/app/LocalePicker$LocaleSelectionListener$Companion;';

  @jni$_.internal
  @core$_.override
  LocalePicker$LocaleSelectionListener$Companion? fromReference(
    jni$_.JReference reference,
  ) => reference.isNull
      ? null
      : LocalePicker$LocaleSelectionListener$Companion.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$Type$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<LocalePicker$LocaleSelectionListener$Companion?>
  get nullableType => this;

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode =>
      ($LocalePicker$LocaleSelectionListener$Companion$NullableType$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType ==
            ($LocalePicker$LocaleSelectionListener$Companion$NullableType$) &&
        other is $LocalePicker$LocaleSelectionListener$Companion$NullableType$;
  }
}

final class $LocalePicker$LocaleSelectionListener$Companion$Type$
    extends jni$_.JType<LocalePicker$LocaleSelectionListener$Companion> {
  @jni$_.internal
  const $LocalePicker$LocaleSelectionListener$Companion$Type$();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Ldev/zeekr/invictus_android/internal/app/LocalePicker$LocaleSelectionListener$Companion;';

  @jni$_.internal
  @core$_.override
  LocalePicker$LocaleSelectionListener$Companion fromReference(
    jni$_.JReference reference,
  ) => LocalePicker$LocaleSelectionListener$Companion.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$Type$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<LocalePicker$LocaleSelectionListener$Companion?>
  get nullableType =>
      const $LocalePicker$LocaleSelectionListener$Companion$NullableType$();

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode =>
      ($LocalePicker$LocaleSelectionListener$Companion$Type$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType ==
            ($LocalePicker$LocaleSelectionListener$Companion$Type$) &&
        other is $LocalePicker$LocaleSelectionListener$Companion$Type$;
  }
}

/// from: `dev.zeekr.invictus_android.internal.app.LocalePicker$LocaleSelectionListener`
class LocalePicker$LocaleSelectionListener extends jni$_.JObject {
  @jni$_.internal
  @core$_.override
  final jni$_.JType<LocalePicker$LocaleSelectionListener> $type;

  @jni$_.internal
  LocalePicker$LocaleSelectionListener.fromReference(jni$_.JReference reference)
    : $type = type,
      super.fromReference(reference);

  static final _class = jni$_.JClass.forName(
    r'dev/zeekr/invictus_android/internal/app/LocalePicker$LocaleSelectionListener',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<LocalePicker$LocaleSelectionListener?> nullableType =
      $LocalePicker$LocaleSelectionListener$NullableType$();

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<LocalePicker$LocaleSelectionListener> type =
      $LocalePicker$LocaleSelectionListener$Type$();
  static final _id_Companion = _class.staticFieldId(
    r'Companion',
    r'Ldev/zeekr/invictus_android/internal/app/LocalePicker$LocaleSelectionListener$Companion;',
  );

  /// from: `static public final dev.zeekr.invictus_android.internal.app.LocalePicker$LocaleSelectionListener$Companion Companion`
  /// The returned object must be released after use, by calling the [release] method.
  static LocalePicker$LocaleSelectionListener$Companion get Companion =>
      _id_Companion.get(
        _class,
        const $LocalePicker$LocaleSelectionListener$Companion$Type$(),
      );

  static final _id_getObj = _class.instanceMethodId(
    r'getObj',
    r'()Ljava/lang/Object;',
  );

  static final _getObj =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public final java.lang.Object getObj()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JObject getObj() {
    return _getObj(
      reference.pointer,
      _id_getObj as jni$_.JMethodIDPtr,
    ).object<jni$_.JObject>(const jni$_.$JObject$Type$());
  }

  static final _id_onLocaleSelected = _class.instanceMethodId(
    r'onLocaleSelected',
    r'(Ljava/util/Locale;)V',
  );

  static final _onLocaleSelected =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public fun onLocaleSelected(locale: java.util.Locale): kotlin.Unit`
  void onLocaleSelected(locale$_.Locale locale) {
    final _$locale = locale.reference;
    _onLocaleSelected(
      reference.pointer,
      _id_onLocaleSelected as jni$_.JMethodIDPtr,
      _$locale.pointer,
    ).check();
  }
}

final class $LocalePicker$LocaleSelectionListener$NullableType$
    extends jni$_.JType<LocalePicker$LocaleSelectionListener?> {
  @jni$_.internal
  const $LocalePicker$LocaleSelectionListener$NullableType$();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Ldev/zeekr/invictus_android/internal/app/LocalePicker$LocaleSelectionListener;';

  @jni$_.internal
  @core$_.override
  LocalePicker$LocaleSelectionListener? fromReference(
    jni$_.JReference reference,
  ) => reference.isNull
      ? null
      : LocalePicker$LocaleSelectionListener.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$Type$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<LocalePicker$LocaleSelectionListener?> get nullableType => this;

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode =>
      ($LocalePicker$LocaleSelectionListener$NullableType$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType ==
            ($LocalePicker$LocaleSelectionListener$NullableType$) &&
        other is $LocalePicker$LocaleSelectionListener$NullableType$;
  }
}

final class $LocalePicker$LocaleSelectionListener$Type$
    extends jni$_.JType<LocalePicker$LocaleSelectionListener> {
  @jni$_.internal
  const $LocalePicker$LocaleSelectionListener$Type$();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Ldev/zeekr/invictus_android/internal/app/LocalePicker$LocaleSelectionListener;';

  @jni$_.internal
  @core$_.override
  LocalePicker$LocaleSelectionListener fromReference(
    jni$_.JReference reference,
  ) => LocalePicker$LocaleSelectionListener.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$Type$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<LocalePicker$LocaleSelectionListener?> get nullableType =>
      const $LocalePicker$LocaleSelectionListener$NullableType$();

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($LocalePicker$LocaleSelectionListener$Type$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($LocalePicker$LocaleSelectionListener$Type$) &&
        other is $LocalePicker$LocaleSelectionListener$Type$;
  }
}

/// from: `dev.zeekr.invictus_android.internal.app.LocalePicker`
class LocalePicker extends jni$_.JObject {
  @jni$_.internal
  @core$_.override
  final jni$_.JType<LocalePicker> $type;

  @jni$_.internal
  LocalePicker.fromReference(jni$_.JReference reference)
    : $type = type,
      super.fromReference(reference);

  static final _class = jni$_.JClass.forName(
    r'dev/zeekr/invictus_android/internal/app/LocalePicker',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<LocalePicker?> nullableType =
      $LocalePicker$NullableType$();

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<LocalePicker> type = $LocalePicker$Type$();
  static final _id_Companion = _class.staticFieldId(
    r'Companion',
    r'Ldev/zeekr/invictus_android/internal/app/LocalePicker$Companion;',
  );

  /// from: `static public final dev.zeekr.invictus_android.internal.app.LocalePicker$Companion Companion`
  /// The returned object must be released after use, by calling the [release] method.
  static LocalePicker$Companion get Companion =>
      _id_Companion.get(_class, const $LocalePicker$Companion$Type$());

  static final _id_new$ = _class.constructorId(r'()V');

  static final _new$ =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public void <init>()`
  /// The returned object must be released after use, by calling the [release] method.
  factory LocalePicker() {
    return LocalePicker.fromReference(
      _new$(_class.reference.pointer, _id_new$ as jni$_.JMethodIDPtr).reference,
    );
  }
}

final class $LocalePicker$NullableType$ extends jni$_.JType<LocalePicker?> {
  @jni$_.internal
  const $LocalePicker$NullableType$();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Ldev/zeekr/invictus_android/internal/app/LocalePicker;';

  @jni$_.internal
  @core$_.override
  LocalePicker? fromReference(jni$_.JReference reference) =>
      reference.isNull ? null : LocalePicker.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$Type$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<LocalePicker?> get nullableType => this;

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($LocalePicker$NullableType$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($LocalePicker$NullableType$) &&
        other is $LocalePicker$NullableType$;
  }
}

final class $LocalePicker$Type$ extends jni$_.JType<LocalePicker> {
  @jni$_.internal
  const $LocalePicker$Type$();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Ldev/zeekr/invictus_android/internal/app/LocalePicker;';

  @jni$_.internal
  @core$_.override
  LocalePicker fromReference(jni$_.JReference reference) =>
      LocalePicker.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$Type$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<LocalePicker?> get nullableType =>
      const $LocalePicker$NullableType$();

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($LocalePicker$Type$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($LocalePicker$Type$) &&
        other is $LocalePicker$Type$;
  }
}
