// AUTO GENERATED BY JNIGEN 0.15.0. DO NOT EDIT!

// ignore_for_file: annotate_overrides
// ignore_for_file: argument_type_not_assignable
// ignore_for_file: camel_case_extensions
// ignore_for_file: camel_case_types
// ignore_for_file: constant_identifier_names
// ignore_for_file: comment_references
// ignore_for_file: doc_directive_unknown
// ignore_for_file: file_names
// ignore_for_file: inference_failure_on_untyped_parameter
// ignore_for_file: invalid_internal_annotation
// ignore_for_file: invalid_use_of_internal_member
// ignore_for_file: library_prefixes
// ignore_for_file: lines_longer_than_80_chars
// ignore_for_file: no_leading_underscores_for_library_prefixes
// ignore_for_file: no_leading_underscores_for_local_identifiers
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: only_throw_errors
// ignore_for_file: overridden_fields
// ignore_for_file: prefer_double_quotes
// ignore_for_file: unintended_html_in_doc_comment
// ignore_for_file: unnecessary_cast
// ignore_for_file: unnecessary_non_null_assertion
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: unused_element
// ignore_for_file: unused_field
// ignore_for_file: unused_import
// ignore_for_file: unused_local_variable
// ignore_for_file: unused_shown_name
// ignore_for_file: use_super_parameters

import 'dart:core' as core$_;
import 'dart:core' show Object, String, bool, double, int;

import 'package:jni/_internal.dart' as jni$_;
import 'package:jni/jni.dart' as jni$_;

/// from: `android.net.NetworkInfo$DetailedState`
class NetworkInfo$DetailedState extends jni$_.JObject {
  @jni$_.internal
  @core$_.override
  final jni$_.JType<NetworkInfo$DetailedState> $type;

  @jni$_.internal
  NetworkInfo$DetailedState.fromReference(jni$_.JReference reference)
    : $type = type,
      super.fromReference(reference);

  static final _class = jni$_.JClass.forName(
    r'android/net/NetworkInfo$DetailedState',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<NetworkInfo$DetailedState?> nullableType =
      $NetworkInfo$DetailedState$NullableType$();

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<NetworkInfo$DetailedState> type =
      $NetworkInfo$DetailedState$Type$();
  static final _id_AUTHENTICATING = _class.staticFieldId(
    r'AUTHENTICATING',
    r'Landroid/net/NetworkInfo$DetailedState;',
  );

  /// from: `static public final android.net.NetworkInfo$DetailedState AUTHENTICATING`
  /// The returned object must be released after use, by calling the [release] method.
  static NetworkInfo$DetailedState get AUTHENTICATING =>
      _id_AUTHENTICATING.get(_class, const $NetworkInfo$DetailedState$Type$());

  static final _id_BLOCKED = _class.staticFieldId(
    r'BLOCKED',
    r'Landroid/net/NetworkInfo$DetailedState;',
  );

  /// from: `static public final android.net.NetworkInfo$DetailedState BLOCKED`
  /// The returned object must be released after use, by calling the [release] method.
  static NetworkInfo$DetailedState get BLOCKED =>
      _id_BLOCKED.get(_class, const $NetworkInfo$DetailedState$Type$());

  static final _id_CAPTIVE_PORTAL_CHECK = _class.staticFieldId(
    r'CAPTIVE_PORTAL_CHECK',
    r'Landroid/net/NetworkInfo$DetailedState;',
  );

  /// from: `static public final android.net.NetworkInfo$DetailedState CAPTIVE_PORTAL_CHECK`
  /// The returned object must be released after use, by calling the [release] method.
  static NetworkInfo$DetailedState get CAPTIVE_PORTAL_CHECK =>
      _id_CAPTIVE_PORTAL_CHECK.get(
        _class,
        const $NetworkInfo$DetailedState$Type$(),
      );

  static final _id_CONNECTED = _class.staticFieldId(
    r'CONNECTED',
    r'Landroid/net/NetworkInfo$DetailedState;',
  );

  /// from: `static public final android.net.NetworkInfo$DetailedState CONNECTED`
  /// The returned object must be released after use, by calling the [release] method.
  static NetworkInfo$DetailedState get CONNECTED =>
      _id_CONNECTED.get(_class, const $NetworkInfo$DetailedState$Type$());

  static final _id_CONNECTING = _class.staticFieldId(
    r'CONNECTING',
    r'Landroid/net/NetworkInfo$DetailedState;',
  );

  /// from: `static public final android.net.NetworkInfo$DetailedState CONNECTING`
  /// The returned object must be released after use, by calling the [release] method.
  static NetworkInfo$DetailedState get CONNECTING =>
      _id_CONNECTING.get(_class, const $NetworkInfo$DetailedState$Type$());

  static final _id_DISCONNECTED = _class.staticFieldId(
    r'DISCONNECTED',
    r'Landroid/net/NetworkInfo$DetailedState;',
  );

  /// from: `static public final android.net.NetworkInfo$DetailedState DISCONNECTED`
  /// The returned object must be released after use, by calling the [release] method.
  static NetworkInfo$DetailedState get DISCONNECTED =>
      _id_DISCONNECTED.get(_class, const $NetworkInfo$DetailedState$Type$());

  static final _id_DISCONNECTING = _class.staticFieldId(
    r'DISCONNECTING',
    r'Landroid/net/NetworkInfo$DetailedState;',
  );

  /// from: `static public final android.net.NetworkInfo$DetailedState DISCONNECTING`
  /// The returned object must be released after use, by calling the [release] method.
  static NetworkInfo$DetailedState get DISCONNECTING =>
      _id_DISCONNECTING.get(_class, const $NetworkInfo$DetailedState$Type$());

  static final _id_FAILED = _class.staticFieldId(
    r'FAILED',
    r'Landroid/net/NetworkInfo$DetailedState;',
  );

  /// from: `static public final android.net.NetworkInfo$DetailedState FAILED`
  /// The returned object must be released after use, by calling the [release] method.
  static NetworkInfo$DetailedState get FAILED =>
      _id_FAILED.get(_class, const $NetworkInfo$DetailedState$Type$());

  static final _id_IDLE = _class.staticFieldId(
    r'IDLE',
    r'Landroid/net/NetworkInfo$DetailedState;',
  );

  /// from: `static public final android.net.NetworkInfo$DetailedState IDLE`
  /// The returned object must be released after use, by calling the [release] method.
  static NetworkInfo$DetailedState get IDLE =>
      _id_IDLE.get(_class, const $NetworkInfo$DetailedState$Type$());

  static final _id_OBTAINING_IPADDR = _class.staticFieldId(
    r'OBTAINING_IPADDR',
    r'Landroid/net/NetworkInfo$DetailedState;',
  );

  /// from: `static public final android.net.NetworkInfo$DetailedState OBTAINING_IPADDR`
  /// The returned object must be released after use, by calling the [release] method.
  static NetworkInfo$DetailedState get OBTAINING_IPADDR => _id_OBTAINING_IPADDR
      .get(_class, const $NetworkInfo$DetailedState$Type$());

  static final _id_SCANNING = _class.staticFieldId(
    r'SCANNING',
    r'Landroid/net/NetworkInfo$DetailedState;',
  );

  /// from: `static public final android.net.NetworkInfo$DetailedState SCANNING`
  /// The returned object must be released after use, by calling the [release] method.
  static NetworkInfo$DetailedState get SCANNING =>
      _id_SCANNING.get(_class, const $NetworkInfo$DetailedState$Type$());

  static final _id_SUSPENDED = _class.staticFieldId(
    r'SUSPENDED',
    r'Landroid/net/NetworkInfo$DetailedState;',
  );

  /// from: `static public final android.net.NetworkInfo$DetailedState SUSPENDED`
  /// The returned object must be released after use, by calling the [release] method.
  static NetworkInfo$DetailedState get SUSPENDED =>
      _id_SUSPENDED.get(_class, const $NetworkInfo$DetailedState$Type$());

  static final _id_VERIFYING_POOR_LINK = _class.staticFieldId(
    r'VERIFYING_POOR_LINK',
    r'Landroid/net/NetworkInfo$DetailedState;',
  );

  /// from: `static public final android.net.NetworkInfo$DetailedState VERIFYING_POOR_LINK`
  /// The returned object must be released after use, by calling the [release] method.
  static NetworkInfo$DetailedState get VERIFYING_POOR_LINK =>
      _id_VERIFYING_POOR_LINK.get(
        _class,
        const $NetworkInfo$DetailedState$Type$(),
      );

  static final _id_values = _class.staticMethodId(
    r'values',
    r'()[Landroid/net/NetworkInfo$DetailedState;',
  );

  static final _values =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallStaticObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `static public android.net.NetworkInfo$DetailedState[] values()`
  /// The returned object must be released after use, by calling the [release] method.
  static jni$_.JArray<NetworkInfo$DetailedState?>? values() {
    return _values(
      _class.reference.pointer,
      _id_values as jni$_.JMethodIDPtr,
    ).object<jni$_.JArray<NetworkInfo$DetailedState?>?>(
      const jni$_.$JArray$NullableType$<NetworkInfo$DetailedState?>(
        $NetworkInfo$DetailedState$NullableType$(),
      ),
    );
  }

  static final _id_valueOf = _class.staticMethodId(
    r'valueOf',
    r'(Ljava/lang/String;)Landroid/net/NetworkInfo$DetailedState;',
  );

  static final _valueOf =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallStaticObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `static public android.net.NetworkInfo$DetailedState valueOf(java.lang.String synthetic)`
  /// The returned object must be released after use, by calling the [release] method.
  static NetworkInfo$DetailedState? valueOf(jni$_.JString? synthetic) {
    final _$synthetic = synthetic?.reference ?? jni$_.jNullReference;
    return _valueOf(
      _class.reference.pointer,
      _id_valueOf as jni$_.JMethodIDPtr,
      _$synthetic.pointer,
    ).object<NetworkInfo$DetailedState?>(
      const $NetworkInfo$DetailedState$NullableType$(),
    );
  }
}

final class $NetworkInfo$DetailedState$NullableType$
    extends jni$_.JType<NetworkInfo$DetailedState?> {
  @jni$_.internal
  const $NetworkInfo$DetailedState$NullableType$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Landroid/net/NetworkInfo$DetailedState;';

  @jni$_.internal
  @core$_.override
  NetworkInfo$DetailedState? fromReference(jni$_.JReference reference) =>
      reference.isNull
      ? null
      : NetworkInfo$DetailedState.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$NullableType$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<NetworkInfo$DetailedState?> get nullableType => this;

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($NetworkInfo$DetailedState$NullableType$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($NetworkInfo$DetailedState$NullableType$) &&
        other is $NetworkInfo$DetailedState$NullableType$;
  }
}

final class $NetworkInfo$DetailedState$Type$
    extends jni$_.JType<NetworkInfo$DetailedState> {
  @jni$_.internal
  const $NetworkInfo$DetailedState$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Landroid/net/NetworkInfo$DetailedState;';

  @jni$_.internal
  @core$_.override
  NetworkInfo$DetailedState fromReference(jni$_.JReference reference) =>
      NetworkInfo$DetailedState.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$NullableType$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<NetworkInfo$DetailedState?> get nullableType =>
      const $NetworkInfo$DetailedState$NullableType$();

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($NetworkInfo$DetailedState$Type$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($NetworkInfo$DetailedState$Type$) &&
        other is $NetworkInfo$DetailedState$Type$;
  }
}

/// from: `android.net.NetworkInfo$State`
class NetworkInfo$State extends jni$_.JObject {
  @jni$_.internal
  @core$_.override
  final jni$_.JType<NetworkInfo$State> $type;

  @jni$_.internal
  NetworkInfo$State.fromReference(jni$_.JReference reference)
    : $type = type,
      super.fromReference(reference);

  static final _class = jni$_.JClass.forName(r'android/net/NetworkInfo$State');

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<NetworkInfo$State?> nullableType =
      $NetworkInfo$State$NullableType$();

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<NetworkInfo$State> type = $NetworkInfo$State$Type$();
  static final _id_CONNECTED = _class.staticFieldId(
    r'CONNECTED',
    r'Landroid/net/NetworkInfo$State;',
  );

  /// from: `static public final android.net.NetworkInfo$State CONNECTED`
  /// The returned object must be released after use, by calling the [release] method.
  static NetworkInfo$State get CONNECTED =>
      _id_CONNECTED.get(_class, const $NetworkInfo$State$Type$());

  static final _id_CONNECTING = _class.staticFieldId(
    r'CONNECTING',
    r'Landroid/net/NetworkInfo$State;',
  );

  /// from: `static public final android.net.NetworkInfo$State CONNECTING`
  /// The returned object must be released after use, by calling the [release] method.
  static NetworkInfo$State get CONNECTING =>
      _id_CONNECTING.get(_class, const $NetworkInfo$State$Type$());

  static final _id_DISCONNECTED = _class.staticFieldId(
    r'DISCONNECTED',
    r'Landroid/net/NetworkInfo$State;',
  );

  /// from: `static public final android.net.NetworkInfo$State DISCONNECTED`
  /// The returned object must be released after use, by calling the [release] method.
  static NetworkInfo$State get DISCONNECTED =>
      _id_DISCONNECTED.get(_class, const $NetworkInfo$State$Type$());

  static final _id_DISCONNECTING = _class.staticFieldId(
    r'DISCONNECTING',
    r'Landroid/net/NetworkInfo$State;',
  );

  /// from: `static public final android.net.NetworkInfo$State DISCONNECTING`
  /// The returned object must be released after use, by calling the [release] method.
  static NetworkInfo$State get DISCONNECTING =>
      _id_DISCONNECTING.get(_class, const $NetworkInfo$State$Type$());

  static final _id_SUSPENDED = _class.staticFieldId(
    r'SUSPENDED',
    r'Landroid/net/NetworkInfo$State;',
  );

  /// from: `static public final android.net.NetworkInfo$State SUSPENDED`
  /// The returned object must be released after use, by calling the [release] method.
  static NetworkInfo$State get SUSPENDED =>
      _id_SUSPENDED.get(_class, const $NetworkInfo$State$Type$());

  static final _id_UNKNOWN = _class.staticFieldId(
    r'UNKNOWN',
    r'Landroid/net/NetworkInfo$State;',
  );

  /// from: `static public final android.net.NetworkInfo$State UNKNOWN`
  /// The returned object must be released after use, by calling the [release] method.
  static NetworkInfo$State get UNKNOWN =>
      _id_UNKNOWN.get(_class, const $NetworkInfo$State$Type$());

  static final _id_values = _class.staticMethodId(
    r'values',
    r'()[Landroid/net/NetworkInfo$State;',
  );

  static final _values =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallStaticObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `static public android.net.NetworkInfo$State[] values()`
  /// The returned object must be released after use, by calling the [release] method.
  static jni$_.JArray<NetworkInfo$State?>? values() {
    return _values(
      _class.reference.pointer,
      _id_values as jni$_.JMethodIDPtr,
    ).object<jni$_.JArray<NetworkInfo$State?>?>(
      const jni$_.$JArray$NullableType$<NetworkInfo$State?>(
        $NetworkInfo$State$NullableType$(),
      ),
    );
  }

  static final _id_valueOf = _class.staticMethodId(
    r'valueOf',
    r'(Ljava/lang/String;)Landroid/net/NetworkInfo$State;',
  );

  static final _valueOf =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallStaticObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `static public android.net.NetworkInfo$State valueOf(java.lang.String synthetic)`
  /// The returned object must be released after use, by calling the [release] method.
  static NetworkInfo$State? valueOf(jni$_.JString? synthetic) {
    final _$synthetic = synthetic?.reference ?? jni$_.jNullReference;
    return _valueOf(
      _class.reference.pointer,
      _id_valueOf as jni$_.JMethodIDPtr,
      _$synthetic.pointer,
    ).object<NetworkInfo$State?>(const $NetworkInfo$State$NullableType$());
  }
}

final class $NetworkInfo$State$NullableType$
    extends jni$_.JType<NetworkInfo$State?> {
  @jni$_.internal
  const $NetworkInfo$State$NullableType$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Landroid/net/NetworkInfo$State;';

  @jni$_.internal
  @core$_.override
  NetworkInfo$State? fromReference(jni$_.JReference reference) =>
      reference.isNull ? null : NetworkInfo$State.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$NullableType$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<NetworkInfo$State?> get nullableType => this;

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($NetworkInfo$State$NullableType$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($NetworkInfo$State$NullableType$) &&
        other is $NetworkInfo$State$NullableType$;
  }
}

final class $NetworkInfo$State$Type$ extends jni$_.JType<NetworkInfo$State> {
  @jni$_.internal
  const $NetworkInfo$State$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Landroid/net/NetworkInfo$State;';

  @jni$_.internal
  @core$_.override
  NetworkInfo$State fromReference(jni$_.JReference reference) =>
      NetworkInfo$State.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$NullableType$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<NetworkInfo$State?> get nullableType =>
      const $NetworkInfo$State$NullableType$();

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($NetworkInfo$State$Type$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($NetworkInfo$State$Type$) &&
        other is $NetworkInfo$State$Type$;
  }
}

/// from: `android.net.NetworkInfo`
class NetworkInfo extends jni$_.JObject {
  @jni$_.internal
  @core$_.override
  final jni$_.JType<NetworkInfo> $type;

  @jni$_.internal
  NetworkInfo.fromReference(jni$_.JReference reference)
    : $type = type,
      super.fromReference(reference);

  static final _class = jni$_.JClass.forName(r'android/net/NetworkInfo');

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<NetworkInfo?> nullableType =
      $NetworkInfo$NullableType$();

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<NetworkInfo> type = $NetworkInfo$Type$();
  static final _id_CREATOR = _class.staticFieldId(
    r'CREATOR',
    r'Landroid/os/Parcelable$Creator;',
  );

  /// from: `static public final android.os.Parcelable$Creator<android.net.NetworkInfo> CREATOR`
  /// The returned object must be released after use, by calling the [release] method.
  static jni$_.JObject get CREATOR =>
      _id_CREATOR.get(_class, const jni$_.$JObject$Type$());

  static final _id_new$ = _class.constructorId(
    r'(IILjava/lang/String;Ljava/lang/String;)V',
  );

  static final _new$ =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                  )
                >,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              int,
              int,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void <init>(int i, int i1, java.lang.String string, java.lang.String string1)`
  /// The returned object must be released after use, by calling the [release] method.
  factory NetworkInfo(
    int i,
    int i1,
    jni$_.JString? string,
    jni$_.JString? string1,
  ) {
    final _$string = string?.reference ?? jni$_.jNullReference;
    final _$string1 = string1?.reference ?? jni$_.jNullReference;
    return NetworkInfo.fromReference(
      _new$(
        _class.reference.pointer,
        _id_new$ as jni$_.JMethodIDPtr,
        i,
        i1,
        _$string.pointer,
        _$string1.pointer,
      ).reference,
    );
  }

  static final _id_describeContents = _class.instanceMethodId(
    r'describeContents',
    r'()I',
  );

  static final _describeContents =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallIntMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public int describeContents()`
  int describeContents() {
    return _describeContents(
      reference.pointer,
      _id_describeContents as jni$_.JMethodIDPtr,
    ).integer;
  }

  static final _id_getDetailedState = _class.instanceMethodId(
    r'getDetailedState',
    r'()Landroid/net/NetworkInfo$DetailedState;',
  );

  static final _getDetailedState =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public android.net.NetworkInfo$DetailedState getDetailedState()`
  /// The returned object must be released after use, by calling the [release] method.
  NetworkInfo$DetailedState getDetailedState() {
    return _getDetailedState(
      reference.pointer,
      _id_getDetailedState as jni$_.JMethodIDPtr,
    ).object<NetworkInfo$DetailedState>(
      const $NetworkInfo$DetailedState$Type$(),
    );
  }

  static final _id_getExtraInfo = _class.instanceMethodId(
    r'getExtraInfo',
    r'()Ljava/lang/String;',
  );

  static final _getExtraInfo =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public java.lang.String getExtraInfo()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JString? getExtraInfo() {
    return _getExtraInfo(
      reference.pointer,
      _id_getExtraInfo as jni$_.JMethodIDPtr,
    ).object<jni$_.JString?>(const jni$_.$JString$NullableType$());
  }

  static final _id_getReason = _class.instanceMethodId(
    r'getReason',
    r'()Ljava/lang/String;',
  );

  static final _getReason =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public java.lang.String getReason()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JString? getReason() {
    return _getReason(
      reference.pointer,
      _id_getReason as jni$_.JMethodIDPtr,
    ).object<jni$_.JString?>(const jni$_.$JString$NullableType$());
  }

  static final _id_getState = _class.instanceMethodId(
    r'getState',
    r'()Landroid/net/NetworkInfo$State;',
  );

  static final _getState =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public android.net.NetworkInfo$State getState()`
  /// The returned object must be released after use, by calling the [release] method.
  NetworkInfo$State? getState() {
    return _getState(
      reference.pointer,
      _id_getState as jni$_.JMethodIDPtr,
    ).object<NetworkInfo$State?>(const $NetworkInfo$State$NullableType$());
  }

  static final _id_getSubtype = _class.instanceMethodId(r'getSubtype', r'()I');

  static final _getSubtype =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallIntMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public int getSubtype()`
  int getSubtype() {
    return _getSubtype(
      reference.pointer,
      _id_getSubtype as jni$_.JMethodIDPtr,
    ).integer;
  }

  static final _id_getSubtypeName = _class.instanceMethodId(
    r'getSubtypeName',
    r'()Ljava/lang/String;',
  );

  static final _getSubtypeName =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public java.lang.String getSubtypeName()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JString? getSubtypeName() {
    return _getSubtypeName(
      reference.pointer,
      _id_getSubtypeName as jni$_.JMethodIDPtr,
    ).object<jni$_.JString?>(const jni$_.$JString$NullableType$());
  }

  static final _id_getType = _class.instanceMethodId(r'getType', r'()I');

  static final _getType =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallIntMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public int getType()`
  int getType() {
    return _getType(
      reference.pointer,
      _id_getType as jni$_.JMethodIDPtr,
    ).integer;
  }

  static final _id_getTypeName = _class.instanceMethodId(
    r'getTypeName',
    r'()Ljava/lang/String;',
  );

  static final _getTypeName =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public java.lang.String getTypeName()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JString? getTypeName() {
    return _getTypeName(
      reference.pointer,
      _id_getTypeName as jni$_.JMethodIDPtr,
    ).object<jni$_.JString?>(const jni$_.$JString$NullableType$());
  }

  static final _id_isAvailable = _class.instanceMethodId(
    r'isAvailable',
    r'()Z',
  );

  static final _isAvailable =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallBooleanMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public boolean isAvailable()`
  bool isAvailable() {
    return _isAvailable(
      reference.pointer,
      _id_isAvailable as jni$_.JMethodIDPtr,
    ).boolean;
  }

  static final _id_isConnected = _class.instanceMethodId(
    r'isConnected',
    r'()Z',
  );

  static final _isConnected =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallBooleanMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public boolean isConnected()`
  bool isConnected() {
    return _isConnected(
      reference.pointer,
      _id_isConnected as jni$_.JMethodIDPtr,
    ).boolean;
  }

  static final _id_isConnectedOrConnecting = _class.instanceMethodId(
    r'isConnectedOrConnecting',
    r'()Z',
  );

  static final _isConnectedOrConnecting =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallBooleanMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public boolean isConnectedOrConnecting()`
  bool isConnectedOrConnecting() {
    return _isConnectedOrConnecting(
      reference.pointer,
      _id_isConnectedOrConnecting as jni$_.JMethodIDPtr,
    ).boolean;
  }

  static final _id_isFailover = _class.instanceMethodId(r'isFailover', r'()Z');

  static final _isFailover =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallBooleanMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public boolean isFailover()`
  bool isFailover() {
    return _isFailover(
      reference.pointer,
      _id_isFailover as jni$_.JMethodIDPtr,
    ).boolean;
  }

  static final _id_isRoaming = _class.instanceMethodId(r'isRoaming', r'()Z');

  static final _isRoaming =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallBooleanMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public boolean isRoaming()`
  bool isRoaming() {
    return _isRoaming(
      reference.pointer,
      _id_isRoaming as jni$_.JMethodIDPtr,
    ).boolean;
  }

  static final _id_setDetailedState = _class.instanceMethodId(
    r'setDetailedState',
    r'(Landroid/net/NetworkInfo$DetailedState;Ljava/lang/String;Ljava/lang/String;)V',
  );

  static final _setDetailedState =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                  )
                >,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void setDetailedState(android.net.NetworkInfo$DetailedState detailedState, java.lang.String string, java.lang.String string1)`
  void setDetailedState(
    NetworkInfo$DetailedState detailedState,
    jni$_.JString? string,
    jni$_.JString? string1,
  ) {
    final _$detailedState = detailedState.reference;
    final _$string = string?.reference ?? jni$_.jNullReference;
    final _$string1 = string1?.reference ?? jni$_.jNullReference;
    _setDetailedState(
      reference.pointer,
      _id_setDetailedState as jni$_.JMethodIDPtr,
      _$detailedState.pointer,
      _$string.pointer,
      _$string1.pointer,
    ).check();
  }

  static final _id_toString$1 = _class.instanceMethodId(
    r'toString',
    r'()Ljava/lang/String;',
  );

  static final _toString$1 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public java.lang.String toString()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JString? toString$1() {
    return _toString$1(
      reference.pointer,
      _id_toString$1 as jni$_.JMethodIDPtr,
    ).object<jni$_.JString?>(const jni$_.$JString$NullableType$());
  }

  static final _id_writeToParcel = _class.instanceMethodId(
    r'writeToParcel',
    r'(Landroid/os/Parcel;I)V',
  );

  static final _writeToParcel =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>, jni$_.Int32)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              int,
            )
          >();

  /// from: `public void writeToParcel(android.os.Parcel parcel, int i)`
  void writeToParcel(jni$_.JObject? parcel, int i) {
    final _$parcel = parcel?.reference ?? jni$_.jNullReference;
    _writeToParcel(
      reference.pointer,
      _id_writeToParcel as jni$_.JMethodIDPtr,
      _$parcel.pointer,
      i,
    ).check();
  }
}

final class $NetworkInfo$NullableType$ extends jni$_.JType<NetworkInfo?> {
  @jni$_.internal
  const $NetworkInfo$NullableType$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Landroid/net/NetworkInfo;';

  @jni$_.internal
  @core$_.override
  NetworkInfo? fromReference(jni$_.JReference reference) =>
      reference.isNull ? null : NetworkInfo.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$NullableType$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<NetworkInfo?> get nullableType => this;

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($NetworkInfo$NullableType$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($NetworkInfo$NullableType$) &&
        other is $NetworkInfo$NullableType$;
  }
}

final class $NetworkInfo$Type$ extends jni$_.JType<NetworkInfo> {
  @jni$_.internal
  const $NetworkInfo$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Landroid/net/NetworkInfo;';

  @jni$_.internal
  @core$_.override
  NetworkInfo fromReference(jni$_.JReference reference) =>
      NetworkInfo.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$NullableType$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<NetworkInfo?> get nullableType =>
      const $NetworkInfo$NullableType$();

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($NetworkInfo$Type$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($NetworkInfo$Type$) &&
        other is $NetworkInfo$Type$;
  }
}
