// AUTO GENERATED BY JNIGEN 0.16.0. DO NOT EDIT!

// ignore_for_file: annotate_overrides
// ignore_for_file: argument_type_not_assignable
// ignore_for_file: camel_case_extensions
// ignore_for_file: camel_case_types
// ignore_for_file: constant_identifier_names
// ignore_for_file: comment_references
// ignore_for_file: doc_directive_unknown
// ignore_for_file: file_names
// ignore_for_file: inference_failure_on_untyped_parameter
// ignore_for_file: invalid_internal_annotation
// ignore_for_file: invalid_use_of_internal_member
// ignore_for_file: library_prefixes
// ignore_for_file: lines_longer_than_80_chars
// ignore_for_file: no_leading_underscores_for_library_prefixes
// ignore_for_file: no_leading_underscores_for_local_identifiers
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: only_throw_errors
// ignore_for_file: overridden_fields
// ignore_for_file: prefer_double_quotes
// ignore_for_file: unintended_html_in_doc_comment
// ignore_for_file: unnecessary_cast
// ignore_for_file: unnecessary_non_null_assertion
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: unused_element
// ignore_for_file: unused_field
// ignore_for_file: unused_import
// ignore_for_file: unused_local_variable
// ignore_for_file: unused_shown_name
// ignore_for_file: use_super_parameters

import 'dart:core' as core$_;
import 'dart:core' show Object, String;

import 'package:jni/_internal.dart' as jni$_;
import 'package:jni/jni.dart' as jni$_;

import '../io/Closeable.dart' as closeable$_;

import 'InetAddress.dart' as inetaddress$_;

/// from: `java.net.DatagramSocket`
extension type DatagramSocket._(jni$_.JObject _$this)
    implements jni$_.JObject, closeable$_.Closeable {
  static final _class = jni$_.JClass.forName(r'java/net/DatagramSocket');

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<DatagramSocket> type = $DatagramSocket$Type$();
  static final _id_new$ = _class.constructorId(r'()V');

  static final _new$ =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public void <init>()`
  /// The returned object must be released after use, by calling the [release] method.
  factory DatagramSocket() {
    return _new$(
      _class.reference.pointer,
      _id_new$.pointer,
    ).object<DatagramSocket>();
  }

  static final _id_new$1 = _class.constructorId(r'(I)V');

  static final _new$1 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Int32,)>,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              core$_.int,
            )
          >();

  /// from: `public void <init>(int i)`
  /// The returned object must be released after use, by calling the [release] method.
  factory DatagramSocket.new$1(core$_.int i) {
    return _new$1(
      _class.reference.pointer,
      _id_new$1.pointer,
      i,
    ).object<DatagramSocket>();
  }

  static final _id_new$2 = _class.constructorId(r'(ILjava/net/InetAddress;)V');

  static final _new$2 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Int32, jni$_.Pointer<jni$_.Void>)>,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              core$_.int,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void <init>(int i, java.net.InetAddress inetAddress)`
  /// The returned object must be released after use, by calling the [release] method.
  factory DatagramSocket.new$2(
    core$_.int i,
    inetaddress$_.InetAddress? inetAddress,
  ) {
    final _$inetAddress = inetAddress?.reference ?? jni$_.jNullReference;
    return _new$2(
      _class.reference.pointer,
      _id_new$2.pointer,
      i,
      _$inetAddress.pointer,
    ).object<DatagramSocket>();
  }

  static final _id_new$3 = _class.constructorId(r'(Ljava/net/SocketAddress;)V');

  static final _new$3 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void <init>(java.net.SocketAddress socketAddress)`
  /// The returned object must be released after use, by calling the [release] method.
  factory DatagramSocket.new$3(jni$_.JObject? socketAddress) {
    final _$socketAddress = socketAddress?.reference ?? jni$_.jNullReference;
    return _new$3(
      _class.reference.pointer,
      _id_new$3.pointer,
      _$socketAddress.pointer,
    ).object<DatagramSocket>();
  }

  static final _id_set$datagramSocketImplFactory = _class.staticMethodId(
    r'setDatagramSocketImplFactory',
    r'(Ljava/net/DatagramSocketImplFactory;)V',
  );

  static final _set$datagramSocketImplFactory =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallStaticVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `static public void setDatagramSocketImplFactory(java.net.DatagramSocketImplFactory datagramSocketImplFactory)`
  static set datagramSocketImplFactory(
    jni$_.JObject? datagramSocketImplFactory,
  ) {
    final _$datagramSocketImplFactory =
        datagramSocketImplFactory?.reference ?? jni$_.jNullReference;
    _set$datagramSocketImplFactory(
      _class.reference.pointer,
      _id_set$datagramSocketImplFactory.pointer,
      _$datagramSocketImplFactory.pointer,
    ).check();
  }
}

extension DatagramSocket$$Methods on DatagramSocket {
  static final _id_bind = DatagramSocket._class.instanceMethodId(
    r'bind',
    r'(Ljava/net/SocketAddress;)V',
  );

  static final _bind =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void bind(java.net.SocketAddress socketAddress)`
  void bind(jni$_.JObject? socketAddress) {
    final _$socketAddress = socketAddress?.reference ?? jni$_.jNullReference;
    _bind(reference.pointer, _id_bind.pointer, _$socketAddress.pointer).check();
  }

  static final _id_close = DatagramSocket._class.instanceMethodId(
    r'close',
    r'()V',
  );

  static final _close =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public void close()`
  void close() {
    _close(reference.pointer, _id_close.pointer).check();
  }

  static final _id_connect = DatagramSocket._class.instanceMethodId(
    r'connect',
    r'(Ljava/net/InetAddress;I)V',
  );

  static final _connect =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>, jni$_.Int32)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              core$_.int,
            )
          >();

  /// from: `public void connect(java.net.InetAddress inetAddress, int i)`
  void connect(inetaddress$_.InetAddress? inetAddress, core$_.int i) {
    final _$inetAddress = inetAddress?.reference ?? jni$_.jNullReference;
    _connect(
      reference.pointer,
      _id_connect.pointer,
      _$inetAddress.pointer,
      i,
    ).check();
  }

  static final _id_connect$1 = DatagramSocket._class.instanceMethodId(
    r'connect',
    r'(Ljava/net/SocketAddress;)V',
  );

  static final _connect$1 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void connect(java.net.SocketAddress socketAddress)`
  void connect$1(jni$_.JObject? socketAddress) {
    final _$socketAddress = socketAddress?.reference ?? jni$_.jNullReference;
    _connect$1(
      reference.pointer,
      _id_connect$1.pointer,
      _$socketAddress.pointer,
    ).check();
  }

  static final _id_disconnect = DatagramSocket._class.instanceMethodId(
    r'disconnect',
    r'()V',
  );

  static final _disconnect =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public void disconnect()`
  void disconnect() {
    _disconnect(reference.pointer, _id_disconnect.pointer).check();
  }

  static final _id_get$broadcast = DatagramSocket._class.instanceMethodId(
    r'getBroadcast',
    r'()Z',
  );

  static final _get$broadcast =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallBooleanMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public boolean getBroadcast()`
  core$_.bool get broadcast {
    return _get$broadcast(reference.pointer, _id_get$broadcast.pointer).boolean;
  }

  static final _id_get$channel = DatagramSocket._class.instanceMethodId(
    r'getChannel',
    r'()Ljava/nio/channels/DatagramChannel;',
  );

  static final _get$channel =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public java.nio.channels.DatagramChannel getChannel()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JObject? get channel {
    return _get$channel(
      reference.pointer,
      _id_get$channel.pointer,
    ).object<jni$_.JObject?>();
  }

  static final _id_get$inetAddress = DatagramSocket._class.instanceMethodId(
    r'getInetAddress',
    r'()Ljava/net/InetAddress;',
  );

  static final _get$inetAddress =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public java.net.InetAddress getInetAddress()`
  /// The returned object must be released after use, by calling the [release] method.
  inetaddress$_.InetAddress? get inetAddress {
    return _get$inetAddress(
      reference.pointer,
      _id_get$inetAddress.pointer,
    ).object<inetaddress$_.InetAddress?>();
  }

  static final _id_get$localAddress = DatagramSocket._class.instanceMethodId(
    r'getLocalAddress',
    r'()Ljava/net/InetAddress;',
  );

  static final _get$localAddress =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public java.net.InetAddress getLocalAddress()`
  /// The returned object must be released after use, by calling the [release] method.
  inetaddress$_.InetAddress? get localAddress {
    return _get$localAddress(
      reference.pointer,
      _id_get$localAddress.pointer,
    ).object<inetaddress$_.InetAddress?>();
  }

  static final _id_get$localPort = DatagramSocket._class.instanceMethodId(
    r'getLocalPort',
    r'()I',
  );

  static final _get$localPort =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallIntMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public int getLocalPort()`
  core$_.int get localPort {
    return _get$localPort(reference.pointer, _id_get$localPort.pointer).integer;
  }

  static final _id_get$localSocketAddress = DatagramSocket._class
      .instanceMethodId(
        r'getLocalSocketAddress',
        r'()Ljava/net/SocketAddress;',
      );

  static final _get$localSocketAddress =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public java.net.SocketAddress getLocalSocketAddress()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JObject? get localSocketAddress {
    return _get$localSocketAddress(
      reference.pointer,
      _id_get$localSocketAddress.pointer,
    ).object<jni$_.JObject?>();
  }

  static final _id_getOption = DatagramSocket._class.instanceMethodId(
    r'getOption',
    r'(Ljava/net/SocketOption;)Ljava/lang/Object;',
  );

  static final _getOption =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public T getOption(java.net.SocketOption<T> socketOption)`
  /// The returned object must be released after use, by calling the [release] method.
  $T? getOption<$T extends jni$_.JObject?>(jni$_.JObject? socketOption) {
    final _$socketOption = socketOption?.reference ?? jni$_.jNullReference;
    return _getOption(
      reference.pointer,
      _id_getOption.pointer,
      _$socketOption.pointer,
    ).object<$T?>();
  }

  static final _id_get$port = DatagramSocket._class.instanceMethodId(
    r'getPort',
    r'()I',
  );

  static final _get$port =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallIntMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public int getPort()`
  core$_.int get port {
    return _get$port(reference.pointer, _id_get$port.pointer).integer;
  }

  static final _id_get$receiveBufferSize = DatagramSocket._class
      .instanceMethodId(r'getReceiveBufferSize', r'()I');

  static final _get$receiveBufferSize =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallIntMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public int getReceiveBufferSize()`
  core$_.int get receiveBufferSize {
    return _get$receiveBufferSize(
      reference.pointer,
      _id_get$receiveBufferSize.pointer,
    ).integer;
  }

  static final _id_get$remoteSocketAddress = DatagramSocket._class
      .instanceMethodId(
        r'getRemoteSocketAddress',
        r'()Ljava/net/SocketAddress;',
      );

  static final _get$remoteSocketAddress =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public java.net.SocketAddress getRemoteSocketAddress()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JObject? get remoteSocketAddress {
    return _get$remoteSocketAddress(
      reference.pointer,
      _id_get$remoteSocketAddress.pointer,
    ).object<jni$_.JObject?>();
  }

  static final _id_get$reuseAddress = DatagramSocket._class.instanceMethodId(
    r'getReuseAddress',
    r'()Z',
  );

  static final _get$reuseAddress =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallBooleanMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public boolean getReuseAddress()`
  core$_.bool get reuseAddress {
    return _get$reuseAddress(
      reference.pointer,
      _id_get$reuseAddress.pointer,
    ).boolean;
  }

  static final _id_get$sendBufferSize = DatagramSocket._class.instanceMethodId(
    r'getSendBufferSize',
    r'()I',
  );

  static final _get$sendBufferSize =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallIntMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public int getSendBufferSize()`
  core$_.int get sendBufferSize {
    return _get$sendBufferSize(
      reference.pointer,
      _id_get$sendBufferSize.pointer,
    ).integer;
  }

  static final _id_get$soTimeout = DatagramSocket._class.instanceMethodId(
    r'getSoTimeout',
    r'()I',
  );

  static final _get$soTimeout =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallIntMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public int getSoTimeout()`
  core$_.int get soTimeout {
    return _get$soTimeout(reference.pointer, _id_get$soTimeout.pointer).integer;
  }

  static final _id_get$trafficClass = DatagramSocket._class.instanceMethodId(
    r'getTrafficClass',
    r'()I',
  );

  static final _get$trafficClass =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallIntMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public int getTrafficClass()`
  core$_.int get trafficClass {
    return _get$trafficClass(
      reference.pointer,
      _id_get$trafficClass.pointer,
    ).integer;
  }

  static final _id_get$isBound = DatagramSocket._class.instanceMethodId(
    r'isBound',
    r'()Z',
  );

  static final _get$isBound =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallBooleanMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public boolean isBound()`
  core$_.bool get isBound {
    return _get$isBound(reference.pointer, _id_get$isBound.pointer).boolean;
  }

  static final _id_get$isClosed = DatagramSocket._class.instanceMethodId(
    r'isClosed',
    r'()Z',
  );

  static final _get$isClosed =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallBooleanMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public boolean isClosed()`
  core$_.bool get isClosed {
    return _get$isClosed(reference.pointer, _id_get$isClosed.pointer).boolean;
  }

  static final _id_get$isConnected = DatagramSocket._class.instanceMethodId(
    r'isConnected',
    r'()Z',
  );

  static final _get$isConnected =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallBooleanMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public boolean isConnected()`
  core$_.bool get isConnected {
    return _get$isConnected(
      reference.pointer,
      _id_get$isConnected.pointer,
    ).boolean;
  }

  static final _id_receive = DatagramSocket._class.instanceMethodId(
    r'receive',
    r'(Ljava/net/DatagramPacket;)V',
  );

  static final _receive =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void receive(java.net.DatagramPacket datagramPacket)`
  void receive(jni$_.JObject? datagramPacket) {
    final _$datagramPacket = datagramPacket?.reference ?? jni$_.jNullReference;
    _receive(
      reference.pointer,
      _id_receive.pointer,
      _$datagramPacket.pointer,
    ).check();
  }

  static final _id_send = DatagramSocket._class.instanceMethodId(
    r'send',
    r'(Ljava/net/DatagramPacket;)V',
  );

  static final _send =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void send(java.net.DatagramPacket datagramPacket)`
  void send(jni$_.JObject? datagramPacket) {
    final _$datagramPacket = datagramPacket?.reference ?? jni$_.jNullReference;
    _send(
      reference.pointer,
      _id_send.pointer,
      _$datagramPacket.pointer,
    ).check();
  }

  static final _id_set$broadcast = DatagramSocket._class.instanceMethodId(
    r'setBroadcast',
    r'(Z)V',
  );

  static final _set$broadcast =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Int32,)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              core$_.int,
            )
          >();

  /// from: `public void setBroadcast(boolean z)`
  set broadcast(core$_.bool z) {
    _set$broadcast(
      reference.pointer,
      _id_set$broadcast.pointer,
      z ? 1 : 0,
    ).check();
  }

  static final _id_setOption = DatagramSocket._class.instanceMethodId(
    r'setOption',
    r'(Ljava/net/SocketOption;Ljava/lang/Object;)Ljava/net/DatagramSocket;',
  );

  static final _setOption =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (jni$_.Pointer<jni$_.Void>, jni$_.Pointer<jni$_.Void>)
                >,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public java.net.DatagramSocket setOption(java.net.SocketOption<T> socketOption, T object)`
  /// The returned object must be released after use, by calling the [release] method.
  DatagramSocket? setOption<$T extends jni$_.JObject?>(
    jni$_.JObject? socketOption,
    $T? object,
  ) {
    final _$socketOption = socketOption?.reference ?? jni$_.jNullReference;
    final _$object = object?.reference ?? jni$_.jNullReference;
    return _setOption(
      reference.pointer,
      _id_setOption.pointer,
      _$socketOption.pointer,
      _$object.pointer,
    ).object<DatagramSocket?>();
  }

  static final _id_set$receiveBufferSize = DatagramSocket._class
      .instanceMethodId(r'setReceiveBufferSize', r'(I)V');

  static final _set$receiveBufferSize =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Int32,)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              core$_.int,
            )
          >();

  /// from: `public void setReceiveBufferSize(int i)`
  set receiveBufferSize(core$_.int i) {
    _set$receiveBufferSize(
      reference.pointer,
      _id_set$receiveBufferSize.pointer,
      i,
    ).check();
  }

  static final _id_set$reuseAddress = DatagramSocket._class.instanceMethodId(
    r'setReuseAddress',
    r'(Z)V',
  );

  static final _set$reuseAddress =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Int32,)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              core$_.int,
            )
          >();

  /// from: `public void setReuseAddress(boolean z)`
  set reuseAddress(core$_.bool z) {
    _set$reuseAddress(
      reference.pointer,
      _id_set$reuseAddress.pointer,
      z ? 1 : 0,
    ).check();
  }

  static final _id_set$sendBufferSize = DatagramSocket._class.instanceMethodId(
    r'setSendBufferSize',
    r'(I)V',
  );

  static final _set$sendBufferSize =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Int32,)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              core$_.int,
            )
          >();

  /// from: `public void setSendBufferSize(int i)`
  set sendBufferSize(core$_.int i) {
    _set$sendBufferSize(
      reference.pointer,
      _id_set$sendBufferSize.pointer,
      i,
    ).check();
  }

  static final _id_set$soTimeout = DatagramSocket._class.instanceMethodId(
    r'setSoTimeout',
    r'(I)V',
  );

  static final _set$soTimeout =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Int32,)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              core$_.int,
            )
          >();

  /// from: `public void setSoTimeout(int i)`
  set soTimeout(core$_.int i) {
    _set$soTimeout(reference.pointer, _id_set$soTimeout.pointer, i).check();
  }

  static final _id_set$trafficClass = DatagramSocket._class.instanceMethodId(
    r'setTrafficClass',
    r'(I)V',
  );

  static final _set$trafficClass =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Int32,)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              core$_.int,
            )
          >();

  /// from: `public void setTrafficClass(int i)`
  set trafficClass(core$_.int i) {
    _set$trafficClass(
      reference.pointer,
      _id_set$trafficClass.pointer,
      i,
    ).check();
  }

  static final _id_supportedOptions = DatagramSocket._class.instanceMethodId(
    r'supportedOptions',
    r'()Ljava/util/Set;',
  );

  static final _supportedOptions =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public java.util.Set<java.net.SocketOption<?>> supportedOptions()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JSet<jni$_.JObject?>? supportedOptions() {
    return _supportedOptions(
      reference.pointer,
      _id_supportedOptions.pointer,
    ).object<jni$_.JSet<jni$_.JObject?>?>();
  }
}

final class $DatagramSocket$Type$ extends jni$_.JType<DatagramSocket> {
  @jni$_.internal
  const $DatagramSocket$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Ljava/net/DatagramSocket;';
}
