// AUTO GENERATED BY JNIGEN 0.16.0. DO NOT EDIT!

// ignore_for_file: annotate_overrides
// ignore_for_file: argument_type_not_assignable
// ignore_for_file: camel_case_extensions
// ignore_for_file: camel_case_types
// ignore_for_file: constant_identifier_names
// ignore_for_file: comment_references
// ignore_for_file: doc_directive_unknown
// ignore_for_file: file_names
// ignore_for_file: inference_failure_on_untyped_parameter
// ignore_for_file: invalid_internal_annotation
// ignore_for_file: invalid_use_of_internal_member
// ignore_for_file: library_prefixes
// ignore_for_file: lines_longer_than_80_chars
// ignore_for_file: no_leading_underscores_for_library_prefixes
// ignore_for_file: no_leading_underscores_for_local_identifiers
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: only_throw_errors
// ignore_for_file: overridden_fields
// ignore_for_file: prefer_double_quotes
// ignore_for_file: unintended_html_in_doc_comment
// ignore_for_file: unnecessary_cast
// ignore_for_file: unnecessary_non_null_assertion
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: unused_element
// ignore_for_file: unused_field
// ignore_for_file: unused_import
// ignore_for_file: unused_local_variable
// ignore_for_file: unused_shown_name
// ignore_for_file: use_super_parameters

import 'dart:core' as core$_;
import 'dart:core' show Object, String;

import 'package:jni/_internal.dart' as jni$_;
import 'package:jni/jni.dart' as jni$_;

import '../io/Closeable.dart' as closeable$_;

import '../io/InputStream.dart' as inputstream$_;

import '../io/OutputStream.dart' as outputstream$_;

import 'InetAddress.dart' as inetaddress$_;

import 'Proxy.dart' as proxy$_;

/// from: `java.net.Socket`
extension type Socket._(jni$_.JObject _$this)
    implements jni$_.JObject, closeable$_.Closeable {
  static final _class = jni$_.JClass.forName(r'java/net/Socket');

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<Socket> type = $Socket$Type$();
  static final _id_new$ = _class.constructorId(r'()V');

  static final _new$ =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public void <init>()`
  /// The returned object must be released after use, by calling the [release] method.
  factory Socket() {
    return _new$(_class.reference.pointer, _id_new$.pointer).object<Socket>();
  }

  static final _id_new$1 = _class.constructorId(r'(Ljava/lang/String;I)V');

  static final _new$1 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>, jni$_.Int32)>,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              core$_.int,
            )
          >();

  /// from: `public void <init>(java.lang.String string, int i)`
  /// The returned object must be released after use, by calling the [release] method.
  factory Socket.new$1(jni$_.JString? string, core$_.int i) {
    final _$string = string?.reference ?? jni$_.jNullReference;
    return _new$1(
      _class.reference.pointer,
      _id_new$1.pointer,
      _$string.pointer,
      i,
    ).object<Socket>();
  }

  static final _id_new$2 = _class.constructorId(r'(Ljava/lang/String;IZ)V');

  static final _new$2 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (jni$_.Pointer<jni$_.Void>, jni$_.Int32, jni$_.Int32)
                >,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              core$_.int,
              core$_.int,
            )
          >();

  /// from: `public void <init>(java.lang.String string, int i, boolean z)`
  /// The returned object must be released after use, by calling the [release] method.
  factory Socket.new$2(jni$_.JString? string, core$_.int i, core$_.bool z) {
    final _$string = string?.reference ?? jni$_.jNullReference;
    return _new$2(
      _class.reference.pointer,
      _id_new$2.pointer,
      _$string.pointer,
      i,
      z ? 1 : 0,
    ).object<Socket>();
  }

  static final _id_new$3 = _class.constructorId(
    r'(Ljava/lang/String;ILjava/net/InetAddress;I)V',
  );

  static final _new$3 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Int32,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Int32,
                  )
                >,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              core$_.int,
              jni$_.Pointer<jni$_.Void>,
              core$_.int,
            )
          >();

  /// from: `public void <init>(java.lang.String string, int i, java.net.InetAddress inetAddress, int i1)`
  /// The returned object must be released after use, by calling the [release] method.
  factory Socket.new$3(
    jni$_.JString? string,
    core$_.int i,
    inetaddress$_.InetAddress? inetAddress,
    core$_.int i1,
  ) {
    final _$string = string?.reference ?? jni$_.jNullReference;
    final _$inetAddress = inetAddress?.reference ?? jni$_.jNullReference;
    return _new$3(
      _class.reference.pointer,
      _id_new$3.pointer,
      _$string.pointer,
      i,
      _$inetAddress.pointer,
      i1,
    ).object<Socket>();
  }

  static final _id_new$4 = _class.constructorId(r'(Ljava/net/InetAddress;I)V');

  static final _new$4 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>, jni$_.Int32)>,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              core$_.int,
            )
          >();

  /// from: `public void <init>(java.net.InetAddress inetAddress, int i)`
  /// The returned object must be released after use, by calling the [release] method.
  factory Socket.new$4(inetaddress$_.InetAddress? inetAddress, core$_.int i) {
    final _$inetAddress = inetAddress?.reference ?? jni$_.jNullReference;
    return _new$4(
      _class.reference.pointer,
      _id_new$4.pointer,
      _$inetAddress.pointer,
      i,
    ).object<Socket>();
  }

  static final _id_new$5 = _class.constructorId(r'(Ljava/net/InetAddress;IZ)V');

  static final _new$5 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (jni$_.Pointer<jni$_.Void>, jni$_.Int32, jni$_.Int32)
                >,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              core$_.int,
              core$_.int,
            )
          >();

  /// from: `public void <init>(java.net.InetAddress inetAddress, int i, boolean z)`
  /// The returned object must be released after use, by calling the [release] method.
  factory Socket.new$5(
    inetaddress$_.InetAddress? inetAddress,
    core$_.int i,
    core$_.bool z,
  ) {
    final _$inetAddress = inetAddress?.reference ?? jni$_.jNullReference;
    return _new$5(
      _class.reference.pointer,
      _id_new$5.pointer,
      _$inetAddress.pointer,
      i,
      z ? 1 : 0,
    ).object<Socket>();
  }

  static final _id_new$6 = _class.constructorId(
    r'(Ljava/net/InetAddress;ILjava/net/InetAddress;I)V',
  );

  static final _new$6 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Int32,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Int32,
                  )
                >,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              core$_.int,
              jni$_.Pointer<jni$_.Void>,
              core$_.int,
            )
          >();

  /// from: `public void <init>(java.net.InetAddress inetAddress, int i, java.net.InetAddress inetAddress1, int i1)`
  /// The returned object must be released after use, by calling the [release] method.
  factory Socket.new$6(
    inetaddress$_.InetAddress? inetAddress,
    core$_.int i,
    inetaddress$_.InetAddress? inetAddress1,
    core$_.int i1,
  ) {
    final _$inetAddress = inetAddress?.reference ?? jni$_.jNullReference;
    final _$inetAddress1 = inetAddress1?.reference ?? jni$_.jNullReference;
    return _new$6(
      _class.reference.pointer,
      _id_new$6.pointer,
      _$inetAddress.pointer,
      i,
      _$inetAddress1.pointer,
      i1,
    ).object<Socket>();
  }

  static final _id_new$7 = _class.constructorId(r'(Ljava/net/Proxy;)V');

  static final _new$7 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void <init>(java.net.Proxy proxy)`
  /// The returned object must be released after use, by calling the [release] method.
  factory Socket.new$7(proxy$_.Proxy? proxy) {
    final _$proxy = proxy?.reference ?? jni$_.jNullReference;
    return _new$7(
      _class.reference.pointer,
      _id_new$7.pointer,
      _$proxy.pointer,
    ).object<Socket>();
  }

  static final _id_set$socketImplFactory = _class.staticMethodId(
    r'setSocketImplFactory',
    r'(Ljava/net/SocketImplFactory;)V',
  );

  static final _set$socketImplFactory =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallStaticVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `static public void setSocketImplFactory(java.net.SocketImplFactory socketImplFactory)`
  static set socketImplFactory(jni$_.JObject? socketImplFactory) {
    final _$socketImplFactory =
        socketImplFactory?.reference ?? jni$_.jNullReference;
    _set$socketImplFactory(
      _class.reference.pointer,
      _id_set$socketImplFactory.pointer,
      _$socketImplFactory.pointer,
    ).check();
  }
}

extension Socket$$Methods on Socket {
  static final _id_bind = Socket._class.instanceMethodId(
    r'bind',
    r'(Ljava/net/SocketAddress;)V',
  );

  static final _bind =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void bind(java.net.SocketAddress socketAddress)`
  void bind(jni$_.JObject? socketAddress) {
    final _$socketAddress = socketAddress?.reference ?? jni$_.jNullReference;
    _bind(reference.pointer, _id_bind.pointer, _$socketAddress.pointer).check();
  }

  static final _id_close = Socket._class.instanceMethodId(r'close', r'()V');

  static final _close =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public void close()`
  void close() {
    _close(reference.pointer, _id_close.pointer).check();
  }

  static final _id_connect = Socket._class.instanceMethodId(
    r'connect',
    r'(Ljava/net/SocketAddress;)V',
  );

  static final _connect =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void connect(java.net.SocketAddress socketAddress)`
  void connect(jni$_.JObject? socketAddress) {
    final _$socketAddress = socketAddress?.reference ?? jni$_.jNullReference;
    _connect(
      reference.pointer,
      _id_connect.pointer,
      _$socketAddress.pointer,
    ).check();
  }

  static final _id_connect$1 = Socket._class.instanceMethodId(
    r'connect',
    r'(Ljava/net/SocketAddress;I)V',
  );

  static final _connect$1 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>, jni$_.Int32)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              core$_.int,
            )
          >();

  /// from: `public void connect(java.net.SocketAddress socketAddress, int i)`
  void connect$1(jni$_.JObject? socketAddress, core$_.int i) {
    final _$socketAddress = socketAddress?.reference ?? jni$_.jNullReference;
    _connect$1(
      reference.pointer,
      _id_connect$1.pointer,
      _$socketAddress.pointer,
      i,
    ).check();
  }

  static final _id_get$channel = Socket._class.instanceMethodId(
    r'getChannel',
    r'()Ljava/nio/channels/SocketChannel;',
  );

  static final _get$channel =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public java.nio.channels.SocketChannel getChannel()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JObject? get channel {
    return _get$channel(
      reference.pointer,
      _id_get$channel.pointer,
    ).object<jni$_.JObject?>();
  }

  static final _id_get$inetAddress = Socket._class.instanceMethodId(
    r'getInetAddress',
    r'()Ljava/net/InetAddress;',
  );

  static final _get$inetAddress =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public java.net.InetAddress getInetAddress()`
  /// The returned object must be released after use, by calling the [release] method.
  inetaddress$_.InetAddress? get inetAddress {
    return _get$inetAddress(
      reference.pointer,
      _id_get$inetAddress.pointer,
    ).object<inetaddress$_.InetAddress?>();
  }

  static final _id_get$inputStream = Socket._class.instanceMethodId(
    r'getInputStream',
    r'()Ljava/io/InputStream;',
  );

  static final _get$inputStream =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public java.io.InputStream getInputStream()`
  /// The returned object must be released after use, by calling the [release] method.
  inputstream$_.InputStream? get inputStream {
    return _get$inputStream(
      reference.pointer,
      _id_get$inputStream.pointer,
    ).object<inputstream$_.InputStream?>();
  }

  static final _id_get$keepAlive = Socket._class.instanceMethodId(
    r'getKeepAlive',
    r'()Z',
  );

  static final _get$keepAlive =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallBooleanMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public boolean getKeepAlive()`
  core$_.bool get keepAlive {
    return _get$keepAlive(reference.pointer, _id_get$keepAlive.pointer).boolean;
  }

  static final _id_get$localAddress = Socket._class.instanceMethodId(
    r'getLocalAddress',
    r'()Ljava/net/InetAddress;',
  );

  static final _get$localAddress =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public java.net.InetAddress getLocalAddress()`
  /// The returned object must be released after use, by calling the [release] method.
  inetaddress$_.InetAddress? get localAddress {
    return _get$localAddress(
      reference.pointer,
      _id_get$localAddress.pointer,
    ).object<inetaddress$_.InetAddress?>();
  }

  static final _id_get$localPort = Socket._class.instanceMethodId(
    r'getLocalPort',
    r'()I',
  );

  static final _get$localPort =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallIntMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public int getLocalPort()`
  core$_.int get localPort {
    return _get$localPort(reference.pointer, _id_get$localPort.pointer).integer;
  }

  static final _id_get$localSocketAddress = Socket._class.instanceMethodId(
    r'getLocalSocketAddress',
    r'()Ljava/net/SocketAddress;',
  );

  static final _get$localSocketAddress =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public java.net.SocketAddress getLocalSocketAddress()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JObject? get localSocketAddress {
    return _get$localSocketAddress(
      reference.pointer,
      _id_get$localSocketAddress.pointer,
    ).object<jni$_.JObject?>();
  }

  static final _id_get$oOBInline = Socket._class.instanceMethodId(
    r'getOOBInline',
    r'()Z',
  );

  static final _get$oOBInline =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallBooleanMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public boolean getOOBInline()`
  core$_.bool get oOBInline {
    return _get$oOBInline(reference.pointer, _id_get$oOBInline.pointer).boolean;
  }

  static final _id_getOption = Socket._class.instanceMethodId(
    r'getOption',
    r'(Ljava/net/SocketOption;)Ljava/lang/Object;',
  );

  static final _getOption =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public T getOption(java.net.SocketOption<T> socketOption)`
  /// The returned object must be released after use, by calling the [release] method.
  $T? getOption<$T extends jni$_.JObject?>(jni$_.JObject? socketOption) {
    final _$socketOption = socketOption?.reference ?? jni$_.jNullReference;
    return _getOption(
      reference.pointer,
      _id_getOption.pointer,
      _$socketOption.pointer,
    ).object<$T?>();
  }

  static final _id_get$outputStream = Socket._class.instanceMethodId(
    r'getOutputStream',
    r'()Ljava/io/OutputStream;',
  );

  static final _get$outputStream =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public java.io.OutputStream getOutputStream()`
  /// The returned object must be released after use, by calling the [release] method.
  outputstream$_.OutputStream? get outputStream {
    return _get$outputStream(
      reference.pointer,
      _id_get$outputStream.pointer,
    ).object<outputstream$_.OutputStream?>();
  }

  static final _id_get$port = Socket._class.instanceMethodId(
    r'getPort',
    r'()I',
  );

  static final _get$port =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallIntMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public int getPort()`
  core$_.int get port {
    return _get$port(reference.pointer, _id_get$port.pointer).integer;
  }

  static final _id_get$receiveBufferSize = Socket._class.instanceMethodId(
    r'getReceiveBufferSize',
    r'()I',
  );

  static final _get$receiveBufferSize =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallIntMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public int getReceiveBufferSize()`
  core$_.int get receiveBufferSize {
    return _get$receiveBufferSize(
      reference.pointer,
      _id_get$receiveBufferSize.pointer,
    ).integer;
  }

  static final _id_get$remoteSocketAddress = Socket._class.instanceMethodId(
    r'getRemoteSocketAddress',
    r'()Ljava/net/SocketAddress;',
  );

  static final _get$remoteSocketAddress =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public java.net.SocketAddress getRemoteSocketAddress()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JObject? get remoteSocketAddress {
    return _get$remoteSocketAddress(
      reference.pointer,
      _id_get$remoteSocketAddress.pointer,
    ).object<jni$_.JObject?>();
  }

  static final _id_get$reuseAddress = Socket._class.instanceMethodId(
    r'getReuseAddress',
    r'()Z',
  );

  static final _get$reuseAddress =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallBooleanMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public boolean getReuseAddress()`
  core$_.bool get reuseAddress {
    return _get$reuseAddress(
      reference.pointer,
      _id_get$reuseAddress.pointer,
    ).boolean;
  }

  static final _id_get$sendBufferSize = Socket._class.instanceMethodId(
    r'getSendBufferSize',
    r'()I',
  );

  static final _get$sendBufferSize =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallIntMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public int getSendBufferSize()`
  core$_.int get sendBufferSize {
    return _get$sendBufferSize(
      reference.pointer,
      _id_get$sendBufferSize.pointer,
    ).integer;
  }

  static final _id_get$soLinger = Socket._class.instanceMethodId(
    r'getSoLinger',
    r'()I',
  );

  static final _get$soLinger =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallIntMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public int getSoLinger()`
  core$_.int get soLinger {
    return _get$soLinger(reference.pointer, _id_get$soLinger.pointer).integer;
  }

  static final _id_get$soTimeout = Socket._class.instanceMethodId(
    r'getSoTimeout',
    r'()I',
  );

  static final _get$soTimeout =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallIntMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public int getSoTimeout()`
  core$_.int get soTimeout {
    return _get$soTimeout(reference.pointer, _id_get$soTimeout.pointer).integer;
  }

  static final _id_get$tcpNoDelay = Socket._class.instanceMethodId(
    r'getTcpNoDelay',
    r'()Z',
  );

  static final _get$tcpNoDelay =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallBooleanMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public boolean getTcpNoDelay()`
  core$_.bool get tcpNoDelay {
    return _get$tcpNoDelay(
      reference.pointer,
      _id_get$tcpNoDelay.pointer,
    ).boolean;
  }

  static final _id_get$trafficClass = Socket._class.instanceMethodId(
    r'getTrafficClass',
    r'()I',
  );

  static final _get$trafficClass =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallIntMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public int getTrafficClass()`
  core$_.int get trafficClass {
    return _get$trafficClass(
      reference.pointer,
      _id_get$trafficClass.pointer,
    ).integer;
  }

  static final _id_get$isBound = Socket._class.instanceMethodId(
    r'isBound',
    r'()Z',
  );

  static final _get$isBound =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallBooleanMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public boolean isBound()`
  core$_.bool get isBound {
    return _get$isBound(reference.pointer, _id_get$isBound.pointer).boolean;
  }

  static final _id_get$isClosed = Socket._class.instanceMethodId(
    r'isClosed',
    r'()Z',
  );

  static final _get$isClosed =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallBooleanMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public boolean isClosed()`
  core$_.bool get isClosed {
    return _get$isClosed(reference.pointer, _id_get$isClosed.pointer).boolean;
  }

  static final _id_get$isConnected = Socket._class.instanceMethodId(
    r'isConnected',
    r'()Z',
  );

  static final _get$isConnected =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallBooleanMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public boolean isConnected()`
  core$_.bool get isConnected {
    return _get$isConnected(
      reference.pointer,
      _id_get$isConnected.pointer,
    ).boolean;
  }

  static final _id_get$isInputShutdown = Socket._class.instanceMethodId(
    r'isInputShutdown',
    r'()Z',
  );

  static final _get$isInputShutdown =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallBooleanMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public boolean isInputShutdown()`
  core$_.bool get isInputShutdown {
    return _get$isInputShutdown(
      reference.pointer,
      _id_get$isInputShutdown.pointer,
    ).boolean;
  }

  static final _id_get$isOutputShutdown = Socket._class.instanceMethodId(
    r'isOutputShutdown',
    r'()Z',
  );

  static final _get$isOutputShutdown =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallBooleanMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public boolean isOutputShutdown()`
  core$_.bool get isOutputShutdown {
    return _get$isOutputShutdown(
      reference.pointer,
      _id_get$isOutputShutdown.pointer,
    ).boolean;
  }

  static final _id_sendUrgentData = Socket._class.instanceMethodId(
    r'sendUrgentData',
    r'(I)V',
  );

  static final _sendUrgentData =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Int32,)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              core$_.int,
            )
          >();

  /// from: `public void sendUrgentData(int i)`
  void sendUrgentData(core$_.int i) {
    _sendUrgentData(reference.pointer, _id_sendUrgentData.pointer, i).check();
  }

  static final _id_set$keepAlive = Socket._class.instanceMethodId(
    r'setKeepAlive',
    r'(Z)V',
  );

  static final _set$keepAlive =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Int32,)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              core$_.int,
            )
          >();

  /// from: `public void setKeepAlive(boolean z)`
  set keepAlive(core$_.bool z) {
    _set$keepAlive(
      reference.pointer,
      _id_set$keepAlive.pointer,
      z ? 1 : 0,
    ).check();
  }

  static final _id_set$oOBInline = Socket._class.instanceMethodId(
    r'setOOBInline',
    r'(Z)V',
  );

  static final _set$oOBInline =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Int32,)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              core$_.int,
            )
          >();

  /// from: `public void setOOBInline(boolean z)`
  set oOBInline(core$_.bool z) {
    _set$oOBInline(
      reference.pointer,
      _id_set$oOBInline.pointer,
      z ? 1 : 0,
    ).check();
  }

  static final _id_setOption = Socket._class.instanceMethodId(
    r'setOption',
    r'(Ljava/net/SocketOption;Ljava/lang/Object;)Ljava/net/Socket;',
  );

  static final _setOption =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (jni$_.Pointer<jni$_.Void>, jni$_.Pointer<jni$_.Void>)
                >,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public java.net.Socket setOption(java.net.SocketOption<T> socketOption, T object)`
  /// The returned object must be released after use, by calling the [release] method.
  Socket? setOption<$T extends jni$_.JObject?>(
    jni$_.JObject? socketOption,
    $T? object,
  ) {
    final _$socketOption = socketOption?.reference ?? jni$_.jNullReference;
    final _$object = object?.reference ?? jni$_.jNullReference;
    return _setOption(
      reference.pointer,
      _id_setOption.pointer,
      _$socketOption.pointer,
      _$object.pointer,
    ).object<Socket?>();
  }

  static final _id_setPerformancePreferences = Socket._class.instanceMethodId(
    r'setPerformancePreferences',
    r'(III)V',
  );

  static final _setPerformancePreferences =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Int32, jni$_.Int32, jni$_.Int32)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              core$_.int,
              core$_.int,
              core$_.int,
            )
          >();

  /// from: `public void setPerformancePreferences(int i, int i1, int i2)`
  void setPerformancePreferences(core$_.int i, core$_.int i1, core$_.int i2) {
    _setPerformancePreferences(
      reference.pointer,
      _id_setPerformancePreferences.pointer,
      i,
      i1,
      i2,
    ).check();
  }

  static final _id_set$receiveBufferSize = Socket._class.instanceMethodId(
    r'setReceiveBufferSize',
    r'(I)V',
  );

  static final _set$receiveBufferSize =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Int32,)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              core$_.int,
            )
          >();

  /// from: `public void setReceiveBufferSize(int i)`
  set receiveBufferSize(core$_.int i) {
    _set$receiveBufferSize(
      reference.pointer,
      _id_set$receiveBufferSize.pointer,
      i,
    ).check();
  }

  static final _id_set$reuseAddress = Socket._class.instanceMethodId(
    r'setReuseAddress',
    r'(Z)V',
  );

  static final _set$reuseAddress =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Int32,)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              core$_.int,
            )
          >();

  /// from: `public void setReuseAddress(boolean z)`
  set reuseAddress(core$_.bool z) {
    _set$reuseAddress(
      reference.pointer,
      _id_set$reuseAddress.pointer,
      z ? 1 : 0,
    ).check();
  }

  static final _id_set$sendBufferSize = Socket._class.instanceMethodId(
    r'setSendBufferSize',
    r'(I)V',
  );

  static final _set$sendBufferSize =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Int32,)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              core$_.int,
            )
          >();

  /// from: `public void setSendBufferSize(int i)`
  set sendBufferSize(core$_.int i) {
    _set$sendBufferSize(
      reference.pointer,
      _id_set$sendBufferSize.pointer,
      i,
    ).check();
  }

  static final _id_setSoLinger = Socket._class.instanceMethodId(
    r'setSoLinger',
    r'(ZI)V',
  );

  static final _setSoLinger =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Int32, jni$_.Int32)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              core$_.int,
              core$_.int,
            )
          >();

  /// from: `public void setSoLinger(boolean z, int i)`
  void setSoLinger(core$_.bool z, core$_.int i) {
    _setSoLinger(
      reference.pointer,
      _id_setSoLinger.pointer,
      z ? 1 : 0,
      i,
    ).check();
  }

  static final _id_set$soTimeout = Socket._class.instanceMethodId(
    r'setSoTimeout',
    r'(I)V',
  );

  static final _set$soTimeout =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Int32,)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              core$_.int,
            )
          >();

  /// from: `public void setSoTimeout(int i)`
  set soTimeout(core$_.int i) {
    _set$soTimeout(reference.pointer, _id_set$soTimeout.pointer, i).check();
  }

  static final _id_set$tcpNoDelay = Socket._class.instanceMethodId(
    r'setTcpNoDelay',
    r'(Z)V',
  );

  static final _set$tcpNoDelay =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Int32,)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              core$_.int,
            )
          >();

  /// from: `public void setTcpNoDelay(boolean z)`
  set tcpNoDelay(core$_.bool z) {
    _set$tcpNoDelay(
      reference.pointer,
      _id_set$tcpNoDelay.pointer,
      z ? 1 : 0,
    ).check();
  }

  static final _id_set$trafficClass = Socket._class.instanceMethodId(
    r'setTrafficClass',
    r'(I)V',
  );

  static final _set$trafficClass =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Int32,)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              core$_.int,
            )
          >();

  /// from: `public void setTrafficClass(int i)`
  set trafficClass(core$_.int i) {
    _set$trafficClass(
      reference.pointer,
      _id_set$trafficClass.pointer,
      i,
    ).check();
  }

  static final _id_shutdownInput = Socket._class.instanceMethodId(
    r'shutdownInput',
    r'()V',
  );

  static final _shutdownInput =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public void shutdownInput()`
  void shutdownInput() {
    _shutdownInput(reference.pointer, _id_shutdownInput.pointer).check();
  }

  static final _id_shutdownOutput = Socket._class.instanceMethodId(
    r'shutdownOutput',
    r'()V',
  );

  static final _shutdownOutput =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public void shutdownOutput()`
  void shutdownOutput() {
    _shutdownOutput(reference.pointer, _id_shutdownOutput.pointer).check();
  }

  static final _id_supportedOptions = Socket._class.instanceMethodId(
    r'supportedOptions',
    r'()Ljava/util/Set;',
  );

  static final _supportedOptions =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public java.util.Set<java.net.SocketOption<?>> supportedOptions()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JSet<jni$_.JObject?>? supportedOptions() {
    return _supportedOptions(
      reference.pointer,
      _id_supportedOptions.pointer,
    ).object<jni$_.JSet<jni$_.JObject?>?>();
  }

  static final _id_toString$1 = Socket._class.instanceMethodId(
    r'toString',
    r'()Ljava/lang/String;',
  );

  static final _toString$1 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public java.lang.String toString()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JString? toString$1() {
    return _toString$1(
      reference.pointer,
      _id_toString$1.pointer,
    ).object<jni$_.JString?>();
  }
}

final class $Socket$Type$ extends jni$_.JType<Socket> {
  @jni$_.internal
  const $Socket$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Ljava/net/Socket;';
}
