import 'dart:io';

import 'package:jnigen/jnigen.dart';
import 'package:logging/logging.dart';

void main() async {
  final root = Platform.script.resolve('../');
  final config = Config(
    outputConfig: OutputConfig(
      dartConfig: DartCodeOutputConfig(
        path: root.resolve('lib/src/jni/'),
        structure: OutputStructure.packageStructure,
      ),
    ),
    classes: [
      'android.app.Activity',
      'android.app.ActivityManager',
      'android.app.AlarmManager',
      'android.app.PendingIntent',
      'android.content.BroadcastReceiver',
      'android.content.ContentResolver',
      'android.content.Context',
      'android.content.Intent',
      'android.content.IntentFilter',
      'android.hardware.usb.UsbAccessory',
      'android.hardware.usb.UsbConfiguration',
      'android.hardware.usb.UsbConstants',
      'android.hardware.usb.UsbDevice',
      'android.hardware.usb.UsbDeviceConnection',
      'android.hardware.usb.UsbEndpoint',
      'android.hardware.usb.UsbInterface',
      'android.hardware.usb.UsbManager',
      'android.hardware.usb.UsbRequest',
      'android.icu.util.ULocale',
      'android.net.ConnectivityManager',
      'android.net.DhcpInfo',
      'android.net.InetAddresses',
      'android.net.IpPrefix',
      'android.net.IpSecManager',
      'android.net.LinkAddress',
      'android.net.LinkProperties',
      'android.net.MacAddress',
      'android.net.Network',
      'android.net.NetworkInfo',
      'android.net.NetworkRequest',
      'android.net.NetworkCapabilities',
      'android.net.NetworkSpecifier',
      'android.net.ProxyInfo',
      'android.net.RouteInfo',
      'android.net.SocketKeepalive',
      'android.net.TransportInfo',
      'android.net.Uri',
      'android.net.wifi.MloLink',
      'android.net.wifi.ScanResult',
      'android.net.wifi.SupplicantState',
      'android.net.wifi.WifiConfiguration',
      'android.net.wifi.WifiEnterpriseConfig',
      'android.net.wifi.WifiInfo',
      'android.net.wifi.WifiManager',
      'android.net.wifi.WifiSsid',
      'android.net.wifi.aware.WifiAwareNetworkInfo',
      'android.os.Build',
      'android.os.Environment',
      'android.os.Handler',
      'android.os.LocaleList',
      'android.os.Looper',
      'android.os.ParcelFileDescriptor',
      'android.os.PowerManager',
      'android.os.Process',
      'android.os.SystemClock',
      'android.os.storage.OnObbStateChangeListener',
      'android.os.storage.StorageManager',
      'android.os.storage.StorageVolume',
      'android.provider.Settings',
      'androidx.core.content.ContextCompat',
      'androidx.core.content.IntentCompat',
      'dev.zeekr.invictus_android.app.ActivityManagerCompat',
      'dev.zeekr.invictus_android.app.time.Capabilities',
      'dev.zeekr.invictus_android.app.time.ExternalTimeSuggestion',
      'dev.zeekr.invictus_android.app.time.TimeCapabilities',
      'dev.zeekr.invictus_android.app.time.TimeCapabilitiesAndConfig',
      'dev.zeekr.invictus_android.app.time.TimeCapabilitiesAndConfigCompat',
      'dev.zeekr.invictus_android.app.time.TimeConfiguration',
      'dev.zeekr.invictus_android.app.time.TimeManager',
      'dev.zeekr.invictus_android.app.time.TimeState',
      'dev.zeekr.invictus_android.app.time.TimeZoneCapabilities',
      'dev.zeekr.invictus_android.app.time.TimeZoneCapabilitiesAndConfig',
      'dev.zeekr.invictus_android.app.time.TimeZoneConfiguration',
      'dev.zeekr.invictus_android.app.time.TimeZoneState',
      'dev.zeekr.invictus_android.app.time.UnixEpochTime',
      'dev.zeekr.invictus_android.app.time.JniTimeManager',
      'dev.zeekr.invictus_android.content.JniBroadcastReceiver',
      'dev.zeekr.invictus_android.content.JniBroadcastReceiverImpl',
      'dev.zeekr.invictus_android.internal.app.LocalePicker',
      'dev.zeekr.invictus_android.internal.app.JniLocalePicker',
      'dev.zeekr.invictus_android.net.EthernetManager',
      'dev.zeekr.invictus_android.net.Inet4AddressCompat',
      'dev.zeekr.invictus_android.net.Inet6AddressCompat',
      'dev.zeekr.invictus_android.net.IpConfiguration',
      'dev.zeekr.invictus_android.net.LinkAddressCompat',
      'dev.zeekr.invictus_android.net.StaticIpConfiguration',
      'dev.zeekr.invictus_android.net.JniConnectivityManager',
      'dev.zeekr.invictus_android.net.JniEthernetManager',
      'dev.zeekr.invictus_android.net.util.Inet4AddressUtils',
      'dev.zeekr.invictus_android.net.util.NetworkUtils',
      'dev.zeekr.invictus_android.net.wifi.WifiConfigurationCompat',
      'dev.zeekr.invictus_android.net.wifi.JniWifiManager',
      'dev.zeekr.invictus_android.os.PowerManagerCompat',
      'dev.zeekr.invictus_android.os.SystemProperties',
      'dev.zeekr.invictus_android.os.storage.DiskInfo',
      'dev.zeekr.invictus_android.os.storage.StorageEventListener',
      'dev.zeekr.invictus_android.os.storage.StorageManagerCompat',
      'dev.zeekr.invictus_android.os.storage.StorageVolumeCompat',
      'dev.zeekr.invictus_android.os.storage.VolumeInfo',
      'dev.zeekr.invictus_android.os.storage.VolumeRecord',
      'dev.zeekr.invictus_android.os.storage.JniOnObbStateChangeListener',
      'dev.zeekr.invictus_android.os.storage.JniOnObbStateChangeListenerImpl',
      'dev.zeekr.invictus_android.os.storage.JniStorageEventListener',
      'dev.zeekr.invictus_android.os.storage.JniStorageEventListenerImpl',
      'dev.zeekr.invictus_android.os.storage.JniStorageManagerCompat',
      'java.io.Closeable',
      'java.io.FileDescriptor',
      'java.io.Flushable',
      'java.io.InputStream',
      'java.io.OutputStream',
      'java.lang.AutoCloseable',
      'java.lang.CharSequence',
      'java.lang.Comparable',
      'java.lang.Iterable',
      'java.lang.Runnable',
      'java.net.DatagramSocket',
      'java.net.InetAddress',
      'java.net.Inet4Address',
      'java.net.Inet6Address',
      'java.net.InetSocketAddress',
      'java.net.InterfaceAddress',
      'java.net.NetworkInterface',
      'java.net.Proxy',
      'java.net.Socket',
      'java.net.URL',
      'java.net.URLConnection',
      'java.util.AbstractCollection',
      'java.util.AbstractList',
      'java.util.AbstractMap',
      'java.util.ArrayList',
      'java.util.BitSet',
      'java.util.Collection',
      'java.util.Collections',
      'java.util.Enumeration',
      'java.util.HashMap',
      'java.util.Locale',
      'java.util.TimeZone',
      'java.util.concurrent.Executor',
      'javax.net.SocketFactory',
    ],
    sourcePath: [root.resolve('android/src/main/kotlin/')],
    androidSdkConfig: AndroidSdkConfig(
      addGradleDeps: true,
      androidExample: '../invictus/example/',
    ),
    nonNullAnnotations: ['android.annotation.NonNull'],
    nullableAnnotations: ['android.annotation.Nullable'],
    logLevel: Level.WARNING,
  );
  await generateJniBindings(config);
}
