import 'dart:io';

import 'package:jnigen/jnigen.dart';
import 'package:logging/logging.dart';

void main() async {
  final root = Platform.script.resolve('../');
  final config = Config(
    outputConfig: OutputConfig(
      dartConfig: DartCodeOutputConfig(
        path: root.resolve('lib/src/jni/'),
        structure: OutputStructure.packageStructure,
      ),
    ),
    classes: [
      'android.app.Activity',
      'android.app.PendingIntent',
      'android.content.BroadcastReceiver',
      'android.content.Context',
      'android.content.Intent',
      'android.content.IntentFilter',
      'android.hardware.usb.UsbAccessory',
      'android.hardware.usb.UsbConfiguration',
      'android.hardware.usb.UsbConstants',
      'android.hardware.usb.UsbDevice',
      'android.hardware.usb.UsbDeviceConnection',
      'android.hardware.usb.UsbEndpoint',
      'android.hardware.usb.UsbInterface',
      'android.hardware.usb.UsbManager',
      'android.hardware.usb.UsbRequest',
      'android.net.ConnectivityManager',
      'android.net.DhcpInfo',
      'android.net.InetAddresses',
      'android.net.IpPrefix',
      'android.net.IpSecManager',
      'android.net.LinkAddress',
      'android.net.LinkProperties',
      'android.net.MacAddress',
      'android.net.Network',
      'android.net.NetworkInfo',
      'android.net.NetworkRequest',
      'android.net.NetworkCapabilities',
      'android.net.NetworkSpecifier',
      'android.net.ProxyInfo',
      'android.net.RouteInfo',
      'android.net.SocketKeepalive',
      'android.net.TransportInfo',
      'android.net.wifi.MloLink',
      'android.net.wifi.ScanResult',
      'android.net.wifi.SupplicantState',
      'android.net.wifi.WifiConfiguration',
      'android.net.wifi.WifiInfo',
      'android.net.wifi.WifiManager',
      'android.net.wifi.WifiSsid',
      'android.net.wifi.aware.WifiAwareNetworkInfo',
      'android.os.Build',
      'android.os.Handler',
      'android.os.Looper',
      'android.os.PowerManager',
      'androidx.core.content.ContextCompat',
      'dev.zeekr.invictus_android.content.InvictusBroadcastReceiver',
      'dev.zeekr.invictus_android.content.InvictusContext',
      'dev.zeekr.invictus_android.content.InvictusBroadcastReceiverImpl',
      'dev.zeekr.invictus_android.net.InvictusConnectivityManager',
      'dev.zeekr.invictus_android.net.InvictusInet4Address',
      'dev.zeekr.invictus_android.net.InvictusInet6Address',
      'dev.zeekr.invictus_android.net.InvictusLinkAddress',
      'dev.zeekr.invictus_android.net.IpConfiguration',
      'dev.zeekr.invictus_android.net.StaticIpConfiguration',
      'dev.zeekr.invictus_android.net.ethernet.EthernetManager',
      'dev.zeekr.invictus_android.net.ethernet.InvictusEthernetManager',
      'dev.zeekr.invictus_android.net.util.InvictusInet4AddressUtil',
      'dev.zeekr.invictus_android.net.util.InvictusNetworkUtil',
      'dev.zeekr.invictus_android.net.wifi.InvictusWifiManager',
      'dev.zeekr.invictus_android.os.InvictusPowerManager',
      'java.io.FileDescriptor',
      'java.lang.CharSequence',
      'java.lang.Iterable',
      'java.net.DatagramSocket',
      'java.net.InetAddress',
      'java.net.Inet4Address',
      'java.net.Inet6Address',
      'java.net.InetSocketAddress',
      'java.net.InterfaceAddress',
      'java.net.NetworkInterface',
      'java.net.Proxy',
      'java.net.Socket',
      'java.net.URL',
      'java.net.URLConnection',
      'java.util.AbstractMap',
      'java.util.Collection',
      'java.util.HashMap',
      'java.util.concurrent.Executor',
      'javax.net.SocketFactory',
    ],
    sourcePath: [root.resolve('android/src/main/kotlin/')],
    androidSdkConfig: AndroidSdkConfig(
      addGradleDeps: true,
      androidExample: 'example/',
    ),
    nonNullAnnotations: ['android.annotation.NonNull'],
    nullableAnnotations: ['android.annotation.Nullable'],
    logLevel: Level.ALL,
  );
  await generateJniBindings(config);
}
