// AUTO GENERATED BY JNIGEN 0.15.0. DO NOT EDIT!

// ignore_for_file: annotate_overrides
// ignore_for_file: argument_type_not_assignable
// ignore_for_file: camel_case_extensions
// ignore_for_file: camel_case_types
// ignore_for_file: constant_identifier_names
// ignore_for_file: comment_references
// ignore_for_file: doc_directive_unknown
// ignore_for_file: file_names
// ignore_for_file: inference_failure_on_untyped_parameter
// ignore_for_file: invalid_internal_annotation
// ignore_for_file: invalid_use_of_internal_member
// ignore_for_file: library_prefixes
// ignore_for_file: lines_longer_than_80_chars
// ignore_for_file: no_leading_underscores_for_library_prefixes
// ignore_for_file: no_leading_underscores_for_local_identifiers
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: only_throw_errors
// ignore_for_file: overridden_fields
// ignore_for_file: prefer_double_quotes
// ignore_for_file: unintended_html_in_doc_comment
// ignore_for_file: unnecessary_cast
// ignore_for_file: unnecessary_non_null_assertion
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: unused_element
// ignore_for_file: unused_field
// ignore_for_file: unused_import
// ignore_for_file: unused_local_variable
// ignore_for_file: unused_shown_name
// ignore_for_file: use_super_parameters

import 'dart:core' as core$_;
import 'dart:core' show Object, String, bool, double, int;

import 'package:jni/_internal.dart' as jni$_;
import 'package:jni/jni.dart' as jni$_;

/// from: `android.os.Looper`
class Looper extends jni$_.JObject {
  @jni$_.internal
  @core$_.override
  final jni$_.JType<Looper> $type;

  @jni$_.internal
  Looper.fromReference(jni$_.JReference reference)
    : $type = type,
      super.fromReference(reference);

  static final _class = jni$_.JClass.forName(r'android/os/Looper');

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<Looper?> nullableType = $Looper$NullableType$();

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<Looper> type = $Looper$Type$();
  static final _id_dump = _class.instanceMethodId(
    r'dump',
    r'(Landroid/util/Printer;Ljava/lang/String;)V',
  );

  static final _dump =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (jni$_.Pointer<jni$_.Void>, jni$_.Pointer<jni$_.Void>)
                >,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void dump(android.util.Printer printer, java.lang.String string)`
  void dump(jni$_.JObject printer, jni$_.JString string) {
    final _$printer = printer.reference;
    final _$string = string.reference;
    _dump(
      reference.pointer,
      _id_dump as jni$_.JMethodIDPtr,
      _$printer.pointer,
      _$string.pointer,
    ).check();
  }

  static final _id_getMainLooper = _class.staticMethodId(
    r'getMainLooper',
    r'()Landroid/os/Looper;',
  );

  static final _getMainLooper =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallStaticObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `static public android.os.Looper getMainLooper()`
  /// The returned object must be released after use, by calling the [release] method.
  static Looper? getMainLooper() {
    return _getMainLooper(
      _class.reference.pointer,
      _id_getMainLooper as jni$_.JMethodIDPtr,
    ).object<Looper?>(const $Looper$NullableType$());
  }

  static final _id_getQueue = _class.instanceMethodId(
    r'getQueue',
    r'()Landroid/os/MessageQueue;',
  );

  static final _getQueue =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public android.os.MessageQueue getQueue()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JObject getQueue() {
    return _getQueue(
      reference.pointer,
      _id_getQueue as jni$_.JMethodIDPtr,
    ).object<jni$_.JObject>(const jni$_.$JObject$Type$());
  }

  static final _id_getThread = _class.instanceMethodId(
    r'getThread',
    r'()Ljava/lang/Thread;',
  );

  static final _getThread =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public java.lang.Thread getThread()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JObject getThread() {
    return _getThread(
      reference.pointer,
      _id_getThread as jni$_.JMethodIDPtr,
    ).object<jni$_.JObject>(const jni$_.$JObject$Type$());
  }

  static final _id_isCurrentThread = _class.instanceMethodId(
    r'isCurrentThread',
    r'()Z',
  );

  static final _isCurrentThread =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallBooleanMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public boolean isCurrentThread()`
  bool isCurrentThread() {
    return _isCurrentThread(
      reference.pointer,
      _id_isCurrentThread as jni$_.JMethodIDPtr,
    ).boolean;
  }

  static final _id_loop = _class.staticMethodId(r'loop', r'()V');

  static final _loop =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallStaticVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `static public void loop()`
  static void loop() {
    _loop(_class.reference.pointer, _id_loop as jni$_.JMethodIDPtr).check();
  }

  static final _id_myLooper = _class.staticMethodId(
    r'myLooper',
    r'()Landroid/os/Looper;',
  );

  static final _myLooper =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallStaticObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `static public android.os.Looper myLooper()`
  /// The returned object must be released after use, by calling the [release] method.
  static Looper? myLooper() {
    return _myLooper(
      _class.reference.pointer,
      _id_myLooper as jni$_.JMethodIDPtr,
    ).object<Looper?>(const $Looper$NullableType$());
  }

  static final _id_myQueue = _class.staticMethodId(
    r'myQueue',
    r'()Landroid/os/MessageQueue;',
  );

  static final _myQueue =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallStaticObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `static public android.os.MessageQueue myQueue()`
  /// The returned object must be released after use, by calling the [release] method.
  static jni$_.JObject myQueue() {
    return _myQueue(
      _class.reference.pointer,
      _id_myQueue as jni$_.JMethodIDPtr,
    ).object<jni$_.JObject>(const jni$_.$JObject$Type$());
  }

  static final _id_prepare = _class.staticMethodId(r'prepare', r'()V');

  static final _prepare =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallStaticVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `static public void prepare()`
  static void prepare() {
    _prepare(
      _class.reference.pointer,
      _id_prepare as jni$_.JMethodIDPtr,
    ).check();
  }

  static final _id_prepareMainLooper = _class.staticMethodId(
    r'prepareMainLooper',
    r'()V',
  );

  static final _prepareMainLooper =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallStaticVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `static public void prepareMainLooper()`
  static void prepareMainLooper() {
    _prepareMainLooper(
      _class.reference.pointer,
      _id_prepareMainLooper as jni$_.JMethodIDPtr,
    ).check();
  }

  static final _id_quit = _class.instanceMethodId(r'quit', r'()V');

  static final _quit =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public void quit()`
  void quit() {
    _quit(reference.pointer, _id_quit as jni$_.JMethodIDPtr).check();
  }

  static final _id_quitSafely = _class.instanceMethodId(r'quitSafely', r'()V');

  static final _quitSafely =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public void quitSafely()`
  void quitSafely() {
    _quitSafely(
      reference.pointer,
      _id_quitSafely as jni$_.JMethodIDPtr,
    ).check();
  }

  static final _id_setMessageLogging = _class.instanceMethodId(
    r'setMessageLogging',
    r'(Landroid/util/Printer;)V',
  );

  static final _setMessageLogging =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void setMessageLogging(android.util.Printer printer)`
  void setMessageLogging(jni$_.JObject? printer) {
    final _$printer = printer?.reference ?? jni$_.jNullReference;
    _setMessageLogging(
      reference.pointer,
      _id_setMessageLogging as jni$_.JMethodIDPtr,
      _$printer.pointer,
    ).check();
  }

  static final _id_toString$1 = _class.instanceMethodId(
    r'toString',
    r'()Ljava/lang/String;',
  );

  static final _toString$1 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public java.lang.String toString()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JString? toString$1() {
    return _toString$1(
      reference.pointer,
      _id_toString$1 as jni$_.JMethodIDPtr,
    ).object<jni$_.JString?>(const jni$_.$JString$NullableType$());
  }
}

final class $Looper$NullableType$ extends jni$_.JType<Looper?> {
  @jni$_.internal
  const $Looper$NullableType$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Landroid/os/Looper;';

  @jni$_.internal
  @core$_.override
  Looper? fromReference(jni$_.JReference reference) =>
      reference.isNull ? null : Looper.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$NullableType$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<Looper?> get nullableType => this;

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($Looper$NullableType$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($Looper$NullableType$) &&
        other is $Looper$NullableType$;
  }
}

final class $Looper$Type$ extends jni$_.JType<Looper> {
  @jni$_.internal
  const $Looper$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Landroid/os/Looper;';

  @jni$_.internal
  @core$_.override
  Looper fromReference(jni$_.JReference reference) =>
      Looper.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$NullableType$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<Looper?> get nullableType => const $Looper$NullableType$();

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($Looper$Type$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($Looper$Type$) && other is $Looper$Type$;
  }
}
