// AUTO GENERATED BY JNIGEN 1.0.0. DO NOT EDIT!

// ignore_for_file: annotate_overrides
// ignore_for_file: argument_type_not_assignable
// ignore_for_file: camel_case_extensions
// ignore_for_file: camel_case_types
// ignore_for_file: constant_identifier_names
// ignore_for_file: comment_references
// ignore_for_file: doc_directive_unknown
// ignore_for_file: file_names
// ignore_for_file: inference_failure_on_untyped_parameter
// ignore_for_file: invalid_internal_annotation
// ignore_for_file: invalid_use_of_internal_member
// ignore_for_file: library_prefixes
// ignore_for_file: lines_longer_than_80_chars
// ignore_for_file: no_leading_underscores_for_library_prefixes
// ignore_for_file: no_leading_underscores_for_local_identifiers
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: only_throw_errors
// ignore_for_file: overridden_fields
// ignore_for_file: prefer_double_quotes
// ignore_for_file: unintended_html_in_doc_comment
// ignore_for_file: unnecessary_cast
// ignore_for_file: unnecessary_non_null_assertion
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: unused_element
// ignore_for_file: unused_field
// ignore_for_file: unused_import
// ignore_for_file: unused_local_variable
// ignore_for_file: unused_shown_name
// ignore_for_file: use_super_parameters

import 'dart:core' as core$_;
import 'dart:core' show Object, String;

import 'package:jni/_internal.dart' as jni$_;
import 'package:jni/jni.dart' as jni$_;

import 'UserHandle.dart' as userhandle$_;

/// from: `android.os.Process`
extension type Process._(jni$_.JObject _$this) implements jni$_.JObject {
  static final _class = jni$_.JClass.forName(r'android/os/Process');

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<Process> type = $Process$Type$();

  /// from: `static public final int BLUETOOTH_UID`
  static const BLUETOOTH_UID = 1002;

  /// from: `static public final int FIRST_APPLICATION_UID`
  static const FIRST_APPLICATION_UID = 10000;

  /// from: `static public final int INVALID_PID`
  static const INVALID_PID = -1;

  /// from: `static public final int INVALID_UID`
  static const INVALID_UID = -1;

  /// from: `static public final int LAST_APPLICATION_UID`
  static const LAST_APPLICATION_UID = 19999;

  /// from: `static public final int PHONE_UID`
  static const PHONE_UID = 1001;

  /// from: `static public final int ROOT_UID`
  static const ROOT_UID = 0;

  /// from: `static public final int SHELL_UID`
  static const SHELL_UID = 2000;

  /// from: `static public final int SIGNAL_KILL`
  static const SIGNAL_KILL = 9;

  /// from: `static public final int SIGNAL_QUIT`
  static const SIGNAL_QUIT = 3;

  /// from: `static public final int SIGNAL_USR1`
  static const SIGNAL_USR1 = 10;

  /// from: `static public final int SYSTEM_UID`
  static const SYSTEM_UID = 1000;

  /// from: `static public final int THREAD_PRIORITY_AUDIO`
  static const THREAD_PRIORITY_AUDIO = -16;

  /// from: `static public final int THREAD_PRIORITY_BACKGROUND`
  static const THREAD_PRIORITY_BACKGROUND = 10;

  /// from: `static public final int THREAD_PRIORITY_DEFAULT`
  static const THREAD_PRIORITY_DEFAULT = 0;

  /// from: `static public final int THREAD_PRIORITY_DISPLAY`
  static const THREAD_PRIORITY_DISPLAY = -4;

  /// from: `static public final int THREAD_PRIORITY_FOREGROUND`
  static const THREAD_PRIORITY_FOREGROUND = -2;

  /// from: `static public final int THREAD_PRIORITY_LESS_FAVORABLE`
  static const THREAD_PRIORITY_LESS_FAVORABLE = 1;

  /// from: `static public final int THREAD_PRIORITY_LOWEST`
  static const THREAD_PRIORITY_LOWEST = 19;

  /// from: `static public final int THREAD_PRIORITY_MORE_FAVORABLE`
  static const THREAD_PRIORITY_MORE_FAVORABLE = -1;

  /// from: `static public final int THREAD_PRIORITY_URGENT_AUDIO`
  static const THREAD_PRIORITY_URGENT_AUDIO = -19;

  /// from: `static public final int THREAD_PRIORITY_URGENT_DISPLAY`
  static const THREAD_PRIORITY_URGENT_DISPLAY = -8;

  /// from: `static public final int THREAD_PRIORITY_VIDEO`
  static const THREAD_PRIORITY_VIDEO = -10;

  /// from: `static public final int WIFI_UID`
  static const WIFI_UID = 1010;
  static final _id_new$ = _class.constructorId(r'()V');

  static final _new$ =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public void <init>()`
  /// The returned object must be released after use, by calling the [release] method.
  factory Process() {
    final _$$classRef = _class.reference;
    return _new$(_$$classRef.pointer, _id_new$.pointer).object<Process>();
  }

  static final _id_getAppUidForSdkSandboxUid = _class.staticMethodId(
    r'getAppUidForSdkSandboxUid',
    r'(I)I',
  );

  static final _getAppUidForSdkSandboxUid =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Int32,)>,
              )
            >
          >('globalEnv_CallStaticIntMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              core$_.int,
            )
          >();

  /// from: `static public final int getAppUidForSdkSandboxUid(int i)`
  static core$_.int getAppUidForSdkSandboxUid(core$_.int i) {
    final _$$classRef = _class.reference;
    return _getAppUidForSdkSandboxUid(
      _$$classRef.pointer,
      _id_getAppUidForSdkSandboxUid.pointer,
      i,
    ).integer;
  }

  static final _id_get$elapsedCpuTime = _class.staticMethodId(
    r'getElapsedCpuTime',
    r'()J',
  );

  static final _get$elapsedCpuTime =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallStaticLongMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `static public native final long getElapsedCpuTime()`
  static core$_.int get elapsedCpuTime {
    final _$$classRef = _class.reference;
    return _get$elapsedCpuTime(
      _$$classRef.pointer,
      _id_get$elapsedCpuTime.pointer,
    ).long;
  }

  static final _id_get$exclusiveCores = _class.staticMethodId(
    r'getExclusiveCores',
    r'()[I',
  );

  static final _get$exclusiveCores =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallStaticObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `static public native final int[] getExclusiveCores()`
  /// The returned object must be released after use, by calling the [release] method.
  static jni$_.JIntArray? get exclusiveCores {
    final _$$classRef = _class.reference;
    return _get$exclusiveCores(
      _$$classRef.pointer,
      _id_get$exclusiveCores.pointer,
    ).object<jni$_.JIntArray?>();
  }

  static final _id_getGidForName = _class.staticMethodId(
    r'getGidForName',
    r'(Ljava/lang/String;)I',
  );

  static final _getGidForName =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallStaticIntMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `static public native final int getGidForName(java.lang.String string)`
  static core$_.int getGidForName(jni$_.JString? string) {
    final _$$classRef = _class.reference;
    final _$string = string?.reference ?? jni$_.jNullReference;
    return _getGidForName(
      _$$classRef.pointer,
      _id_getGidForName.pointer,
      _$string.pointer,
    ).integer;
  }

  static final _id_getSdkSandboxUidForAppUid = _class.staticMethodId(
    r'getSdkSandboxUidForAppUid',
    r'(I)I',
  );

  static final _getSdkSandboxUidForAppUid =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Int32,)>,
              )
            >
          >('globalEnv_CallStaticIntMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              core$_.int,
            )
          >();

  /// from: `static public final int getSdkSandboxUidForAppUid(int i)`
  static core$_.int getSdkSandboxUidForAppUid(core$_.int i) {
    final _$$classRef = _class.reference;
    return _getSdkSandboxUidForAppUid(
      _$$classRef.pointer,
      _id_getSdkSandboxUidForAppUid.pointer,
      i,
    ).integer;
  }

  static final _id_get$startElapsedRealtime = _class.staticMethodId(
    r'getStartElapsedRealtime',
    r'()J',
  );

  static final _get$startElapsedRealtime =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallStaticLongMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `static public long getStartElapsedRealtime()`
  static core$_.int get startElapsedRealtime {
    final _$$classRef = _class.reference;
    return _get$startElapsedRealtime(
      _$$classRef.pointer,
      _id_get$startElapsedRealtime.pointer,
    ).long;
  }

  static final _id_get$startRequestedElapsedRealtime = _class.staticMethodId(
    r'getStartRequestedElapsedRealtime',
    r'()J',
  );

  static final _get$startRequestedElapsedRealtime =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallStaticLongMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `static public long getStartRequestedElapsedRealtime()`
  static core$_.int get startRequestedElapsedRealtime {
    final _$$classRef = _class.reference;
    return _get$startRequestedElapsedRealtime(
      _$$classRef.pointer,
      _id_get$startRequestedElapsedRealtime.pointer,
    ).long;
  }

  static final _id_get$startRequestedUptimeMillis = _class.staticMethodId(
    r'getStartRequestedUptimeMillis',
    r'()J',
  );

  static final _get$startRequestedUptimeMillis =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallStaticLongMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `static public long getStartRequestedUptimeMillis()`
  static core$_.int get startRequestedUptimeMillis {
    final _$$classRef = _class.reference;
    return _get$startRequestedUptimeMillis(
      _$$classRef.pointer,
      _id_get$startRequestedUptimeMillis.pointer,
    ).long;
  }

  static final _id_get$startUptimeMillis = _class.staticMethodId(
    r'getStartUptimeMillis',
    r'()J',
  );

  static final _get$startUptimeMillis =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallStaticLongMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `static public long getStartUptimeMillis()`
  static core$_.int get startUptimeMillis {
    final _$$classRef = _class.reference;
    return _get$startUptimeMillis(
      _$$classRef.pointer,
      _id_get$startUptimeMillis.pointer,
    ).long;
  }

  static final _id_getThreadPriority = _class.staticMethodId(
    r'getThreadPriority',
    r'(I)I',
  );

  static final _getThreadPriority =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Int32,)>,
              )
            >
          >('globalEnv_CallStaticIntMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              core$_.int,
            )
          >();

  /// from: `static public native final int getThreadPriority(int i)`
  static core$_.int getThreadPriority(core$_.int i) {
    final _$$classRef = _class.reference;
    return _getThreadPriority(
      _$$classRef.pointer,
      _id_getThreadPriority.pointer,
      i,
    ).integer;
  }

  static final _id_getUidForName = _class.staticMethodId(
    r'getUidForName',
    r'(Ljava/lang/String;)I',
  );

  static final _getUidForName =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallStaticIntMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `static public native final int getUidForName(java.lang.String string)`
  static core$_.int getUidForName(jni$_.JString? string) {
    final _$$classRef = _class.reference;
    final _$string = string?.reference ?? jni$_.jNullReference;
    return _getUidForName(
      _$$classRef.pointer,
      _id_getUidForName.pointer,
      _$string.pointer,
    ).integer;
  }

  static final _id_is64Bit = _class.staticMethodId(r'is64Bit', r'()Z');

  static final _is64Bit =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallStaticBooleanMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `static public final boolean is64Bit()`
  static core$_.bool is64Bit() {
    final _$$classRef = _class.reference;
    return _is64Bit(_$$classRef.pointer, _id_is64Bit.pointer).boolean;
  }

  static final _id_isApplicationUid = _class.staticMethodId(
    r'isApplicationUid',
    r'(I)Z',
  );

  static final _isApplicationUid =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Int32,)>,
              )
            >
          >('globalEnv_CallStaticBooleanMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              core$_.int,
            )
          >();

  /// from: `static public boolean isApplicationUid(int i)`
  static core$_.bool isApplicationUid(core$_.int i) {
    final _$$classRef = _class.reference;
    return _isApplicationUid(
      _$$classRef.pointer,
      _id_isApplicationUid.pointer,
      i,
    ).boolean;
  }

  static final _id_get$isIsolated = _class.staticMethodId(
    r'isIsolated',
    r'()Z',
  );

  static final _get$isIsolated =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallStaticBooleanMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `static public final boolean isIsolated()`
  static core$_.bool get isIsolated {
    final _$$classRef = _class.reference;
    return _get$isIsolated(
      _$$classRef.pointer,
      _id_get$isIsolated.pointer,
    ).boolean;
  }

  static final _id_isIsolatedUid = _class.staticMethodId(
    r'isIsolatedUid',
    r'(I)Z',
  );

  static final _isIsolatedUid =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Int32,)>,
              )
            >
          >('globalEnv_CallStaticBooleanMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              core$_.int,
            )
          >();

  /// from: `static public final boolean isIsolatedUid(int i)`
  static core$_.bool isIsolatedUid(core$_.int i) {
    final _$$classRef = _class.reference;
    return _isIsolatedUid(
      _$$classRef.pointer,
      _id_isIsolatedUid.pointer,
      i,
    ).boolean;
  }

  static final _id_get$isSdkSandbox = _class.staticMethodId(
    r'isSdkSandbox',
    r'()Z',
  );

  static final _get$isSdkSandbox =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallStaticBooleanMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `static public final boolean isSdkSandbox()`
  static core$_.bool get isSdkSandbox {
    final _$$classRef = _class.reference;
    return _get$isSdkSandbox(
      _$$classRef.pointer,
      _id_get$isSdkSandbox.pointer,
    ).boolean;
  }

  static final _id_isSdkSandboxUid = _class.staticMethodId(
    r'isSdkSandboxUid',
    r'(I)Z',
  );

  static final _isSdkSandboxUid =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Int32,)>,
              )
            >
          >('globalEnv_CallStaticBooleanMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              core$_.int,
            )
          >();

  /// from: `static public final boolean isSdkSandboxUid(int i)`
  static core$_.bool isSdkSandboxUid(core$_.int i) {
    final _$$classRef = _class.reference;
    return _isSdkSandboxUid(
      _$$classRef.pointer,
      _id_isSdkSandboxUid.pointer,
      i,
    ).boolean;
  }

  static final _id_killProcess = _class.staticMethodId(r'killProcess', r'(I)V');

  static final _killProcess =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Int32,)>,
              )
            >
          >('globalEnv_CallStaticVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              core$_.int,
            )
          >();

  /// from: `static public final void killProcess(int i)`
  static void killProcess(core$_.int i) {
    final _$$classRef = _class.reference;
    _killProcess(_$$classRef.pointer, _id_killProcess.pointer, i).check();
  }

  static final _id_myPid = _class.staticMethodId(r'myPid', r'()I');

  static final _myPid =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallStaticIntMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `static public final int myPid()`
  static core$_.int myPid() {
    final _$$classRef = _class.reference;
    return _myPid(_$$classRef.pointer, _id_myPid.pointer).integer;
  }

  static final _id_myProcessName = _class.staticMethodId(
    r'myProcessName',
    r'()Ljava/lang/String;',
  );

  static final _myProcessName =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallStaticObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `static public java.lang.String myProcessName()`
  /// The returned object must be released after use, by calling the [release] method.
  static jni$_.JString myProcessName() {
    final _$$classRef = _class.reference;
    return _myProcessName(
      _$$classRef.pointer,
      _id_myProcessName.pointer,
    ).object<jni$_.JString>();
  }

  static final _id_myTid = _class.staticMethodId(r'myTid', r'()I');

  static final _myTid =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallStaticIntMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `static public final int myTid()`
  static core$_.int myTid() {
    final _$$classRef = _class.reference;
    return _myTid(_$$classRef.pointer, _id_myTid.pointer).integer;
  }

  static final _id_myUid = _class.staticMethodId(r'myUid', r'()I');

  static final _myUid =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallStaticIntMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `static public final int myUid()`
  static core$_.int myUid() {
    final _$$classRef = _class.reference;
    return _myUid(_$$classRef.pointer, _id_myUid.pointer).integer;
  }

  static final _id_myUserHandle = _class.staticMethodId(
    r'myUserHandle',
    r'()Landroid/os/UserHandle;',
  );

  static final _myUserHandle =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallStaticObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `static public android.os.UserHandle myUserHandle()`
  /// The returned object must be released after use, by calling the [release] method.
  static userhandle$_.UserHandle? myUserHandle() {
    final _$$classRef = _class.reference;
    return _myUserHandle(
      _$$classRef.pointer,
      _id_myUserHandle.pointer,
    ).object<userhandle$_.UserHandle?>();
  }

  static final _id_sendSignal = _class.staticMethodId(r'sendSignal', r'(II)V');

  static final _sendSignal =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Int32, jni$_.Int32)>,
              )
            >
          >('globalEnv_CallStaticVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              core$_.int,
              core$_.int,
            )
          >();

  /// from: `static public native final void sendSignal(int i, int i1)`
  static void sendSignal(core$_.int i, core$_.int i1) {
    final _$$classRef = _class.reference;
    _sendSignal(_$$classRef.pointer, _id_sendSignal.pointer, i, i1).check();
  }

  static final _id_set$threadPriority = _class.staticMethodId(
    r'setThreadPriority',
    r'(I)V',
  );

  static final _set$threadPriority =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Int32,)>,
              )
            >
          >('globalEnv_CallStaticVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              core$_.int,
            )
          >();

  /// from: `static public native final void setThreadPriority(int i)`
  static set threadPriority(core$_.int i) {
    final _$$classRef = _class.reference;
    _set$threadPriority(
      _$$classRef.pointer,
      _id_set$threadPriority.pointer,
      i,
    ).check();
  }

  static final _id_setThreadPriority = _class.staticMethodId(
    r'setThreadPriority',
    r'(II)V',
  );

  static final _setThreadPriority =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Int32, jni$_.Int32)>,
              )
            >
          >('globalEnv_CallStaticVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              core$_.int,
              core$_.int,
            )
          >();

  /// from: `static public native final void setThreadPriority(int i, int i1)`
  static void setThreadPriority(core$_.int i, core$_.int i1) {
    final _$$classRef = _class.reference;
    _setThreadPriority(
      _$$classRef.pointer,
      _id_setThreadPriority.pointer,
      i,
      i1,
    ).check();
  }

  static final _id_supportsProcesses = _class.staticMethodId(
    r'supportsProcesses',
    r'()Z',
  );

  static final _supportsProcesses =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallStaticBooleanMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `static public final boolean supportsProcesses()`
  @core$_.Deprecated('This Java method is deprecated.')
  static core$_.bool supportsProcesses() {
    final _$$classRef = _class.reference;
    return _supportsProcesses(
      _$$classRef.pointer,
      _id_supportsProcesses.pointer,
    ).boolean;
  }
}

final class $Process$Type$ extends jni$_.JType<Process> {
  @jni$_.internal
  const $Process$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Landroid/os/Process;';
}
