// AUTO GENERATED BY JNIGEN 0.16.0. DO NOT EDIT!

// ignore_for_file: annotate_overrides
// ignore_for_file: argument_type_not_assignable
// ignore_for_file: camel_case_extensions
// ignore_for_file: camel_case_types
// ignore_for_file: constant_identifier_names
// ignore_for_file: comment_references
// ignore_for_file: doc_directive_unknown
// ignore_for_file: file_names
// ignore_for_file: inference_failure_on_untyped_parameter
// ignore_for_file: invalid_internal_annotation
// ignore_for_file: invalid_use_of_internal_member
// ignore_for_file: library_prefixes
// ignore_for_file: lines_longer_than_80_chars
// ignore_for_file: no_leading_underscores_for_library_prefixes
// ignore_for_file: no_leading_underscores_for_local_identifiers
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: only_throw_errors
// ignore_for_file: overridden_fields
// ignore_for_file: prefer_double_quotes
// ignore_for_file: unintended_html_in_doc_comment
// ignore_for_file: unnecessary_cast
// ignore_for_file: unnecessary_non_null_assertion
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: unused_element
// ignore_for_file: unused_field
// ignore_for_file: unused_import
// ignore_for_file: unused_local_variable
// ignore_for_file: unused_shown_name
// ignore_for_file: use_super_parameters

import 'dart:core' as core$_;
import 'dart:core' show Object, String;

import 'package:jni/_internal.dart' as jni$_;
import 'package:jni/jni.dart' as jni$_;

import 'Collection.dart' as collection$_;

/// from: `java.util.AbstractMap$SimpleEntry`
extension type AbstractMap$SimpleEntry<
  $K extends jni$_.JObject?,
  $V extends jni$_.JObject?
>._(jni$_.JObject _$this)
    implements jni$_.JObject {
  static final _class = jni$_.JClass.forName(
    r'java/util/AbstractMap$SimpleEntry',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<AbstractMap$SimpleEntry> type =
      $AbstractMap$SimpleEntry$Type$();
  static final _id_new$ = _class.constructorId(r'(Ljava/util/Map$Entry;)V');

  static final _new$ =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void <init>(java.util.Map$Entry<? extends K, ? extends V> entry)`
  /// The returned object must be released after use, by calling the [release] method.
  factory AbstractMap$SimpleEntry(jni$_.JObject? entry) {
    final _$entry = entry?.reference ?? jni$_.jNullReference;
    return _new$(
      _class.reference.pointer,
      _id_new$.pointer,
      _$entry.pointer,
    ).object<AbstractMap$SimpleEntry<$K, $V>>();
  }

  static final _id_new$1 = _class.constructorId(
    r'(Ljava/lang/Object;Ljava/lang/Object;)V',
  );

  static final _new$1 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (jni$_.Pointer<jni$_.Void>, jni$_.Pointer<jni$_.Void>)
                >,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void <init>(K object, V object1)`
  /// The returned object must be released after use, by calling the [release] method.
  factory AbstractMap$SimpleEntry.new$1($K? object, $V? object1) {
    final _$object = object?.reference ?? jni$_.jNullReference;
    final _$object1 = object1?.reference ?? jni$_.jNullReference;
    return _new$1(
      _class.reference.pointer,
      _id_new$1.pointer,
      _$object.pointer,
      _$object1.pointer,
    ).object<AbstractMap$SimpleEntry<$K, $V>>();
  }
}

extension AbstractMap$SimpleEntry$$Methods<
  $K extends jni$_.JObject?,
  $V extends jni$_.JObject?
>
    on AbstractMap$SimpleEntry<$K, $V> {
  static final _id_equals = AbstractMap$SimpleEntry._class.instanceMethodId(
    r'equals',
    r'(Ljava/lang/Object;)Z',
  );

  static final _equals =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallBooleanMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public boolean equals(java.lang.Object object)`
  core$_.bool equals(jni$_.JObject? object) {
    final _$object = object?.reference ?? jni$_.jNullReference;
    return _equals(
      reference.pointer,
      _id_equals.pointer,
      _$object.pointer,
    ).boolean;
  }

  static final _id_get$key = AbstractMap$SimpleEntry._class.instanceMethodId(
    r'getKey',
    r'()Ljava/lang/Object;',
  );

  static final _get$key =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public K getKey()`
  /// The returned object must be released after use, by calling the [release] method.
  $K? get key {
    return _get$key(reference.pointer, _id_get$key.pointer).object<$K?>();
  }

  static final _id_get$value = AbstractMap$SimpleEntry._class.instanceMethodId(
    r'getValue',
    r'()Ljava/lang/Object;',
  );

  static final _get$value =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public V getValue()`
  /// The returned object must be released after use, by calling the [release] method.
  $V? get value {
    return _get$value(reference.pointer, _id_get$value.pointer).object<$V?>();
  }

  static final _id_hashCode$1 = AbstractMap$SimpleEntry._class.instanceMethodId(
    r'hashCode',
    r'()I',
  );

  static final _hashCode$1 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallIntMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public int hashCode()`
  core$_.int hashCode$1() {
    return _hashCode$1(reference.pointer, _id_hashCode$1.pointer).integer;
  }

  static final _id_setValue = AbstractMap$SimpleEntry._class.instanceMethodId(
    r'setValue',
    r'(Ljava/lang/Object;)Ljava/lang/Object;',
  );

  static final _setValue =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public V setValue(V object)`
  /// The returned object must be released after use, by calling the [release] method.
  $V? setValue($V? object) {
    final _$object = object?.reference ?? jni$_.jNullReference;
    return _setValue(
      reference.pointer,
      _id_setValue.pointer,
      _$object.pointer,
    ).object<$V?>();
  }

  static final _id_toString$1 = AbstractMap$SimpleEntry._class.instanceMethodId(
    r'toString',
    r'()Ljava/lang/String;',
  );

  static final _toString$1 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public java.lang.String toString()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JString? toString$1() {
    return _toString$1(
      reference.pointer,
      _id_toString$1.pointer,
    ).object<jni$_.JString?>();
  }
}

final class $AbstractMap$SimpleEntry$Type$
    extends jni$_.JType<AbstractMap$SimpleEntry> {
  @jni$_.internal
  const $AbstractMap$SimpleEntry$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Ljava/util/AbstractMap$SimpleEntry;';
}

/// from: `java.util.AbstractMap$SimpleImmutableEntry`
extension type AbstractMap$SimpleImmutableEntry<
  $K extends jni$_.JObject?,
  $V extends jni$_.JObject?
>._(jni$_.JObject _$this)
    implements jni$_.JObject {
  static final _class = jni$_.JClass.forName(
    r'java/util/AbstractMap$SimpleImmutableEntry',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<AbstractMap$SimpleImmutableEntry> type =
      $AbstractMap$SimpleImmutableEntry$Type$();
  static final _id_new$ = _class.constructorId(r'(Ljava/util/Map$Entry;)V');

  static final _new$ =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void <init>(java.util.Map$Entry<? extends K, ? extends V> entry)`
  /// The returned object must be released after use, by calling the [release] method.
  factory AbstractMap$SimpleImmutableEntry(jni$_.JObject? entry) {
    final _$entry = entry?.reference ?? jni$_.jNullReference;
    return _new$(
      _class.reference.pointer,
      _id_new$.pointer,
      _$entry.pointer,
    ).object<AbstractMap$SimpleImmutableEntry<$K, $V>>();
  }

  static final _id_new$1 = _class.constructorId(
    r'(Ljava/lang/Object;Ljava/lang/Object;)V',
  );

  static final _new$1 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (jni$_.Pointer<jni$_.Void>, jni$_.Pointer<jni$_.Void>)
                >,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void <init>(K object, V object1)`
  /// The returned object must be released after use, by calling the [release] method.
  factory AbstractMap$SimpleImmutableEntry.new$1($K? object, $V? object1) {
    final _$object = object?.reference ?? jni$_.jNullReference;
    final _$object1 = object1?.reference ?? jni$_.jNullReference;
    return _new$1(
      _class.reference.pointer,
      _id_new$1.pointer,
      _$object.pointer,
      _$object1.pointer,
    ).object<AbstractMap$SimpleImmutableEntry<$K, $V>>();
  }
}

extension AbstractMap$SimpleImmutableEntry$$Methods<
  $K extends jni$_.JObject?,
  $V extends jni$_.JObject?
>
    on AbstractMap$SimpleImmutableEntry<$K, $V> {
  static final _id_equals = AbstractMap$SimpleImmutableEntry._class
      .instanceMethodId(r'equals', r'(Ljava/lang/Object;)Z');

  static final _equals =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallBooleanMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public boolean equals(java.lang.Object object)`
  core$_.bool equals(jni$_.JObject? object) {
    final _$object = object?.reference ?? jni$_.jNullReference;
    return _equals(
      reference.pointer,
      _id_equals.pointer,
      _$object.pointer,
    ).boolean;
  }

  static final _id_get$key = AbstractMap$SimpleImmutableEntry._class
      .instanceMethodId(r'getKey', r'()Ljava/lang/Object;');

  static final _get$key =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public K getKey()`
  /// The returned object must be released after use, by calling the [release] method.
  $K? get key {
    return _get$key(reference.pointer, _id_get$key.pointer).object<$K?>();
  }

  static final _id_get$value = AbstractMap$SimpleImmutableEntry._class
      .instanceMethodId(r'getValue', r'()Ljava/lang/Object;');

  static final _get$value =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public V getValue()`
  /// The returned object must be released after use, by calling the [release] method.
  $V? get value {
    return _get$value(reference.pointer, _id_get$value.pointer).object<$V?>();
  }

  static final _id_hashCode$1 = AbstractMap$SimpleImmutableEntry._class
      .instanceMethodId(r'hashCode', r'()I');

  static final _hashCode$1 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallIntMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public int hashCode()`
  core$_.int hashCode$1() {
    return _hashCode$1(reference.pointer, _id_hashCode$1.pointer).integer;
  }

  static final _id_setValue = AbstractMap$SimpleImmutableEntry._class
      .instanceMethodId(r'setValue', r'(Ljava/lang/Object;)Ljava/lang/Object;');

  static final _setValue =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public V setValue(V object)`
  /// The returned object must be released after use, by calling the [release] method.
  $V? setValue($V? object) {
    final _$object = object?.reference ?? jni$_.jNullReference;
    return _setValue(
      reference.pointer,
      _id_setValue.pointer,
      _$object.pointer,
    ).object<$V?>();
  }

  static final _id_toString$1 = AbstractMap$SimpleImmutableEntry._class
      .instanceMethodId(r'toString', r'()Ljava/lang/String;');

  static final _toString$1 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public java.lang.String toString()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JString? toString$1() {
    return _toString$1(
      reference.pointer,
      _id_toString$1.pointer,
    ).object<jni$_.JString?>();
  }
}

final class $AbstractMap$SimpleImmutableEntry$Type$
    extends jni$_.JType<AbstractMap$SimpleImmutableEntry> {
  @jni$_.internal
  const $AbstractMap$SimpleImmutableEntry$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Ljava/util/AbstractMap$SimpleImmutableEntry;';
}

/// from: `java.util.AbstractMap`
extension type AbstractMap<
  $K extends jni$_.JObject?,
  $V extends jni$_.JObject?
>._(jni$_.JObject _$this)
    implements jni$_.JObject, jni$_.JMap<$K?, $V?> {
  static final _class = jni$_.JClass.forName(r'java/util/AbstractMap');

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<AbstractMap> type = $AbstractMap$Type$();
}

extension AbstractMap$$Methods<
  $K extends jni$_.JObject?,
  $V extends jni$_.JObject?
>
    on AbstractMap<$K, $V> {
  static final _id_clear = AbstractMap._class.instanceMethodId(
    r'clear',
    r'()V',
  );

  static final _clear =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public void clear()`
  void clear() {
    _clear(reference.pointer, _id_clear.pointer).check();
  }

  static final _id_containsKey = AbstractMap._class.instanceMethodId(
    r'containsKey',
    r'(Ljava/lang/Object;)Z',
  );

  static final _containsKey =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallBooleanMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public boolean containsKey(java.lang.Object object)`
  core$_.bool containsKey(jni$_.JObject? object) {
    final _$object = object?.reference ?? jni$_.jNullReference;
    return _containsKey(
      reference.pointer,
      _id_containsKey.pointer,
      _$object.pointer,
    ).boolean;
  }

  static final _id_containsValue = AbstractMap._class.instanceMethodId(
    r'containsValue',
    r'(Ljava/lang/Object;)Z',
  );

  static final _containsValue =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallBooleanMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public boolean containsValue(java.lang.Object object)`
  core$_.bool containsValue(jni$_.JObject? object) {
    final _$object = object?.reference ?? jni$_.jNullReference;
    return _containsValue(
      reference.pointer,
      _id_containsValue.pointer,
      _$object.pointer,
    ).boolean;
  }

  static final _id_entrySet = AbstractMap._class.instanceMethodId(
    r'entrySet',
    r'()Ljava/util/Set;',
  );

  static final _entrySet =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public abstract java.util.Set<java.util.Map$Entry<K, V>> entrySet()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JSet<jni$_.JObject?>? entrySet() {
    return _entrySet(
      reference.pointer,
      _id_entrySet.pointer,
    ).object<jni$_.JSet<jni$_.JObject?>?>();
  }

  static final _id_equals = AbstractMap._class.instanceMethodId(
    r'equals',
    r'(Ljava/lang/Object;)Z',
  );

  static final _equals =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallBooleanMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public boolean equals(java.lang.Object object)`
  core$_.bool equals(jni$_.JObject? object) {
    final _$object = object?.reference ?? jni$_.jNullReference;
    return _equals(
      reference.pointer,
      _id_equals.pointer,
      _$object.pointer,
    ).boolean;
  }

  static final _id_get = AbstractMap._class.instanceMethodId(
    r'get',
    r'(Ljava/lang/Object;)Ljava/lang/Object;',
  );

  static final _get =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public V get(java.lang.Object object)`
  /// The returned object must be released after use, by calling the [release] method.
  $V? get(jni$_.JObject? object) {
    final _$object = object?.reference ?? jni$_.jNullReference;
    return _get(
      reference.pointer,
      _id_get.pointer,
      _$object.pointer,
    ).object<$V?>();
  }

  static final _id_hashCode$1 = AbstractMap._class.instanceMethodId(
    r'hashCode',
    r'()I',
  );

  static final _hashCode$1 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallIntMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public int hashCode()`
  core$_.int hashCode$1() {
    return _hashCode$1(reference.pointer, _id_hashCode$1.pointer).integer;
  }

  static final _id_get$isEmpty = AbstractMap._class.instanceMethodId(
    r'isEmpty',
    r'()Z',
  );

  static final _get$isEmpty =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallBooleanMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public boolean isEmpty()`
  core$_.bool get isEmpty {
    return _get$isEmpty(reference.pointer, _id_get$isEmpty.pointer).boolean;
  }

  static final _id_keySet = AbstractMap._class.instanceMethodId(
    r'keySet',
    r'()Ljava/util/Set;',
  );

  static final _keySet =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public java.util.Set<K> keySet()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JSet<$K?>? keySet() {
    return _keySet(
      reference.pointer,
      _id_keySet.pointer,
    ).object<jni$_.JSet<$K?>?>();
  }

  static final _id_put = AbstractMap._class.instanceMethodId(
    r'put',
    r'(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;',
  );

  static final _put =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (jni$_.Pointer<jni$_.Void>, jni$_.Pointer<jni$_.Void>)
                >,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public V put(K object, V object1)`
  /// The returned object must be released after use, by calling the [release] method.
  $V? put($K? object, $V? object1) {
    final _$object = object?.reference ?? jni$_.jNullReference;
    final _$object1 = object1?.reference ?? jni$_.jNullReference;
    return _put(
      reference.pointer,
      _id_put.pointer,
      _$object.pointer,
      _$object1.pointer,
    ).object<$V?>();
  }

  static final _id_putAll = AbstractMap._class.instanceMethodId(
    r'putAll',
    r'(Ljava/util/Map;)V',
  );

  static final _putAll =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void putAll(java.util.Map<? extends K, ? extends V> map)`
  void putAll(jni$_.JMap<$K?, $V?>? map) {
    final _$map = map?.reference ?? jni$_.jNullReference;
    _putAll(reference.pointer, _id_putAll.pointer, _$map.pointer).check();
  }

  static final _id_remove = AbstractMap._class.instanceMethodId(
    r'remove',
    r'(Ljava/lang/Object;)Ljava/lang/Object;',
  );

  static final _remove =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public V remove(java.lang.Object object)`
  /// The returned object must be released after use, by calling the [release] method.
  $V? remove(jni$_.JObject? object) {
    final _$object = object?.reference ?? jni$_.jNullReference;
    return _remove(
      reference.pointer,
      _id_remove.pointer,
      _$object.pointer,
    ).object<$V?>();
  }

  static final _id_size = AbstractMap._class.instanceMethodId(r'size', r'()I');

  static final _size =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallIntMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public int size()`
  core$_.int size() {
    return _size(reference.pointer, _id_size.pointer).integer;
  }

  static final _id_toString$1 = AbstractMap._class.instanceMethodId(
    r'toString',
    r'()Ljava/lang/String;',
  );

  static final _toString$1 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public java.lang.String toString()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JString? toString$1() {
    return _toString$1(
      reference.pointer,
      _id_toString$1.pointer,
    ).object<jni$_.JString?>();
  }

  static final _id_values = AbstractMap._class.instanceMethodId(
    r'values',
    r'()Ljava/util/Collection;',
  );

  static final _values =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public java.util.Collection<V> values()`
  /// The returned object must be released after use, by calling the [release] method.
  collection$_.Collection<$V?>? values() {
    return _values(
      reference.pointer,
      _id_values.pointer,
    ).object<collection$_.Collection<$V?>?>();
  }
}

final class $AbstractMap$Type$ extends jni$_.JType<AbstractMap> {
  @jni$_.internal
  const $AbstractMap$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Ljava/util/AbstractMap;';
}
