// AUTO GENERATED BY JNIGEN 0.16.0. DO NOT EDIT!

// ignore_for_file: annotate_overrides
// ignore_for_file: argument_type_not_assignable
// ignore_for_file: camel_case_extensions
// ignore_for_file: camel_case_types
// ignore_for_file: constant_identifier_names
// ignore_for_file: comment_references
// ignore_for_file: doc_directive_unknown
// ignore_for_file: file_names
// ignore_for_file: inference_failure_on_untyped_parameter
// ignore_for_file: invalid_internal_annotation
// ignore_for_file: invalid_use_of_internal_member
// ignore_for_file: library_prefixes
// ignore_for_file: lines_longer_than_80_chars
// ignore_for_file: no_leading_underscores_for_library_prefixes
// ignore_for_file: no_leading_underscores_for_local_identifiers
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: only_throw_errors
// ignore_for_file: overridden_fields
// ignore_for_file: prefer_double_quotes
// ignore_for_file: unintended_html_in_doc_comment
// ignore_for_file: unnecessary_cast
// ignore_for_file: unnecessary_non_null_assertion
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: unused_element
// ignore_for_file: unused_field
// ignore_for_file: unused_import
// ignore_for_file: unused_local_variable
// ignore_for_file: unused_shown_name
// ignore_for_file: use_super_parameters

import 'dart:core' as core$_;
import 'dart:core' show Object, String;

import 'package:jni/_internal.dart' as jni$_;
import 'package:jni/jni.dart' as jni$_;

/// from: `java.util.BitSet`
extension type BitSet._(jni$_.JObject _$this) implements jni$_.JObject {
  static final _class = jni$_.JClass.forName(r'java/util/BitSet');

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<BitSet> type = $BitSet$Type$();
  static final _id_new$ = _class.constructorId(r'()V');

  static final _new$ =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public void <init>()`
  /// The returned object must be released after use, by calling the [release] method.
  factory BitSet() {
    return _new$(_class.reference.pointer, _id_new$.pointer).object<BitSet>();
  }

  static final _id_new$1 = _class.constructorId(r'(I)V');

  static final _new$1 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Int32,)>,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              core$_.int,
            )
          >();

  /// from: `public void <init>(int i)`
  /// The returned object must be released after use, by calling the [release] method.
  factory BitSet.new$1(core$_.int i) {
    return _new$1(
      _class.reference.pointer,
      _id_new$1.pointer,
      i,
    ).object<BitSet>();
  }

  static final _id_valueOf = _class.staticMethodId(
    r'valueOf',
    r'([B)Ljava/util/BitSet;',
  );

  static final _valueOf =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallStaticObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `static public java.util.BitSet valueOf(byte[] bs)`
  /// The returned object must be released after use, by calling the [release] method.
  static BitSet? valueOf(jni$_.JByteArray? bs) {
    final _$bs = bs?.reference ?? jni$_.jNullReference;
    return _valueOf(
      _class.reference.pointer,
      _id_valueOf.pointer,
      _$bs.pointer,
    ).object<BitSet?>();
  }

  static final _id_valueOf$1 = _class.staticMethodId(
    r'valueOf',
    r'(Ljava/nio/ByteBuffer;)Ljava/util/BitSet;',
  );

  static final _valueOf$1 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallStaticObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `static public java.util.BitSet valueOf(java.nio.ByteBuffer byteBuffer)`
  /// The returned object must be released after use, by calling the [release] method.
  static BitSet? valueOf$1(jni$_.JByteBuffer? byteBuffer) {
    final _$byteBuffer = byteBuffer?.reference ?? jni$_.jNullReference;
    return _valueOf$1(
      _class.reference.pointer,
      _id_valueOf$1.pointer,
      _$byteBuffer.pointer,
    ).object<BitSet?>();
  }

  static final _id_valueOf$2 = _class.staticMethodId(
    r'valueOf',
    r'(Ljava/nio/LongBuffer;)Ljava/util/BitSet;',
  );

  static final _valueOf$2 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallStaticObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `static public java.util.BitSet valueOf(java.nio.LongBuffer longBuffer)`
  /// The returned object must be released after use, by calling the [release] method.
  static BitSet? valueOf$2(jni$_.JObject? longBuffer) {
    final _$longBuffer = longBuffer?.reference ?? jni$_.jNullReference;
    return _valueOf$2(
      _class.reference.pointer,
      _id_valueOf$2.pointer,
      _$longBuffer.pointer,
    ).object<BitSet?>();
  }

  static final _id_valueOf$3 = _class.staticMethodId(
    r'valueOf',
    r'([J)Ljava/util/BitSet;',
  );

  static final _valueOf$3 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallStaticObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `static public java.util.BitSet valueOf(long[] js)`
  /// The returned object must be released after use, by calling the [release] method.
  static BitSet? valueOf$3(jni$_.JLongArray? js) {
    final _$js = js?.reference ?? jni$_.jNullReference;
    return _valueOf$3(
      _class.reference.pointer,
      _id_valueOf$3.pointer,
      _$js.pointer,
    ).object<BitSet?>();
  }
}

extension BitSet$$Methods on BitSet {
  static final _id_and = BitSet._class.instanceMethodId(
    r'and',
    r'(Ljava/util/BitSet;)V',
  );

  static final _and =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void and(java.util.BitSet bitSet)`
  void and(BitSet? bitSet) {
    final _$bitSet = bitSet?.reference ?? jni$_.jNullReference;
    _and(reference.pointer, _id_and.pointer, _$bitSet.pointer).check();
  }

  static final _id_andNot = BitSet._class.instanceMethodId(
    r'andNot',
    r'(Ljava/util/BitSet;)V',
  );

  static final _andNot =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void andNot(java.util.BitSet bitSet)`
  void andNot(BitSet? bitSet) {
    final _$bitSet = bitSet?.reference ?? jni$_.jNullReference;
    _andNot(reference.pointer, _id_andNot.pointer, _$bitSet.pointer).check();
  }

  static final _id_cardinality = BitSet._class.instanceMethodId(
    r'cardinality',
    r'()I',
  );

  static final _cardinality =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallIntMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public int cardinality()`
  core$_.int cardinality() {
    return _cardinality(reference.pointer, _id_cardinality.pointer).integer;
  }

  static final _id_clear = BitSet._class.instanceMethodId(r'clear', r'()V');

  static final _clear =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public void clear()`
  void clear() {
    _clear(reference.pointer, _id_clear.pointer).check();
  }

  static final _id_clear$1 = BitSet._class.instanceMethodId(r'clear', r'(I)V');

  static final _clear$1 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Int32,)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              core$_.int,
            )
          >();

  /// from: `public void clear(int i)`
  void clear$1(core$_.int i) {
    _clear$1(reference.pointer, _id_clear$1.pointer, i).check();
  }

  static final _id_clear$2 = BitSet._class.instanceMethodId(r'clear', r'(II)V');

  static final _clear$2 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Int32, jni$_.Int32)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              core$_.int,
              core$_.int,
            )
          >();

  /// from: `public void clear(int i, int i1)`
  void clear$2(core$_.int i, core$_.int i1) {
    _clear$2(reference.pointer, _id_clear$2.pointer, i, i1).check();
  }

  static final _id_clone = BitSet._class.instanceMethodId(
    r'clone',
    r'()Ljava/lang/Object;',
  );

  static final _clone =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public java.lang.Object clone()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JObject? clone() {
    return _clone(
      reference.pointer,
      _id_clone.pointer,
    ).object<jni$_.JObject?>();
  }

  static final _id_equals = BitSet._class.instanceMethodId(
    r'equals',
    r'(Ljava/lang/Object;)Z',
  );

  static final _equals =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallBooleanMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public boolean equals(java.lang.Object object)`
  core$_.bool equals(jni$_.JObject? object) {
    final _$object = object?.reference ?? jni$_.jNullReference;
    return _equals(
      reference.pointer,
      _id_equals.pointer,
      _$object.pointer,
    ).boolean;
  }

  static final _id_flip = BitSet._class.instanceMethodId(r'flip', r'(I)V');

  static final _flip =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Int32,)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              core$_.int,
            )
          >();

  /// from: `public void flip(int i)`
  void flip(core$_.int i) {
    _flip(reference.pointer, _id_flip.pointer, i).check();
  }

  static final _id_flip$1 = BitSet._class.instanceMethodId(r'flip', r'(II)V');

  static final _flip$1 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Int32, jni$_.Int32)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              core$_.int,
              core$_.int,
            )
          >();

  /// from: `public void flip(int i, int i1)`
  void flip$1(core$_.int i, core$_.int i1) {
    _flip$1(reference.pointer, _id_flip$1.pointer, i, i1).check();
  }

  static final _id_get = BitSet._class.instanceMethodId(r'get', r'(I)Z');

  static final _get =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Int32,)>,
              )
            >
          >('globalEnv_CallBooleanMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              core$_.int,
            )
          >();

  /// from: `public boolean get(int i)`
  core$_.bool get(core$_.int i) {
    return _get(reference.pointer, _id_get.pointer, i).boolean;
  }

  static final _id_get$1 = BitSet._class.instanceMethodId(
    r'get',
    r'(II)Ljava/util/BitSet;',
  );

  static final _get$1 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Int32, jni$_.Int32)>,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              core$_.int,
              core$_.int,
            )
          >();

  /// from: `public java.util.BitSet get(int i, int i1)`
  /// The returned object must be released after use, by calling the [release] method.
  BitSet? get$1(core$_.int i, core$_.int i1) {
    return _get$1(
      reference.pointer,
      _id_get$1.pointer,
      i,
      i1,
    ).object<BitSet?>();
  }

  static final _id_hashCode$1 = BitSet._class.instanceMethodId(
    r'hashCode',
    r'()I',
  );

  static final _hashCode$1 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallIntMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public int hashCode()`
  core$_.int hashCode$1() {
    return _hashCode$1(reference.pointer, _id_hashCode$1.pointer).integer;
  }

  static final _id_intersects = BitSet._class.instanceMethodId(
    r'intersects',
    r'(Ljava/util/BitSet;)Z',
  );

  static final _intersects =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallBooleanMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public boolean intersects(java.util.BitSet bitSet)`
  core$_.bool intersects(BitSet? bitSet) {
    final _$bitSet = bitSet?.reference ?? jni$_.jNullReference;
    return _intersects(
      reference.pointer,
      _id_intersects.pointer,
      _$bitSet.pointer,
    ).boolean;
  }

  static final _id_get$isEmpty = BitSet._class.instanceMethodId(
    r'isEmpty',
    r'()Z',
  );

  static final _get$isEmpty =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallBooleanMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public boolean isEmpty()`
  core$_.bool get isEmpty {
    return _get$isEmpty(reference.pointer, _id_get$isEmpty.pointer).boolean;
  }

  static final _id_length = BitSet._class.instanceMethodId(r'length', r'()I');

  static final _length =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallIntMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public int length()`
  core$_.int length() {
    return _length(reference.pointer, _id_length.pointer).integer;
  }

  static final _id_nextClearBit = BitSet._class.instanceMethodId(
    r'nextClearBit',
    r'(I)I',
  );

  static final _nextClearBit =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Int32,)>,
              )
            >
          >('globalEnv_CallIntMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              core$_.int,
            )
          >();

  /// from: `public int nextClearBit(int i)`
  core$_.int nextClearBit(core$_.int i) {
    return _nextClearBit(
      reference.pointer,
      _id_nextClearBit.pointer,
      i,
    ).integer;
  }

  static final _id_nextSetBit = BitSet._class.instanceMethodId(
    r'nextSetBit',
    r'(I)I',
  );

  static final _nextSetBit =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Int32,)>,
              )
            >
          >('globalEnv_CallIntMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              core$_.int,
            )
          >();

  /// from: `public int nextSetBit(int i)`
  core$_.int nextSetBit(core$_.int i) {
    return _nextSetBit(reference.pointer, _id_nextSetBit.pointer, i).integer;
  }

  static final _id_or = BitSet._class.instanceMethodId(
    r'or',
    r'(Ljava/util/BitSet;)V',
  );

  static final _or =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void or(java.util.BitSet bitSet)`
  void or(BitSet? bitSet) {
    final _$bitSet = bitSet?.reference ?? jni$_.jNullReference;
    _or(reference.pointer, _id_or.pointer, _$bitSet.pointer).check();
  }

  static final _id_previousClearBit = BitSet._class.instanceMethodId(
    r'previousClearBit',
    r'(I)I',
  );

  static final _previousClearBit =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Int32,)>,
              )
            >
          >('globalEnv_CallIntMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              core$_.int,
            )
          >();

  /// from: `public int previousClearBit(int i)`
  core$_.int previousClearBit(core$_.int i) {
    return _previousClearBit(
      reference.pointer,
      _id_previousClearBit.pointer,
      i,
    ).integer;
  }

  static final _id_previousSetBit = BitSet._class.instanceMethodId(
    r'previousSetBit',
    r'(I)I',
  );

  static final _previousSetBit =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Int32,)>,
              )
            >
          >('globalEnv_CallIntMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              core$_.int,
            )
          >();

  /// from: `public int previousSetBit(int i)`
  core$_.int previousSetBit(core$_.int i) {
    return _previousSetBit(
      reference.pointer,
      _id_previousSetBit.pointer,
      i,
    ).integer;
  }

  static final _id_set = BitSet._class.instanceMethodId(r'set', r'(I)V');

  static final _set =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Int32,)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              core$_.int,
            )
          >();

  /// from: `public void set(int i)`
  void set(core$_.int i) {
    _set(reference.pointer, _id_set.pointer, i).check();
  }

  static final _id_set$1 = BitSet._class.instanceMethodId(r'set', r'(IZ)V');

  static final _set$1 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Int32, jni$_.Int32)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              core$_.int,
              core$_.int,
            )
          >();

  /// from: `public void set(int i, boolean z)`
  void set$1(core$_.int i, core$_.bool z) {
    _set$1(reference.pointer, _id_set$1.pointer, i, z ? 1 : 0).check();
  }

  static final _id_set$2 = BitSet._class.instanceMethodId(r'set', r'(II)V');

  static final _set$2 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Int32, jni$_.Int32)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              core$_.int,
              core$_.int,
            )
          >();

  /// from: `public void set(int i, int i1)`
  void set$2(core$_.int i, core$_.int i1) {
    _set$2(reference.pointer, _id_set$2.pointer, i, i1).check();
  }

  static final _id_set$3 = BitSet._class.instanceMethodId(r'set', r'(IIZ)V');

  static final _set$3 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Int32, jni$_.Int32, jni$_.Int32)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              core$_.int,
              core$_.int,
              core$_.int,
            )
          >();

  /// from: `public void set(int i, int i1, boolean z)`
  void set$3(core$_.int i, core$_.int i1, core$_.bool z) {
    _set$3(reference.pointer, _id_set$3.pointer, i, i1, z ? 1 : 0).check();
  }

  static final _id_size = BitSet._class.instanceMethodId(r'size', r'()I');

  static final _size =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallIntMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public int size()`
  core$_.int size() {
    return _size(reference.pointer, _id_size.pointer).integer;
  }

  static final _id_stream = BitSet._class.instanceMethodId(
    r'stream',
    r'()Ljava/util/stream/IntStream;',
  );

  static final _stream =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public java.util.stream.IntStream stream()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JObject? stream() {
    return _stream(
      reference.pointer,
      _id_stream.pointer,
    ).object<jni$_.JObject?>();
  }

  static final _id_toByteArray = BitSet._class.instanceMethodId(
    r'toByteArray',
    r'()[B',
  );

  static final _toByteArray =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public byte[] toByteArray()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JByteArray? toByteArray() {
    return _toByteArray(
      reference.pointer,
      _id_toByteArray.pointer,
    ).object<jni$_.JByteArray?>();
  }

  static final _id_toLongArray = BitSet._class.instanceMethodId(
    r'toLongArray',
    r'()[J',
  );

  static final _toLongArray =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public long[] toLongArray()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JLongArray? toLongArray() {
    return _toLongArray(
      reference.pointer,
      _id_toLongArray.pointer,
    ).object<jni$_.JLongArray?>();
  }

  static final _id_toString$1 = BitSet._class.instanceMethodId(
    r'toString',
    r'()Ljava/lang/String;',
  );

  static final _toString$1 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public java.lang.String toString()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JString? toString$1() {
    return _toString$1(
      reference.pointer,
      _id_toString$1.pointer,
    ).object<jni$_.JString?>();
  }

  static final _id_xor = BitSet._class.instanceMethodId(
    r'xor',
    r'(Ljava/util/BitSet;)V',
  );

  static final _xor =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void xor(java.util.BitSet bitSet)`
  void xor(BitSet? bitSet) {
    final _$bitSet = bitSet?.reference ?? jni$_.jNullReference;
    _xor(reference.pointer, _id_xor.pointer, _$bitSet.pointer).check();
  }
}

final class $BitSet$Type$ extends jni$_.JType<BitSet> {
  @jni$_.internal
  const $BitSet$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Ljava/util/BitSet;';
}
