// AUTO GENERATED BY JNIGEN 0.16.0. DO NOT EDIT!

// ignore_for_file: annotate_overrides
// ignore_for_file: argument_type_not_assignable
// ignore_for_file: camel_case_extensions
// ignore_for_file: camel_case_types
// ignore_for_file: constant_identifier_names
// ignore_for_file: comment_references
// ignore_for_file: doc_directive_unknown
// ignore_for_file: file_names
// ignore_for_file: inference_failure_on_untyped_parameter
// ignore_for_file: invalid_internal_annotation
// ignore_for_file: invalid_use_of_internal_member
// ignore_for_file: library_prefixes
// ignore_for_file: lines_longer_than_80_chars
// ignore_for_file: no_leading_underscores_for_library_prefixes
// ignore_for_file: no_leading_underscores_for_local_identifiers
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: only_throw_errors
// ignore_for_file: overridden_fields
// ignore_for_file: prefer_double_quotes
// ignore_for_file: unintended_html_in_doc_comment
// ignore_for_file: unnecessary_cast
// ignore_for_file: unnecessary_non_null_assertion
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: unused_element
// ignore_for_file: unused_field
// ignore_for_file: unused_import
// ignore_for_file: unused_local_variable
// ignore_for_file: unused_shown_name
// ignore_for_file: use_super_parameters

import 'dart:core' as core$_;
import 'dart:core' show Object, String;

import 'package:jni/_internal.dart' as jni$_;
import 'package:jni/jni.dart' as jni$_;

import '../MacAddress.dart' as macaddress$_;

/// from: `android.net.wifi.MloLink`
extension type MloLink._(jni$_.JObject _$this) implements jni$_.JObject {
  static final _class = jni$_.JClass.forName(r'android/net/wifi/MloLink');

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<MloLink> type = $MloLink$Type$();
  static final _id_CREATOR = _class.staticFieldId(
    r'CREATOR',
    r'Landroid/os/Parcelable$Creator;',
  );

  /// from: `static public final android.os.Parcelable$Creator<android.net.wifi.MloLink> CREATOR`
  /// The returned object must be released after use, by calling the [release] method.
  static jni$_.JObject get CREATOR =>
      _id_CREATOR.get(_class, jni$_.JObject.type) as jni$_.JObject;

  /// from: `static public final int INVALID_MLO_LINK_ID`
  static const INVALID_MLO_LINK_ID = -1;

  /// from: `static public final int MLO_LINK_STATE_ACTIVE`
  static const MLO_LINK_STATE_ACTIVE = 3;

  /// from: `static public final int MLO_LINK_STATE_IDLE`
  static const MLO_LINK_STATE_IDLE = 2;

  /// from: `static public final int MLO_LINK_STATE_INVALID`
  static const MLO_LINK_STATE_INVALID = 0;

  /// from: `static public final int MLO_LINK_STATE_UNASSOCIATED`
  static const MLO_LINK_STATE_UNASSOCIATED = 1;
  static final _id_new$ = _class.constructorId(r'()V');

  static final _new$ =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public void <init>()`
  /// The returned object must be released after use, by calling the [release] method.
  factory MloLink() {
    return _new$(_class.reference.pointer, _id_new$.pointer).object<MloLink>();
  }
}

extension MloLink$$Methods on MloLink {
  static final _id_describeContents = MloLink._class.instanceMethodId(
    r'describeContents',
    r'()I',
  );

  static final _describeContents =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallIntMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public int describeContents()`
  core$_.int describeContents() {
    return _describeContents(
      reference.pointer,
      _id_describeContents.pointer,
    ).integer;
  }

  static final _id_equals = MloLink._class.instanceMethodId(
    r'equals',
    r'(Ljava/lang/Object;)Z',
  );

  static final _equals =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallBooleanMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public boolean equals(java.lang.Object object)`
  core$_.bool equals(jni$_.JObject? object) {
    final _$object = object?.reference ?? jni$_.jNullReference;
    return _equals(
      reference.pointer,
      _id_equals.pointer,
      _$object.pointer,
    ).boolean;
  }

  static final _id_get$apMacAddress = MloLink._class.instanceMethodId(
    r'getApMacAddress',
    r'()Landroid/net/MacAddress;',
  );

  static final _get$apMacAddress =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public android.net.MacAddress getApMacAddress()`
  /// The returned object must be released after use, by calling the [release] method.
  macaddress$_.MacAddress? get apMacAddress {
    return _get$apMacAddress(
      reference.pointer,
      _id_get$apMacAddress.pointer,
    ).object<macaddress$_.MacAddress?>();
  }

  static final _id_get$band = MloLink._class.instanceMethodId(
    r'getBand',
    r'()I',
  );

  static final _get$band =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallIntMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public int getBand()`
  core$_.int get band {
    return _get$band(reference.pointer, _id_get$band.pointer).integer;
  }

  static final _id_get$channel = MloLink._class.instanceMethodId(
    r'getChannel',
    r'()I',
  );

  static final _get$channel =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallIntMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public int getChannel()`
  core$_.int get channel {
    return _get$channel(reference.pointer, _id_get$channel.pointer).integer;
  }

  static final _id_get$linkId = MloLink._class.instanceMethodId(
    r'getLinkId',
    r'()I',
  );

  static final _get$linkId =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallIntMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public int getLinkId()`
  core$_.int get linkId {
    return _get$linkId(reference.pointer, _id_get$linkId.pointer).integer;
  }

  static final _id_get$rssi = MloLink._class.instanceMethodId(
    r'getRssi',
    r'()I',
  );

  static final _get$rssi =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallIntMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public int getRssi()`
  core$_.int get rssi {
    return _get$rssi(reference.pointer, _id_get$rssi.pointer).integer;
  }

  static final _id_get$rxLinkSpeedMbps = MloLink._class.instanceMethodId(
    r'getRxLinkSpeedMbps',
    r'()I',
  );

  static final _get$rxLinkSpeedMbps =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallIntMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public int getRxLinkSpeedMbps()`
  core$_.int get rxLinkSpeedMbps {
    return _get$rxLinkSpeedMbps(
      reference.pointer,
      _id_get$rxLinkSpeedMbps.pointer,
    ).integer;
  }

  static final _id_get$staMacAddress = MloLink._class.instanceMethodId(
    r'getStaMacAddress',
    r'()Landroid/net/MacAddress;',
  );

  static final _get$staMacAddress =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public android.net.MacAddress getStaMacAddress()`
  /// The returned object must be released after use, by calling the [release] method.
  macaddress$_.MacAddress? get staMacAddress {
    return _get$staMacAddress(
      reference.pointer,
      _id_get$staMacAddress.pointer,
    ).object<macaddress$_.MacAddress?>();
  }

  static final _id_get$state = MloLink._class.instanceMethodId(
    r'getState',
    r'()I',
  );

  static final _get$state =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallIntMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public int getState()`
  core$_.int get state {
    return _get$state(reference.pointer, _id_get$state.pointer).integer;
  }

  static final _id_get$txLinkSpeedMbps = MloLink._class.instanceMethodId(
    r'getTxLinkSpeedMbps',
    r'()I',
  );

  static final _get$txLinkSpeedMbps =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallIntMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public int getTxLinkSpeedMbps()`
  core$_.int get txLinkSpeedMbps {
    return _get$txLinkSpeedMbps(
      reference.pointer,
      _id_get$txLinkSpeedMbps.pointer,
    ).integer;
  }

  static final _id_hashCode$1 = MloLink._class.instanceMethodId(
    r'hashCode',
    r'()I',
  );

  static final _hashCode$1 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallIntMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public int hashCode()`
  core$_.int hashCode$1() {
    return _hashCode$1(reference.pointer, _id_hashCode$1.pointer).integer;
  }

  static final _id_toString$1 = MloLink._class.instanceMethodId(
    r'toString',
    r'()Ljava/lang/String;',
  );

  static final _toString$1 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public java.lang.String toString()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JString? toString$1() {
    return _toString$1(
      reference.pointer,
      _id_toString$1.pointer,
    ).object<jni$_.JString?>();
  }

  static final _id_writeToParcel = MloLink._class.instanceMethodId(
    r'writeToParcel',
    r'(Landroid/os/Parcel;I)V',
  );

  static final _writeToParcel =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>, jni$_.Int32)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              core$_.int,
            )
          >();

  /// from: `public void writeToParcel(android.os.Parcel parcel, int i)`
  void writeToParcel(jni$_.JObject parcel, core$_.int i) {
    final _$parcel = parcel.reference;
    _writeToParcel(
      reference.pointer,
      _id_writeToParcel.pointer,
      _$parcel.pointer,
      i,
    ).check();
  }
}

final class $MloLink$Type$ extends jni$_.JType<MloLink> {
  @jni$_.internal
  const $MloLink$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Landroid/net/wifi/MloLink;';
}
