// AUTO GENERATED BY JNIGEN 0.15.0. DO NOT EDIT!

// ignore_for_file: annotate_overrides
// ignore_for_file: argument_type_not_assignable
// ignore_for_file: camel_case_extensions
// ignore_for_file: camel_case_types
// ignore_for_file: constant_identifier_names
// ignore_for_file: comment_references
// ignore_for_file: doc_directive_unknown
// ignore_for_file: file_names
// ignore_for_file: inference_failure_on_untyped_parameter
// ignore_for_file: invalid_internal_annotation
// ignore_for_file: invalid_use_of_internal_member
// ignore_for_file: library_prefixes
// ignore_for_file: lines_longer_than_80_chars
// ignore_for_file: no_leading_underscores_for_library_prefixes
// ignore_for_file: no_leading_underscores_for_local_identifiers
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: only_throw_errors
// ignore_for_file: overridden_fields
// ignore_for_file: prefer_double_quotes
// ignore_for_file: unintended_html_in_doc_comment
// ignore_for_file: unnecessary_cast
// ignore_for_file: unnecessary_non_null_assertion
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: unused_element
// ignore_for_file: unused_field
// ignore_for_file: unused_import
// ignore_for_file: unused_local_variable
// ignore_for_file: unused_shown_name
// ignore_for_file: use_super_parameters

import 'dart:core' as core$_;
import 'dart:core' show Object, String, bool, double, int;

import 'package:jni/_internal.dart' as jni$_;
import 'package:jni/jni.dart' as jni$_;

import '../../../../android/net/LinkAddress.dart' as linkaddress$_;

import '../../../../java/net/InetAddress.dart' as inetaddress$_;

import '../../../../java/net/InterfaceAddress.dart' as interfaceaddress$_;

/// from: `dev.zeekr.invictus_android.net.InvictusLinkAddress$Companion`
class InvictusLinkAddress$Companion extends jni$_.JObject {
  @jni$_.internal
  @core$_.override
  final jni$_.JType<InvictusLinkAddress$Companion> $type;

  @jni$_.internal
  InvictusLinkAddress$Companion.fromReference(jni$_.JReference reference)
    : $type = type,
      super.fromReference(reference);

  static final _class = jni$_.JClass.forName(
    r'dev/zeekr/invictus_android/net/InvictusLinkAddress$Companion',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<InvictusLinkAddress$Companion?> nullableType =
      $InvictusLinkAddress$Companion$NullableType$();

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<InvictusLinkAddress$Companion> type =
      $InvictusLinkAddress$Companion$Type$();
  static final _id_getClazz = _class.instanceMethodId(
    r'getClazz',
    r'()Ljava/lang/Class;',
  );

  static final _getClazz =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public final java.lang.Class<android.net.LinkAddress> getClazz()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JObject getClazz() {
    return _getClazz(
      reference.pointer,
      _id_getClazz as jni$_.JMethodIDPtr,
    ).object<jni$_.JObject>(const jni$_.$JObject$Type$());
  }

  static final _id_new$ = _class.constructorId(
    r'(Lkotlin/jvm/internal/DefaultConstructorMarker;)V',
  );

  static final _new$ =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `synthetic public void <init>(kotlin.jvm.internal.DefaultConstructorMarker defaultConstructorMarker)`
  /// The returned object must be released after use, by calling the [release] method.
  factory InvictusLinkAddress$Companion(
    jni$_.JObject? defaultConstructorMarker,
  ) {
    final _$defaultConstructorMarker =
        defaultConstructorMarker?.reference ?? jni$_.jNullReference;
    return InvictusLinkAddress$Companion.fromReference(
      _new$(
        _class.reference.pointer,
        _id_new$ as jni$_.JMethodIDPtr,
        _$defaultConstructorMarker.pointer,
      ).reference,
    );
  }
}

final class $InvictusLinkAddress$Companion$NullableType$
    extends jni$_.JType<InvictusLinkAddress$Companion?> {
  @jni$_.internal
  const $InvictusLinkAddress$Companion$NullableType$();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Ldev/zeekr/invictus_android/net/InvictusLinkAddress$Companion;';

  @jni$_.internal
  @core$_.override
  InvictusLinkAddress$Companion? fromReference(jni$_.JReference reference) =>
      reference.isNull
      ? null
      : InvictusLinkAddress$Companion.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$Type$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<InvictusLinkAddress$Companion?> get nullableType => this;

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($InvictusLinkAddress$Companion$NullableType$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType ==
            ($InvictusLinkAddress$Companion$NullableType$) &&
        other is $InvictusLinkAddress$Companion$NullableType$;
  }
}

final class $InvictusLinkAddress$Companion$Type$
    extends jni$_.JType<InvictusLinkAddress$Companion> {
  @jni$_.internal
  const $InvictusLinkAddress$Companion$Type$();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Ldev/zeekr/invictus_android/net/InvictusLinkAddress$Companion;';

  @jni$_.internal
  @core$_.override
  InvictusLinkAddress$Companion fromReference(jni$_.JReference reference) =>
      InvictusLinkAddress$Companion.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$Type$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<InvictusLinkAddress$Companion?> get nullableType =>
      const $InvictusLinkAddress$Companion$NullableType$();

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($InvictusLinkAddress$Companion$Type$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($InvictusLinkAddress$Companion$Type$) &&
        other is $InvictusLinkAddress$Companion$Type$;
  }
}

/// from: `dev.zeekr.invictus_android.net.InvictusLinkAddress`
class InvictusLinkAddress extends jni$_.JObject {
  @jni$_.internal
  @core$_.override
  final jni$_.JType<InvictusLinkAddress> $type;

  @jni$_.internal
  InvictusLinkAddress.fromReference(jni$_.JReference reference)
    : $type = type,
      super.fromReference(reference);

  static final _class = jni$_.JClass.forName(
    r'dev/zeekr/invictus_android/net/InvictusLinkAddress',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<InvictusLinkAddress?> nullableType =
      $InvictusLinkAddress$NullableType$();

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<InvictusLinkAddress> type =
      $InvictusLinkAddress$Type$();
  static final _id_Companion = _class.staticFieldId(
    r'Companion',
    r'Ldev/zeekr/invictus_android/net/InvictusLinkAddress$Companion;',
  );

  /// from: `static public final dev.zeekr.invictus_android.net.InvictusLinkAddress$Companion Companion`
  /// The returned object must be released after use, by calling the [release] method.
  static InvictusLinkAddress$Companion get Companion =>
      _id_Companion.get(_class, const $InvictusLinkAddress$Companion$Type$());

  static final _id_getObj = _class.instanceMethodId(
    r'getObj',
    r'()Landroid/net/LinkAddress;',
  );

  static final _getObj =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public final android.net.LinkAddress getObj()`
  /// The returned object must be released after use, by calling the [release] method.
  linkaddress$_.LinkAddress getObj() {
    return _getObj(
      reference.pointer,
      _id_getObj as jni$_.JMethodIDPtr,
    ).object<linkaddress$_.LinkAddress>(
      const linkaddress$_.$LinkAddress$Type$(),
    );
  }

  static final _id_new$ = _class.constructorId(r'(Landroid/net/LinkAddress;)V');

  static final _new$ =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void <init>(android.net.LinkAddress linkAddress)`
  /// The returned object must be released after use, by calling the [release] method.
  factory InvictusLinkAddress(linkaddress$_.LinkAddress linkAddress) {
    final _$linkAddress = linkAddress.reference;
    return InvictusLinkAddress.fromReference(
      _new$(
        _class.reference.pointer,
        _id_new$ as jni$_.JMethodIDPtr,
        _$linkAddress.pointer,
      ).reference,
    );
  }

  static final _id_new$1 = _class.constructorId(
    r'(Ljava/net/InetAddress;III)V',
  );

  static final _new$1 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                  )
                >,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              int,
              int,
              int,
            )
          >();

  /// from: `public void <init>(java.net.InetAddress inetAddress, int i, int i1, int i2)`
  /// The returned object must be released after use, by calling the [release] method.
  factory InvictusLinkAddress.new$1(
    inetaddress$_.InetAddress inetAddress,
    int i,
    int i1,
    int i2,
  ) {
    final _$inetAddress = inetAddress.reference;
    return InvictusLinkAddress.fromReference(
      _new$1(
        _class.reference.pointer,
        _id_new$1 as jni$_.JMethodIDPtr,
        _$inetAddress.pointer,
        i,
        i1,
        i2,
      ).reference,
    );
  }

  static final _id_new$2 = _class.constructorId(
    r'(Ljava/net/InetAddress;IIIJJ)V',
  );

  static final _new$2 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int64,
                    jni$_.Int64,
                  )
                >,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              int,
              int,
              int,
              int,
              int,
            )
          >();

  /// from: `public void <init>(java.net.InetAddress inetAddress, int i, int i1, int i2, long j, long j1)`
  /// The returned object must be released after use, by calling the [release] method.
  factory InvictusLinkAddress.new$2(
    inetaddress$_.InetAddress inetAddress,
    int i,
    int i1,
    int i2,
    int j,
    int j1,
  ) {
    final _$inetAddress = inetAddress.reference;
    return InvictusLinkAddress.fromReference(
      _new$2(
        _class.reference.pointer,
        _id_new$2 as jni$_.JMethodIDPtr,
        _$inetAddress.pointer,
        i,
        i1,
        i2,
        j,
        j1,
      ).reference,
    );
  }

  static final _id_new$3 = _class.constructorId(r'(Ljava/net/InetAddress;I)V');

  static final _new$3 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>, jni$_.Int32)>,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              int,
            )
          >();

  /// from: `public void <init>(java.net.InetAddress inetAddress, int i)`
  /// The returned object must be released after use, by calling the [release] method.
  factory InvictusLinkAddress.new$3(
    inetaddress$_.InetAddress inetAddress,
    int i,
  ) {
    final _$inetAddress = inetAddress.reference;
    return InvictusLinkAddress.fromReference(
      _new$3(
        _class.reference.pointer,
        _id_new$3 as jni$_.JMethodIDPtr,
        _$inetAddress.pointer,
        i,
      ).reference,
    );
  }

  static final _id_new$4 = _class.constructorId(
    r'(Ljava/net/InterfaceAddress;)V',
  );

  static final _new$4 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void <init>(java.net.InterfaceAddress interfaceAddress)`
  /// The returned object must be released after use, by calling the [release] method.
  factory InvictusLinkAddress.new$4(
    interfaceaddress$_.InterfaceAddress interfaceAddress,
  ) {
    final _$interfaceAddress = interfaceAddress.reference;
    return InvictusLinkAddress.fromReference(
      _new$4(
        _class.reference.pointer,
        _id_new$4 as jni$_.JMethodIDPtr,
        _$interfaceAddress.pointer,
      ).reference,
    );
  }

  static final _id_new$5 = _class.constructorId(r'(Ljava/lang/String;)V');

  static final _new$5 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void <init>(java.lang.String string)`
  /// The returned object must be released after use, by calling the [release] method.
  factory InvictusLinkAddress.new$5(jni$_.JString string) {
    final _$string = string.reference;
    return InvictusLinkAddress.fromReference(
      _new$5(
        _class.reference.pointer,
        _id_new$5 as jni$_.JMethodIDPtr,
        _$string.pointer,
      ).reference,
    );
  }

  static final _id_new$6 = _class.constructorId(r'(Ljava/lang/String;II)V');

  static final _new$6 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (jni$_.Pointer<jni$_.Void>, jni$_.Int32, jni$_.Int32)
                >,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              int,
              int,
            )
          >();

  /// from: `public void <init>(java.lang.String string, int i, int i1)`
  /// The returned object must be released after use, by calling the [release] method.
  factory InvictusLinkAddress.new$6(jni$_.JString string, int i, int i1) {
    final _$string = string.reference;
    return InvictusLinkAddress.fromReference(
      _new$6(
        _class.reference.pointer,
        _id_new$6 as jni$_.JMethodIDPtr,
        _$string.pointer,
        i,
        i1,
      ).reference,
    );
  }
}

final class $InvictusLinkAddress$NullableType$
    extends jni$_.JType<InvictusLinkAddress?> {
  @jni$_.internal
  const $InvictusLinkAddress$NullableType$();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Ldev/zeekr/invictus_android/net/InvictusLinkAddress;';

  @jni$_.internal
  @core$_.override
  InvictusLinkAddress? fromReference(jni$_.JReference reference) =>
      reference.isNull ? null : InvictusLinkAddress.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$Type$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<InvictusLinkAddress?> get nullableType => this;

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($InvictusLinkAddress$NullableType$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($InvictusLinkAddress$NullableType$) &&
        other is $InvictusLinkAddress$NullableType$;
  }
}

final class $InvictusLinkAddress$Type$
    extends jni$_.JType<InvictusLinkAddress> {
  @jni$_.internal
  const $InvictusLinkAddress$Type$();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Ldev/zeekr/invictus_android/net/InvictusLinkAddress;';

  @jni$_.internal
  @core$_.override
  InvictusLinkAddress fromReference(jni$_.JReference reference) =>
      InvictusLinkAddress.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$Type$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<InvictusLinkAddress?> get nullableType =>
      const $InvictusLinkAddress$NullableType$();

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($InvictusLinkAddress$Type$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($InvictusLinkAddress$Type$) &&
        other is $InvictusLinkAddress$Type$;
  }
}
