import 'package:invictus_android/src/impl.dart';
import 'package:invictus_android/src/jni.dart' as jni;
import 'package:invictus_api/invictus_api.dart';

/// Class that provides a privileged API to capture and consume bugreports.
///
/// This class may only be used by apps that currently have carrier privileges (see
/// `android.telephony.TelephonyManager#hasCarrierPrivileges`) on an active SIM or
/// priv-apps explicitly allowed by the device manufacturer.
///
/// Only one bugreport can be generated by the system at a time.
final class BugreportManagerImpl extends ObjectImpl
    implements BugreportManager {
  @override
  final jni.BugreportManager api;

  BugreportManagerImpl.internal(this.api);

  /// The executor to execute callback methods.
  jni.Executor get executorApi =>
      ArgumentError.checkNotNull(jni.context.mainExecutor, 'mainExecutor');

  /// Cancels the currently running bugreport.
  ///
  /// Apps are only able to cancel their own bugreports. App A cannot cancel a bugreport
  /// started by app B.
  ///
  /// Requires permission: `android.Manifest.permission.DUMP` or that the calling app has
  /// carrier privileges (see `android.telephony.TelephonyManager#hasCarrierPrivileges`)
  /// on any active subscription.
  ///
  /// throws SecurityException if trying to cancel another app's bugreport in progress
  @override
  void cancelBugreport() => api.cancelBugreport();

  /// Speculatively pre-dumps UI data for a bugreport request that might come later.
  ///
  /// Triggers the dump of certain critical UI data, e.g. traces stored in short
  /// ring buffers that might get lost by the time the actual bugreport is requested.
  ///
  /// [BugreportManager.startBugreport] will then pick the pre-dumped data if both of the
  /// following conditions are met:
  /// - [BugreportParams$Flag.usePredumpedUiData] is specified.
  /// - [preDumpUiData] and [startBugreport] were called by the same UID.
  ///
  /// Requires the `android.Manifest.permission.DUMP` permission.
  @override
  void preDumpUiData() =>
      jni.BugreportManagerCompat.INSTANCE.preDumpUiData(api);

  /// Requests a bugreport.
  ///
  /// This requests the platform/system to take a bugreport and makes the final bugreport
  /// available to the user. The user may choose to share it with another app, but the
  /// bugreport is never given back directly to the app that requested it.
  ///
  /// [params] [BugreportParams] that specify what kind of a bugreport should be taken,
  /// please note that not all kinds of bugreport allow for a progress notification.
  ///
  /// [shareTitle] title on the final share notification.
  ///
  /// [shareDescription] description on the final share notification.
  ///
  /// Requires the `android.Manifest.permission.DUMP` permission.
  @override
  void requestBugreport({
    required BugreportParams params,
    String? shareTitle,
    String? shareDescription,
  }) => jni.BugreportManagerCompat.INSTANCE.requestBugreport(
    api,
    params.api,
    shareTitle?.api.as(jni.CharSequence.type),
    shareDescription?.api.as(jni.CharSequence.type),
  );

  /// Retrieves a previously generated bugreport.
  ///
  /// The previously generated bugreport must have been generated by calling
  /// [startBugreport] with the [BugreportParams$Flag.deferConsent] flag set. The
  /// bugreport file returned by the `onFinished(String)` callback of
  /// [BugreportManager$BugreportCallback] for a previously generated bugreport must be
  /// passed to this method. A caller may only retrieve bugreports that they have
  /// previously requested.
  ///
  /// The bugreport artifacts will be copied over to the given file descriptor only if the
  /// user consents to sharing with the calling app.
  ///
  /// [BugreportManager] takes ownership of [bugreportFd].
  ///
  /// The caller may only request to retrieve a given bugreport once. Subsequent calls
  /// will fail with error code
  /// [BugreportManager$BugreportCallback$ErrorCode.noBugreportToRetrieve].
  ///
  /// [bugreportFile] the identifier for a bugreport that was previously generated for this
  /// caller using [startBugreport].
  ///
  /// [bugreportFd] file to copy over the previous bugreport. This should be opened in
  /// write-only, append mode.
  ///
  /// [callback] callback for progress and status updates.
  ///
  /// Requires the `android.Manifest.permission.DUMP` permission.
  @override
  void retrieveBugreport({
    required String bugreportFile,
    required ParcelFileDescriptor bugreportFd,
    required BugreportManager$BugreportCallback callback,
  }) => jni.BugreportManagerCompat.INSTANCE.retrieveBugreport(
    api,
    bugreportFile.api,
    bugreportFd.api,
    executorApi,
    callback.apiCompat,
  );

  /// Starts a bugreport.
  ///
  /// This starts a bugreport in the background. However the call itself can take several
  /// seconds to return in the worst case. [callback] will receive progress and status
  /// updates.
  ///
  /// The bugreport artifacts will be copied over to the given file descriptors only if
  /// the user consents to sharing with the calling app. If the
  /// [BugreportParams$Flag.deferConsent] flag is set, user consent will be deferred and
  /// no files will be copied to the given file descriptors.
  ///
  /// [BugreportManager] takes ownership of [bugreportFd] and [screenshotFd].
  ///
  /// [bugreportFd] file to write the bugreport. This should be opened in write-only,
  /// append mode.
  ///
  /// [screenshotFd] file to write the screenshot, if necessary. This should be opened in
  /// write-only, append mode.
  ///
  /// [params] options that specify what kind of a bugreport should be taken.
  ///
  /// [callback] callback for progress and status updates.
  ///
  /// Requires the `android.Manifest.permission.DUMP` permission.
  @override
  void startBugreport({
    required ParcelFileDescriptor bugreportFd,
    ParcelFileDescriptor? screenshotFd,
    required BugreportParams params,
    required BugreportManager$BugreportCallback callback,
  }) => jni.BugreportManagerCompat.INSTANCE.startBugreport(
    api,
    bugreportFd.api,
    screenshotFd?.api,
    params.api,
    executorApi,
    callback.apiCompat,
  );

  /// Starts a connectivity bugreport.
  ///
  /// The connectivity bugreport is a specialized version of bugreport that only includes
  /// information specifically for debugging connectivity-related issues (e.g. telephony,
  /// wi-fi, and IP networking issues). It is intended primarily for use by OEMs and
  /// network providers such as mobile network operators. In addition to generally
  /// excluding information that isn't targeted to connectivity debugging, this type of
  /// bugreport excludes PII and sensitive information that isn't strictly necessary for
  /// connectivity debugging.
  ///
  /// The calling app MUST have a context-specific reason for requesting a connectivity
  /// bugreport, such as detecting a connectivity-related issue. This API SHALL NOT be used
  /// to perform random sampling from a fleet of public end-user devices.
  ///
  /// Calling this API will cause the system to ask the user for consent every single time.
  /// The bugreport artifacts will be copied over to the given file descriptors only if the
  /// user consents to sharing with the calling app.
  ///
  /// This starts a bugreport in the background. However the call itself can take several
  /// seconds to return in the worst case. [callback] will receive progress and status
  /// updates.
  ///
  /// Requires that the calling app has carrier privileges (see
  /// `android.telephony.TelephonyManager#hasCarrierPrivileges`) on any active
  /// subscription.
  ///
  /// [bugreportFd] file to write the bugreport. This should be opened in write-only,
  /// append mode.
  ///
  /// [callback] callback for progress and status updates.
  ///
  /// ANDROID NOTE: This method is bound by jnigen and invoked directly on
  /// `android.os.BugreportManager`, unlike [startBugreport], [retrieveBugreport],
  /// [requestBugreport] and [preDumpUiData], which are invoked through
  /// `BugreportManagerCompat`.
  @override
  void startConnectivityBugreport({
    required ParcelFileDescriptor bugreportFd,
    required BugreportManager$BugreportCallback callback,
  }) => api.startConnectivityBugreport(
    bugreportFd.api,
    executorApi,
    callback.api,
  );
}

/// An interface describing the callback for bugreport progress and status.
///
/// Callers will receive `onProgress` calls as the bugreport progresses, followed by a
/// terminal call to either `onFinished` or `onError`.
///
/// If an issue is encountered while starting the bugreport asynchronously, callers will
/// receive an `onError` call without any `onProgress` callbacks.
///
/// ANDROID NOTE: On Android the callback is bridged twice, because the framework APIs
/// bound by jnigen require a `android.os.BugreportManager$BugreportCallback` while the
/// hidden APIs invoked through `BugreportManagerCompat` require a
/// `BugreportManagerCompat$BugreportCallbackCompat`. Both bridges forward to the same
/// Dart callbacks.
final class BugreportManager$BugreportCallbackImpl extends ObjectImpl
    implements BugreportManager$BugreportCallback {
  /// The `android.os.BugreportManager$BugreportCallback` instance passed to the
  /// framework APIs bound by jnigen, e.g.
  /// [BugreportManagerImpl.startConnectivityBugreport].
  @override
  final jni.BugreportManager$BugreportCallback api;

  /// The `BugreportManagerCompat$BugreportCallbackCompat` instance passed to the hidden
  /// APIs invoked through `BugreportManagerCompat`, e.g.
  /// [BugreportManagerImpl.startBugreport] and
  /// [BugreportManagerImpl.retrieveBugreport].
  final jni.BugreportManagerCompat$BugreportCallbackCompat apiCompat;

  BugreportManager$BugreportCallbackImpl.internal(this.api, this.apiCompat);
}

final class BugreportManagerChannelImpl extends BugreportManagerChannel {
  @override
  BugreportManager create() {
    final apiOrNull = jni.ContextCompat.getSystemService<jni.BugreportManager>(
      jni.context,
      jni.BugreportManager.type.jClass,
    );
    final api = ArgumentError.checkNotNull(apiOrNull, 'api');
    return BugreportManagerImpl.internal(api);
  }

  @override
  BugreportManager$BugreportCallback createBugreportCallback({
    void Function(double progress)? onProgress,
    void Function(BugreportManager$BugreportCallback$ErrorCode errorCode)?
    onError,
    void Function()? onFinished,
    void Function(String bugreportFile)? onFinished$1,
    void Function()? onEarlyReportFinished,
  }) {
    final api = jni.JniBugreportManager$JniBugreportCallbackImpl(
      jni.JniBugreportManager$JniBugreportCallback.implement(
        jni.$JniBugreportManager$JniBugreportCallback(
          onProgress: (progress) => onProgress?.call(progress),
          onError: (errorCode) =>
              onError?.call(errorCode.bugreportCallback$ErrorCodeImpl),
          onFinished: () => onFinished?.call(),
          onEarlyReportFinished: () => onEarlyReportFinished?.call(),
        ),
      ),
    );
    final apiCompat =
        jni.JniBugreportManagerCompat$JniBugreportCallbackCompatImpl(
          jni.context,
          jni.JniBugreportManagerCompat$JniBugreportCallbackCompat.implement(
            jni.$JniBugreportManagerCompat$JniBugreportCallbackCompat(
              onProgress: (progress) => onProgress?.call(progress),
              onError: (errorCode) =>
                  onError?.call(errorCode.bugreportCallback$ErrorCodeImpl),
              onFinished: () => onFinished?.call(),
              onFinished$1: (bugreportFile) =>
                  onFinished$1?.call(bugreportFile.impl),
              onEarlyReportFinished: () => onEarlyReportFinished?.call(),
            ),
          ),
        );
    return BugreportManager$BugreportCallbackImpl.internal(api, apiCompat);
  }
}

extension Invictus$JBugreportManagerX on jni.BugreportManager {
  BugreportManager get impl => BugreportManagerImpl.internal(this);
}

extension Invictus$BugreportManagerX on BugreportManager {
  jni.BugreportManager get api {
    final impl = this;
    if (impl is! BugreportManagerImpl) throw TypeError();
    return impl.api;
  }
}

extension Invictus$BugreportManager$BugreportCallbackX
    on BugreportManager$BugreportCallback {
  jni.BugreportManager$BugreportCallback get api {
    final impl = this;
    if (impl is! BugreportManager$BugreportCallbackImpl) throw TypeError();
    return impl.api;
  }

  jni.BugreportManagerCompat$BugreportCallbackCompat get apiCompat {
    final impl = this;
    if (impl is! BugreportManager$BugreportCallbackImpl) throw TypeError();
    return impl.apiCompat;
  }
}

extension Invictus$JBugreportCallbackCompat$intX on int {
  BugreportManager$BugreportCallback$ErrorCode
  get bugreportCallback$ErrorCodeImpl {
    if (this ==
        jni
            .BugreportManagerCompat$BugreportCallbackCompat
            .Companion
            .bUGREPORT_ERROR_INVALID_INPUT) {
      return .invalidInput;
    }
    if (this ==
        jni
            .BugreportManagerCompat$BugreportCallbackCompat
            .Companion
            .bUGREPORT_ERROR_RUNTIME) {
      return .runtime;
    }
    if (this ==
        jni
            .BugreportManagerCompat$BugreportCallbackCompat
            .Companion
            .bUGREPORT_ERROR_USER_DENIED_CONSENT) {
      return .userDeniedConsent;
    }
    if (this ==
        jni
            .BugreportManagerCompat$BugreportCallbackCompat
            .Companion
            .bUGREPORT_ERROR_USER_CONSENT_TIMED_OUT) {
      return .userConsentTimedOut;
    }
    if (this ==
        jni
            .BugreportManagerCompat$BugreportCallbackCompat
            .Companion
            .bUGREPORT_ERROR_ANOTHER_REPORT_IN_PROGRESS) {
      return .anotherReportInProgress;
    }
    if (this ==
        jni
            .BugreportManagerCompat$BugreportCallbackCompat
            .Companion
            .bUGREPORT_ERROR_NO_BUGREPORT_TO_RETRIEVE) {
      return .noBugreportToRetrieve;
    }
    throw ArgumentError.value(this, 'bugreportCallback\$ErrorCode');
  }
}
