name: invictus_darwin
description: "iOS and macOS implementation of the invictus plugin."
version: 1.0.0-dev.9
repository: https://github.com/yanshouwang/invictus
issue_tracker: https://github.com/yanshouwang/invictus/issues

resolution: workspace

environment:
  sdk: ^3.12.0
  flutter: '>=3.44.0'

dependencies:
  flutter:
    sdk: flutter
  invictus_api: ^1.0.0-dev.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    implements: invictus
    platforms:
      ios:
        sharedDarwinSource: true
        pluginClass: InvictusDarwinPlugin
        dartPluginClass: InvictusDarwinPlugin
      macos:
        sharedDarwinSource: true
        pluginClass: InvictusDarwinPlugin
        dartPluginClass: InvictusDarwinPlugin
